### PR TITLE
8305329: [8u] Unify test libraries into single test library - step 1

### PR DESCRIPTION
**Pull request by zzambers**
I would like to start effort to unify test libraries in openjdk 8 into one unified library. This is first step of that effort, which moves newest copy of jdk test library (added with jfr backport) from `jdk/test/lib` to `test/lib`. For more details please continue reading. 

**Problem:**
Test libraries in jdk8 are a bit messy.
There are currently 3 different test libraries:
- hotspot testlibrary - placed in [hotspot/test/testlibrary](https://github.com/openjdk/jdk8u-dev/tree/89aeae16e85ddfbd581cb86d0b0480b1e2d50e99/hotspot/test/testlibrary), (pkgs `com.oracle.java.testlibrary`, `sun.hotspot...` ), includes testlibrary tests in [hotspot/test/testlibrary_tests](https://github.com/openjdk/jdk8u-dev/tree/89aeae16e85ddfbd581cb86d0b0480b1e2d50e99/hotspot/test/testlibrary_tests)
- jdk testlibrary (old) - placed in [jdk/test/lib/testlibrary](https://github.com/openjdk/jdk8u-dev/tree/master/jdk/test/lib/testlibrary), (pkgs `jdk.testlibrary`, `com.oracle.testlibrary.jsr292`)
- jdk test lib - placed directly in [jdk/test/lib](https://github.com/openjdk/jdk8u-dev/tree/master/jdk/test/lib), was added with [jfr backport](https://github.com/openjdk/jdk8u-dev/commit/df7e09043392d5952d522a28702c6e5ec3e8492e), (pkgs `jdk.test.lib` `sun.hotspot...`)

Many test library classes exist in multiple different copies (using different pkgs). Few examples:
- Platform.java - 3 copies ([hs](https://github.com/openjdk/jdk8u-dev/blob/89aeae16e85ddfbd581cb86d0b0480b1e2d50e99/hotspot/test/testlibrary/com/oracle/java/testlibrary/Platform.java), [jdk (old)](https://github.com/openjdk/jdk8u-dev/blob/master/jdk/test/lib/testlibrary/jdk/testlibrary/Platform.java), [jdk (jfr)](https://github.com/openjdk/jdk8u-dev/blob/master/jdk/test/lib/jdk/test/lib/Platform.java))
- OutputAnalyzer.java - 3 copies ([hs](https://github.com/openjdk/jdk8u-dev/blob/89aeae16e85ddfbd581cb86d0b0480b1e2d50e99/hotspot/test/testlibrary/com/oracle/java/testlibrary/OutputAnalyzer.java), [jdk (old)](https://github.com/openjdk/jdk8u-dev/blob/master/jdk/test/lib/testlibrary/jdk/testlibrary/OutputAnalyzer.java), [jdk (jfr)](https://github.com/openjdk/jdk8u-dev/blob/master/jdk/test/lib/jdk/test/lib/process/OutputAnalyzer.java))
- WhiteBox.java - 2 copies ([hotspot](https://github.com/openjdk/jdk8u-dev/blob/89aeae16e85ddfbd581cb86d0b0480b1e2d50e99/hotspot/test/testlibrary/whitebox/sun/hotspot/WhiteBox.java), [jdk (jfr)](https://github.com/openjdk/jdk8u-dev/blob/master/jdk/test/lib/sun/hotspot/WhiteBox.java))

Few additional observations:
- classes in jdk test lib (jfr) use java packages compatible with newer jdks, other 2 don't (other 2 are actually not even compatible with each other)
- test lib added with jfr has newest classes, but some of them are NOT JDK8 compatible, some of them do not even compile on 8 (see e.g. [SecurityTools.java](https://github.com/openjdk/jdk8u-dev/blob/cd40350f0e69faf4d9a4658408798eb6e389f573/jdk/test/lib/jdk/test/lib/SecurityTools.java#L86), [InMemoryJavaCompiler.java](https://github.com/openjdk/jdk8u-dev/blob/cd40350f0e69faf4d9a4658408798eb6e389f573/jdk/test/lib/jdk/test/lib/compiler/InMemoryJavaCompiler.java#L146)  ...) , some whitebox stuff in `sun.hotspot` also seem incompatible with 8 (e.g. [NMethod.java](https://github.com/openjdk/jdk8u-dev/blob/89aeae16e85ddfbd581cb86d0b0480b1e2d50e99/jdk/test/lib/sun/hotspot/code/NMethod.java#L37) (compare to [NMethod.java](https://github.com/openjdk/jdk8u-dev/blob/cd40350f0e69faf4d9a4658408798eb6e389f573/hotspot/test/testlibrary/whitebox/sun/hotspot/code/NMethod.java#L37) from hs))
- most jdk tests (with exception of jfr ones) use old testlibrary, but few tests already started using test lib added with jfr
- paths to test lib as specified  `@library` jtreg tag is different from newer jdks (for all 3 test libraries)

This situation complicates backporting and leads to confusion. (What is correct library path? What package test lib classes use?  Which library to use and to which one do backports? Which part are broken and why? etc...)
See some examples: https://github.com/openjdk/jdk8u-dev/pull/129 https://github.com/openjdk/jdk8u-dev/pull/255#issuecomment-1412522724

**Solution:**
Proposed solution is to have single test library placed in `test/lib` directory (+ test library tests in `test/lib-test`) by fixing/merging test libraries. (same locations are used in newer [jdks](https://github.com/openjdk/jdk17u-dev/tree/master/test/lib))
Goal is following:
- single test library, removed code duplication
- all test lib classes compatible with JDK8
- locations of test lib files and java packages (used by test library classes) same as in later jdks
- path as specified by `@library` jtreg tag compatible with later jdks  (`@library /test/lib`)
- only test lib is moved. Tests and `TEST.ROOT` files are not moved, so this should not break existing CIs.

Because this is big change it should be performed in steps:
1. move jdk test library added by jfr to `test/lib` and do necessary modifications to tests (add `external.lib.roots` to `TEST.ROOT` files, modify `@library` tag of affected test)
2. Fix test lib in new location to work with hotspot tests (fix/merge with hotspot testlibrary), modify hotpot tests to use it, remove hotspot testlibrary 
3. continue with jdk tests, doing more fixes to test lib, if necessary (fix/merge with jdk testlibrary), eventually migrating all tests and removing jdk testlibrary (old)

**Changes in this PR:**
This is just the first step and consist of:
- moved test lib classes `jdk/test/lib` -> `test/lib` (excluding `testlibrary`, `security` dirs belonging to the old jdk testlibrary)
- added appropriate `external.lib.roots` to `TEST.ROOT` files of jdk and hotspot
- modified affected tests to use moved library (just modifications of `@library`, with excpetion of `TestNative.sh`)

**Testing:**
tier1: passed (see Checks)
jdk_core: [OK](https://github.com/zzambers/jdk-tester/actions/runs/4481657956/jobs/8053572622) (no regressions to [master](https://github.com/zzambers/jdk-tester/actions/runs/4481634969/jobs/7878603557))
jdk_jfr: [OK](https://github.com/zzambers/jdk-tester/actions/runs/4481322671/jobs/8053582402) (no regressions to [master](https://github.com/zzambers/jdk-tester/actions/runs/3997510473/jobs/6858945097))

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8305329](https://bugs.openjdk.org/browse/JDK-8305329) needs maintainer approval

### Issue
 * [JDK-8305329](https://bugs.openjdk.org/browse/JDK-8305329): [8u] Unify test libraries into single test library - step 1 (**Enhancement** - P4 - Approved)

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/294/head:pull/294` \
`$ git checkout pull/294`

Update a local copy of the PR: \
`$ git checkout pull/294` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/294/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 294`

View PR using the GUI difftool: \
`$ git pr show -t 294`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/294.diff">https://git.openjdk.org/jdk8u-dev/pull/294.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/294#issuecomment-1490978030)

### CODE REVIEW

**Comment by gnu-andrew** [comment]
This is something I'm aware of and I've thought about tackling it in a similar way to you a few times. Thanks for finding the time to do so which has eluded me so far.

I don't have any real issue with this PR, but then I guess this is the easy one. I'm a bit concerned about steps 2 & 3, because you seem to be suggesting that the existing HotSpot & JDK test libraries should be migrated to work with the ones from the JFR library. This seems like the wrong direction to me and a lot more work than migrating the JFR ones to work with the existing libraries (which is what the JFR backport should have done in the first place).

As you say yourself, some of the JFR imported library code doesn't even compile and it includes stuff for newer JDKs which isn't appropriate in 8u. This PR would seem like a good opportunity to remove rather than move any of these files that don't compile (which presumably also means they aren't being used by the JFR tests).

Have you verified that all the moved files actually compile? And if not, can we check that and delete any that don't?

Then, in the HotSpot stage, we can merge in the HotSpot library and replace any duplicates with the 8u versions, and see what (if anything) breaks in the JFR tests.

**Review by gnu-andrew — COMMENTED** [review]
Should have put my above comment under a review...

**Comment by gnu-andrew** [comment]
I think we should also probably have a step 4 to actually move the tests. That will then solve the backporting problem where tests keep being introduced in the wrong location.

**Comment by zzambers** [comment]
Hi @gnu-andrew,
thank you for your review,

> This is something I'm aware of and I've thought about tackling it in a similar way to you a few times. Thanks for finding the time to do so which has eluded me so far.
> 
> I don't have any real issue with this PR, but then I guess this is the easy one. I'm a bit concerned about steps 2 & 3, because you seem to be suggesting that the existing HotSpot & JDK test libraries should be migrated to work with the ones from the JFR library. This seems like the wrong direction to me and a lot more work than migrating the JFR ones to work with the existing libraries (which is what the JFR backport should have done in the first place).
> 
I haven't looked in too much detail, on how they should be merged, but probably on case by case basis. I think, in case of some more generic classes, rather than trying to merge `hs` and `jdk` versions (and fixing java package), it could make sense to just go with `jfr` version (if it looks ok for 8). I mean more generic classes like `Asserts.java`, `OutputAnalyzer.java`, maybe `Platform.java`. In other cases like broken/risky(low-level) stuff it would probably be better to go with `hs` (or `jdk`) version. (e.g. `whitebox` stuff)

> As you say yourself, some of the JFR imported library code doesn't even compile and it includes stuff for newer JDKs which isn't appropriate in 8u. This PR would seem like a good opportunity to remove rather than move any of these files that don't compile (which presumably also means they aren't being used by the JFR tests).
> 
> Have you verified that all the moved files actually compile? And if not, can we check that and delete any that don't?

I have not excluded any files, just moved all of them. However excluding broken stuff here is probably good idea. Keeping and trying to fix unused broken code, would probably be waste of time, as they can be re-added later, if needed by future backport. (I'll take a look at that)

> 
> Then, in the HotSpot stage, we can merge in the HotSpot library and replace any duplicates with the 8u versions, and see what (if anything) breaks in the JFR tests.

For hotspot-specific or low-level stuff it is probably safest approach. In case of more generic classes (which are also used by `jdk` tests), keeping `jfr` version may be easier and safer option.

Also we could use this opportunity to move whitebox classes to `jdk.test.lib` package (used by jdk 17+, see [JDK-8067223](https://bugs.openjdk.org/browse/JDK-8067223), probably can be backported to 11)

**Comment by zzambers** [comment]
> I think we should also probably have a step 4 to actually move the tests. That will then solve the backporting problem where tests keep being introduced in the wrong location.

Even though, it would be good for backporting, I have so far excluded tests themselfs from move, as there are some additional difficulties with that. While changing test library location can be done more or less transparently, in case of tests there are some complications:
- It would be more invasive change needing changes to build system (makefiles)
- It would break existing CI testing (would require changes), in cases, where jtreg is being called directly, rater than through main makefile, (e.g. Adoptium aqa-tests, see: [openjdk.mk](https://github.com/adoptium/aqa-tests/blob/07cac1895144ecb63a2ad03c3214a52fb108cfbc/openjdk/openjdk.mk#L122) [playlist.xml](https://github.com/adoptium/aqa-tests/blob/07cac1895144ecb63a2ad03c3214a52fb108cfbc/openjdk/playlist.xml#L717).)

**Comment by gnu-andrew** [comment]
> I have removed lib classes, which do not compile on jdk 8 (and ones depending on them). Retested -> OK.

This looks good. All seem to have been added by the JFR backport. While some are unique and only used by that (`LingeredApp.java`, `LingeredAppWithDeadlock.java`, `ModuleInfoMaker.java`), the rest seem to be duplicated by (presumably working) versions in the hotspot and jdk libraries.

~~~
$ find -name RedefineClassHelper.java
./hotspot/test/testlibrary/RedefineClassHelper.java
./jdk/test/lib/RedefineClassHelper.java

$ find -name CompilerUtils.java
./jdk/test/lib/jdk/test/lib/compiler/CompilerUtils.java
./jdk/test/lib/testlibrary/CompilerUtils.java

$ find -name InMemoryJavaCompiler.java
./hotspot/test/testlibrary/com/oracle/java/testlibrary/InMemoryJavaCompiler.java
./jdk/test/lib/jdk/test/lib/compiler/InMemoryJavaCompiler.java
./jdk/test/lib/testlibrary/jdk/testlibrary/InMemoryJavaCompiler.java

$ find -name JarUtils.java
./jdk/test/lib/jdk/test/lib/util/JarUtils.java
./jdk/test/lib/testlibrary/jdk/testlibrary/JarUtils.java

$ find -name SecurityTools.java
./jdk/test/lib/jdk/test/lib/SecurityTools.java
./jdk/test/lib/testlibrary/jdk/testlibrary/SecurityTools.java
~~~

**Comment by gnu-andrew** [comment]
> > I think we should also probably have a step 4 to actually move the tests. That will then solve the backporting problem where tests keep being introduced in the wrong location.
> 
> Even though, it would be good for backporting, I have so far excluded tests themselfs from move, as there are some additional difficulties with that. While changing test library location can be done more or less transparently, in case of tests there are some complications:
> 
>     * It would be more invasive change needing changes to build system (makefiles)
> 
>     * It would break existing CI testing (would require changes), in cases, where jtreg is being called directly, rater than through main makefile, (e.g. Adoptium aqa-tests, see: [openjdk.mk](https://github.com/adoptium/aqa-tests/blob/07cac1895144ecb63a2ad03c3214a52fb108cfbc/openjdk/openjdk.mk#L122) [playlist.xml](https://github.com/adoptium/aqa-tests/blob/07cac1895144ecb63a2ad03c3214a52fb108cfbc/openjdk/playlist.xml#L717).)

I know what you mean, and it is what has put me off doing this earlier. We can see how things look once the library work is done, but I think it would actually help remove a lot of special casing for 8u long term.

**Comment by zzambers** [comment]
Seems like this PR will need to get updated (rebased), due to changes introduced by:
https://github.com/openjdk/jdk8u-dev/pull/347

**Comment by zzambers** [comment]
I have rebased changes on current master to fix conflict as shown by GH. (Bot does not like rebasing, but I find it less evil and more readable, than merging in master.)

Rebase using `git rebase master` worked out of box, no manual interaction was needed. I verified that renamed [NetworkConfiguration.java](https://github.com/zzambers/jdk8u-dev/blob/jtreg-lib/test/lib/jdk/test/lib/NetworkConfiguration.java) contains changes by [JDK-8207404 backport](https://github.com/openjdk/jdk8u-dev/pull/347). There is only small change on top fixing `@library` tag in affected tests. I have found no other issues.

**Review by gnu-andrew — APPROVED** [review]
Yes, I agree a rebase makes sense here. The bot comment makes sense to encourage people to respond to review comments with further commits, but not really with merges. Worst of all is with dependent pull requests, where merging the two identical change requests would be more dangerous than just rebasing and having `git` just recognise and drop the duplicate. Of course, that duplicate is only created because the bot itself does a rebase...

The additional changes look fine to me. Let's get this in.

**Comment by zzambers** [comment]
/approval starts process of unifying test libraries and moving them to same place as in newer jdks, it only affects tests, GH testing OK

**Comment by zzambers** [comment]
/approval request  starts process of unifying test libraries and moving them to same place as in newer jdks, it only affects tests, GH testing OK

**Comment by zzambers** [comment]
@gnu-andrew thank you

/integrate

**Pull request closed without merging**
