### PR TITLE
8274840: Update OS detection code to recognize Windows 11

### PR DESCRIPTION
**Pull request by rgithubli**
This pull request contains a backport of commit https://github.com/openjdk/jdk/commit/97ea9dd2f24f9f1fb9b9345a4202a825ee28e014

The original author is Matthias Baesken and co-authored by Arno Zeller. It was reviewed by clanger, dholmes.

The backport was clean after updating filepath.

Verified on win11: when doing `java -XshowSettings:properties -version`, can see `os.name = Windows 11`

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8274840](https://bugs.openjdk.org/browse/JDK-8274840): Update OS detection code to recognize Windows 11

### Reviewers
 * @eastig (no known github.com user name / role)
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/93/head:pull/93` \
`$ git checkout pull/93`

Update a local copy of the PR: \
`$ git checkout pull/93` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/93/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 93`

View PR using the GUI difftool: \
`$ git pr show -t 93`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/93.diff">https://git.openjdk.org/jdk8u-dev/pull/93.diff</a>

</details>

### CODE REVIEW

**Review by eastig — APPROVED** [review]
Confirm it is clean.

**Review by phohensee — APPROVED** [review]
/clean

Lgtm.

**Comment by jerboaa** [comment]
@rgithubli I think we need to do the `/integrate` and `/sponsor` handshake again. It wasn't labelled `ready` when you initially issued `/integrate`...

**Pull request closed without merging**
