### PR TITLE
8011180: Delete obsolete scripts

### PR DESCRIPTION
**Pull request by zzambers**
This backport removes some obsolete scripts.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8011180](https://bugs.openjdk.org/browse/JDK-8011180) needs maintainer approval

### Issue
 * [JDK-8011180](https://bugs.openjdk.org/browse/JDK-8011180): Delete obsolete scripts (**Bug** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/438/head:pull/438` \
`$ git checkout pull/438`

Update a local copy of the PR: \
`$ git checkout pull/438` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/438/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 438`

View PR using the GUI difftool: \
`$ git pr show -t 438`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/438.diff">https://git.openjdk.org/jdk8u-dev/pull/438.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/438#issuecomment-1934197558)

### CODE REVIEW

**Comment by zzambers** [comment]
/approval request Just removes obsolete scripts, which are not used anymore

**Comment by theRealAph** [comment]
No: this isn't a critical bug fix.

**Comment by zzambers** [comment]
@gnu-andrew thanks
/integrate

**Pull request closed without merging**
