### PR TITLE
8323202: [8u] Remove get_source.sh and hgforest.sh

### PR DESCRIPTION
**Pull request by zzambers**
Remove get_source.sh and hgforest.sh scripts. These scripts were used with mercurial forest and are no longer useful after switching to git.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8323202](https://bugs.openjdk.org/browse/JDK-8323202) needs maintainer approval

### Issue
 * [JDK-8323202](https://bugs.openjdk.org/browse/JDK-8323202): [8u] Remove get_source.sh and hgforest.sh (**Enhancement** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [56cba689](https://git.openjdk.org/jdk8u-dev/pull/417/files/56cba6893e3455870edb53b05ce0a5b3d7ee5087)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/417/head:pull/417` \
`$ git checkout pull/417`

Update a local copy of the PR: \
`$ git checkout pull/417` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/417/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 417`

View PR using the GUI difftool: \
`$ git pr show -t 417`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/417.diff">https://git.openjdk.org/jdk8u-dev/pull/417.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/417#issuecomment-1881586660)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by mrserb** [comment]
You probably need to backport this one first https://hg.openjdk.org/jdk9/jdk9/rev/ea7a041eb994

**Comment by gnu-andrew** [comment]
> You probably need to backport this one first https://hg.openjdk.org/jdk9/jdk9/rev/ea7a041eb994

Yes, I think we can use this bug ID and just include get_source.sh as well (removed by 8187443: "Forest Consolidation: Move files to unified layout" which we're obviously not going to backport). Certainly, webrev.ksh should be removed as part of this as well.

**Comment by gnu-andrew** [comment]
> > You probably need to backport this one first https://hg.openjdk.org/jdk9/jdk9/rev/ea7a041eb994
> 
> Yes, I think we can use this bug ID and just include get_source.sh as well (removed by 8187443: "Forest Consolidation: Move files to unified layout" which we're obviously not going to backport). Certainly, `webrev.ksh` should be removed as part of this as well, along with the duplicate `hgforest.sh`.

**Comment by zzambers** [comment]
@mrserb @gnu-andrew sorry, originally I just wanted to remove `get_source.sh` (part of forest consolidation), than found that other script, but missed, that it had a separate bug. :/ Should I close this PR and create new one or just modify this one and add issue using `/issue`?

**Comment by gnu-andrew** [comment]
> @mrserb @gnu-andrew sorry, originally I just wanted to remove `get_source.sh` (part of forest consolidation), than found that other script, but missed, that it had a separate bug. :/ Should I close this PR and create new one or just modify this one and add issue using `/issue`?

I would do a separate PR for a backport of 8011180, and then come back to this one as `get_source.sh` and the other `hgforest.sh` will still need to be removed.

~~~
$ find -name 'hgforest.sh'
./common/bin/hgforest.sh
./make/scripts/hgforest.sh
~~~

The other bug only removes the one in `make/scripts` so this could remove the one in `common/bin`.

**Comment by zzambers** [comment]
Oh, one more `hgforest.sh` :)

I have created [PR](https://github.com/openjdk/jdk8u-dev/pull/438) for JDK-8011180 backport.
After that one I'll update name and chegeset of this one to remove remaining files.

**Comment by zzambers** [comment]
I have updated this PR to do rest of cleanup after JDK-8011180. (Those removed in newer JDKs by [JDK-8187443]( https://bugs.openjdk.org/browse/JDK-8187443).)

I have realized, that I can keep issue/PR name as the only difference to original changeset happens to be, that it removes the other `hgforest.sh`. :)

**Review by gnu-andrew — APPROVED** [review]
Looks good to me. Thanks for doing the other backport.

**Comment by zzambers** [comment]
/approval request Remove leftover scripts (used with mercurial forest, no longer useful/working with git). In newer JDKs they were removed by JDK-8187443 (Forest Consolidation: Move files to unified layout).

**Pull request closed without merging**
