### PR TITLE
8317373: Add Telia Root CA v2

### PR DESCRIPTION
**Pull request by jerboaa**
Backport of a mandatory cacert root addition. JDK 11u patch applies clean modulo path changes. Please review.

Testing:
- [x] GHA
- [x] `jdk/test/sun/security/lib/cacerts` and `jdk/test/security/infra/java/security/cert/CertPathValidator` jtreg tests (including the new one). All pass.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8317373](https://bugs.openjdk.org/browse/JDK-8317373) needs maintainer approval

### Issue
 * [JDK-8317373](https://bugs.openjdk.org/browse/JDK-8317373): Add Telia Root CA v2 (**Enhancement** - P2 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [243ad718](https://git.openjdk.org/jdk8u-dev/pull/397/files/243ad7185c52c674422cc462529ccb8cc8c3b961)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/397/head:pull/397` \
`$ git checkout pull/397`

Update a local copy of the PR: \
`$ git checkout pull/397` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/397/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 397`

View PR using the GUI difftool: \
`$ git pr show -t 397`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/397.diff">https://git.openjdk.org/jdk8u-dev/pull/397.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/397#issuecomment-1830234925)

### CODE REVIEW

**Comment by jerboaa** [comment]
The windows x64 build failure looks suspicous. It doesn't fail in #390 which this PR is based on and doesn't really change anything related to the build failure.

**Review by phohensee — APPROVED** [review]

**Comment by phohensee** [comment]
windows-x64 failure appears to be an infrastructure issue.

**Comment by jerboaa** [comment]
With the latest merge #368 is part of it, so GHA should run the tests as well.

**Comment by jerboaa** [comment]
Test failures seem infra related. All pass in #398

**Comment by gnu-andrew** [comment]
Let's try again.
/approve yes

**Pull request closed without merging**
