### PR TITLE
8202142: jfr/event/io/TestInstrumentation is unstable

### PR DESCRIPTION
**Pull request by dongbohe**
Hi,

This PR has been reviewed by Paul before move to github: https://mail.openjdk.java.net/pipermail/jdk8u-dev/2022-January/014489.html

Thanks,
hedongbo

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issue
 * [JDK-8202142](https://bugs.openjdk.java.net/browse/JDK-8202142): jfr/event/io/TestInstrumentation is unstable

### Reviewers
 * [Paul Hohensee](https://openjdk.java.net/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [7fbbc697](https://git.openjdk.java.net/jdk8u-dev/pull/10/files/7fbbc6976a47aa0b3206d5aa9772afba1711e803)
 * [Zhengyu Gu](https://openjdk.java.net/census#zgu) (@zhengyu123 - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk8u-dev pull/10/head:pull/10` \
`$ git checkout pull/10`

Update a local copy of the PR: \
`$ git checkout pull/10` \
`$ git pull https://git.openjdk.java.net/jdk8u-dev pull/10/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 10`

View PR using the GUI difftool: \
`$ git pr show -t 10`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk8u-dev/pull/10.diff">https://git.openjdk.java.net/jdk8u-dev/pull/10.diff</a>

</details>

### CODE REVIEW

**Comment by zhengyu123** [comment]
I think should backport [8223396](https://bugs.openjdk.java.net/browse/JDK-8223396) first to eliminate another out-of-order backport.

**Comment by dongbohe** [comment]
> I think should backport [8223396](https://bugs.openjdk.java.net/browse/JDK-8223396) first to eliminate another out-of-order backport.

Hi, Zhengyu. I have created #14 to backport 8223396.

**Comment by dongbohe** [comment]
> I think should backport [8223396](https://bugs.openjdk.java.net/browse/JDK-8223396) first to eliminate another out-of-order backport.

Hi, Zhengyu

[8223396](https://bugs.openjdk.java.net/browse/JDK-8223396) has been merged into 8u in #14, can you help me look at this again?

**Comment by dongbohe** [comment]
@zhengyu123 Could you please take another look?

**Comment by phohensee** [comment]
/sponsor

Got the approval.

**Comment by phohensee** [comment]
@dongbohe, please add a /integrate comment so I can sponsor.

**Comment by zhengyu123** [comment]
> @zhengyu123 Could you please take another look?

Sorry, I did not get notification somehow. LGTM

**Review by zhengyu123 — APPROVED** [review]
LGTM

**Pull request closed without merging**
