### PR TITLE
8324185: [8u] Accept Xcode 12+ builds on macOS

### PR DESCRIPTION
**Pull request by mrserb**
I would like to update the build logic for macOS so it will accept the XCode 14 and 15. It could be done in a few ways:

 - Add XCode 13, 14 and 15 to the list of supported versions, like [this](https://github.com/openjdk/jdk8u-dev/pull/422/commits/d2d157ff4dd04cb108e036282643b21ac132016c)
 - Accept all XCode 9+ versions, like [this](https://github.com/openjdk/jdk8u-dev/pull/422/commits/d1d5e2d214135084e50bc5aba839afab98cf2de7).
 - Delete the "fail fast" code path. So if the xcode and command-line tools are there then build it, like [this](https://github.com/openjdk/jdk8u-dev/pull/422/commits/d28f6cdbc2bd6cb6bfefc84837a6c7c76c287572). 

I think we can safely delete this check, so this PR implements it.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8324185](https://bugs.openjdk.org/browse/JDK-8324185) needs maintainer approval

### Issue
 * [JDK-8324185](https://bugs.openjdk.org/browse/JDK-8324185): [8u] Accept Xcode 12+ builds on macOS (**Bug** - P3 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/422/head:pull/422` \
`$ git checkout pull/422`

Update a local copy of the PR: \
`$ git checkout pull/422` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/422/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 422`

View PR using the GUI difftool: \
`$ git pr show -t 422`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/422.diff">https://git.openjdk.org/jdk8u-dev/pull/422.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/422#issuecomment-1899633791)

### CODE REVIEW

**Comment by phohensee** [comment]
I'd go with the second alternative so as keep the error message.

**Comment by benty-amzn** [comment]
Option 3 is closest to what newer versions do. It's quite difficult at this point to get a system with XCode 9 up and running, much less 6, so the error message is likely to never be relevant. I think either option 2 or 3 is fine.

**Review by phohensee — APPROVED** [review]
Let's go with option 3 if that's what's closest to current practice.

**Review by gnu-andrew — APPROVED** [review]
I agree removal is appropriate here. These kind of version tests serve no real purpose in the first place. If one is trying to get the JDK to build with a new XCode version, this check is just a blocker that has to be removed to get to the real issues and actually have something to work with to add support.  If the aim is to avoid a specific bug, or check for a specific feature, then the check should be for the bug or feature (see what we do with flags for GCC)

The thing I was most curious about with this PR was why it wasn't a backport from later versions. It seems that [JDK-8043340](https://bugs.openjdk.org/browse/JDK-8043340) was implemented differently in 8u and 9. In [the 9 version](https://hg.openjdk.org/jdk9/jdk9/rev/26ba036c46fc) this check is not added. It is unique to [the 8 version](https://github.com/openjdk/jdk8u/commit/d85158eee8a044501fd316ffe709e2483ab578e8), restricting it to XCode 4. @benty-amzn's later change just extended it to more versions.

**Pull request closed without merging**
