### PR TITLE
8297141: Fix hotspot/test/runtime/SharedArchiveFile/DefaultUseWithClient.java for 8u

### PR DESCRIPTION
**Pull request by zzambers**
Following test (from hotspot/tier1) currently fails on Windows x86:
`hotspot/test/runtime/SharedArchiveFile/DefaultUseWithClient.java`

**Test output:**
```
...
 stdout: [];
 stderr: [openjdk version "1.8.0_362-internal"
OpenJDK Runtime Environment (build 1.8.0_362-internal-zzambers-54a485c13e59fa68ea9dc088f320520eedbe33fe-b00)
OpenJDK Server VM (build 25.362-b00, mixed mode)
]
 exitValue = 0

java.lang.RuntimeException: 'UseSharedSpaces:' missing from stdout/stderr 

	at com.oracle.java.testlibrary.OutputAnalyzer.shouldContain(OutputAnalyzer.java:134)
	at DefaultUseWithClient.main(DefaultUseWithClient.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:750)
...
```

**Problem:**
Test is Windows 32-bit only, only applies to Client VM and checks default behaviour of shared archive feature. Problem is, that default build of 32-bit windows JDK does not include Client VM, so Server VM is used (so -client arg does nothing). With Server VM tests fails. I tried to make build which has Client VM and then this test passes (It breaks other tests which expect default to be Server VM though).

**Fix:**
Test runs java with `-version` argument, which can print something similar to:
```
openjdk version "1.8.0_362-internal"
OpenJDK Runtime Environment (build 1.8.0_362-internal-zzambers-2bbffac3199782df1f9b81867fdfeb3d72889fcd-b00)
OpenJDK Client VM (build 25.362-b00, mixed mode)
```
This output can be used to check if Client VM and skip other checks, if Client VM is not used. Fix is JDK 8 only as test has been removed on newer JDKs by JDK-8154204 by [2]. But I decided to fix it for JDK 8.

**Testing:**
With this change test passes on Windows 32-bit. (both with Server [3] and Client [4] Vms)

[1] https://github.com/zzambers/jdk8u-dev/actions/runs/3438556844
[2] https://bugs.openjdk.org/browse/JDK-8154204
[3] https://github.com/zzambers/jdk8u-dev/actions/runs/3462926725
[4] https://github.com/zzambers/jdk8u-dev/actions/runs/3462887672

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8297141](https://bugs.openjdk.org/browse/JDK-8297141): Fix hotspot/test/runtime/SharedArchiveFile/DefaultUseWithClient.java for 8u

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/181/head:pull/181` \
`$ git checkout pull/181`

Update a local copy of the PR: \
`$ git checkout pull/181` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/181/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 181`

View PR using the GUI difftool: \
`$ git pr show -t 181`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/181.diff">https://git.openjdk.org/jdk8u-dev/pull/181.diff</a>

</details>

### CODE REVIEW

**Review by jerboaa — COMMENTED** [review]
Shouldn't we just amend the condition on lines 41-45 to something like:

```
boolean is32BitWindowsClientVm = (Platform.isWindows() && Platform.is32bit() && Platform.isClient());
if (!is32BitWindowsClientVm) {
    System.out.println("Test only applicable on 32-bit Windows Client VM. Skipping");
    return;
}
```

**Comment by zzambers** [comment]
@jerboaa Oh, that is indeed cleaner. I have not checked Platform class and I did not know it is capable of that. I'll update my PR. Thanks

**Comment by zzambers** [comment]
Even though, I should test that VM launched with "-client" uses Client VM (maybe case where it has Client VM but it is not default). I would then probably need to run test in othervm and with -client arg as well.

**Comment by zzambers** [comment]
Updated detection code. Tested on both default build [5] (without Client VM) and build with Client VM [6] with windows-x86 testing enabled. Passed both.

[5] https://github.com/zzambers/jdk8u-dev/actions/runs/3482764139
[6] https://github.com/zzambers/jdk8u-dev/actions/runs/3483679375

**Review by jerboaa — APPROVED** [review]
Looks fine to me.

**Comment by zzambers** [comment]
@jerboaa Thanks for the review

(but still needs jdk8u-fix-yes)

**Pull request closed without merging**
