### PR TITLE
8176509: Use pandoc for converting build readme to html

### PR DESCRIPTION
**Pull request by zzambers**
This backport switches to pandoc for coversion of building readme to html. It also does some style/formating changes/fixes to building readme, which is moved to new location and also removes redundant information in other Readme files.

Backport is not clear. Code for coversion to html had to be modified to work with JDK8 build system. Change set (patch) for building readme mostly applied automatically, but some parts had to be done by hand due to few differences.

Unlike in original change set, this backport moves `README-builds.{md,html}` files directly to `doc/building.{md,html}` and not to intermediate location `common/doc/building.{md,html}`. (additional move was done in jdk10 as part of [JDK-8187443](https://bugs.openjdk.org/browse/JDK-8187443))

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8176509](https://bugs.openjdk.org/browse/JDK-8176509) needs maintainer approval

### Issue
 * [JDK-8176509](https://bugs.openjdk.org/browse/JDK-8176509): Use pandoc for converting build readme to html (**Bug** - P3 - Approved)

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/370/head:pull/370` \
`$ git checkout pull/370`

Update a local copy of the PR: \
`$ git checkout pull/370` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/370/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 370`

View PR using the GUI difftool: \
`$ git pr show -t 370`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/370.diff">https://git.openjdk.org/jdk8u-dev/pull/370.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/370#issuecomment-1710716887)

### CODE REVIEW

**Review by gnu-andrew — APPROVED** [review]
Looks good to me. 8u build requirements seem to have been retained as is and I think moving the file to the final place here is the right thing to do.

**Comment by zzambers** [comment]
/approval request Backport switches to pandoc for builds readme html generation (+ does some docs fixes), GHA tests ok

**Comment by zzambers** [comment]
> Looks good to me. 8u build requirements seem to have been retained as is and I think moving the file to the final place here is the right thing to do.

Yy, pandoc should be optional, it builds without it in GHA.

Unfortunately there is little additional noise in generated-configure concerning `--runstatedir` option, even though, I have used same version of autofonf, as was used before (2.69). It boils down to whether autoconf is ran on distro which has [specific backport](https://bugzilla.redhat.com/show_bug.cgi?id=1831941#c6). (Not present on rhel-8 I used) But I don't think this affects OpenJDK in any way.

**Comment by gnu-andrew** [comment]
> > Looks good to me. 8u build requirements seem to have been retained as is and I think moving the file to the final place here is the right thing to do.
> 
> Yy, pandoc should be optional, it builds without it in GHA.
> 
> Unfortunately there is little additional noise in `generated-configure.sh`'s diff concerning `--runstatedir` option, even though, I have used same version of autofonf, as was used before (2.69). It boils down to whether autoconf is ran on distro which has [specific backport](https://bugzilla.redhat.com/show_bug.cgi?id=1831941#c6). (Not present on rhel-8 I used) But I don't think this affects OpenJDK in any way.

No, it shouldn't and one can always regenerate configure if it is an issue. I'm in two minds about whether it is finally time to backport [JDK-8195689](https://bugs.openjdk.org/browse/JDK-8195689) to 8u and get rid of this once and for all. It is the only JDK to have this baggage (it is removed in 11u and up) and I think it causes more problems than it solves, but then I've never been a fan of bundling generated files to begin with.

**Comment by zzambers** [comment]
@gnu-andrew thanks
/integrate

**Pull request closed without merging**
