### PR TITLE
8291638: Keep-Alive timeout of 0 should close connection immediately

### PR DESCRIPTION
**Pull request by dhanalla**
Backport of 26ac8366360685ef0cf3447ee7db16ba7a7fa1ec

A clean backport from JDK11u patch, excluding one version-specific API, "!OptionalInt::isPresent() vs OptionalInt::isEmpty()".

Test performed:
1. JTreg jdk_tier1, hotspot_tier1
2. The backported test case in this PR passed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8291638](https://bugs.openjdk.org/browse/JDK-8291638) needs maintainer approval

### Issue
 * [JDK-8291638](https://bugs.openjdk.org/browse/JDK-8291638): Keep-Alive timeout of 0 should close connection immediately (**Bug** - P3 - Approved)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/454/head:pull/454` \
`$ git checkout pull/454`

Update a local copy of the PR: \
`$ git checkout pull/454` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/454/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 454`

View PR using the GUI difftool: \
`$ git pr show -t 454`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/454.diff">https://git.openjdk.org/jdk8u-dev/pull/454.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/454#issuecomment-1958218308)

### CODE REVIEW

**Review by gnu-andrew — COMMENTED** [review]
It looks like this PR is also trying to bring in [JDK-8291637](https://bugs.openjdk.org/browse/JDK-8291637) without its associated test case.

I would suggest opening a separate PR for that backport and making this one dependent on it instead. This change should then be close to clean.

**Comment by dhanalla** [comment]
> It looks like this PR is also trying to bring in [JDK-8291637](https://bugs.openjdk.org/browse/JDK-8291637) without its associated test case.
> 
> I would suggest opening a separate PR for that backport and making this one dependent on it instead. This change should then be close to clean.

Thanks @gnu-andrew  for reviewing this PR.
I created backport https://github.com/openjdk/jdk8u-dev/pull/466 and made #453 dependent on the new PR #466 in accordance with the backport order in JDK11U.

**Review by jerboaa — APPROVED** [review]
Looks good.

**Comment by dhanalla** [comment]
> Looks good.

Thanks @jerboaa for reviewing this PR. I've added a JDK8 patch request to the bug as the next step.

**Pull request closed without merging**
