### PR TITLE
8318951: Additional negative value check in JPEG decoding

### PR DESCRIPTION
**Pull request by mrserb**
Hi all,

This pull request contains a backport of commit [75ce02fe](https://github.com/openjdk/jdk/commit/75ce02fe74e1232bfa8d72b4fdad82ed938ef957) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Jayathirth D V on 31 Oct 2023 and was reviewed by Alexander Zvegintsev and Phil Race.

Thanks!

---------
### Progress
- [x] [JDK-8318951](https://bugs.openjdk.org/browse/JDK-8318951) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8318951](https://bugs.openjdk.org/browse/JDK-8318951): Additional negative value check in JPEG decoding (**Bug** - P3 - Approved)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/510/head:pull/510` \
`$ git checkout pull/510`

Update a local copy of the PR: \
`$ git checkout pull/510` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/510/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 510`

View PR using the GUI difftool: \
`$ git pr show -t 510`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/510.diff">https://git.openjdk.org/jdk8u-dev/pull/510.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/510#issuecomment-2155977681)

### CODE REVIEW

**Comment by mrserb** [comment]
/clean the change is identical to the fix in openjdk/jdk

**Comment by mrserb** [comment]
keep open

**Comment by mrserb** [comment]
keep open

**Review by jerboaa — APPROVED** [review]
OK.

**Pull request closed without merging**
