### PR TITLE
8201793: (ref) Reference object should not support cloning

### PR DESCRIPTION
**Pull request by poonamparhar**
This is a clean backport of JDK-8201793 from jdk8u-ri to jdk8u-dev.

With this change, java.lang.ref.Reference::clone method always throws CloneNotSupportedException.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8201793](https://bugs.openjdk.org/browse/JDK-8201793): (ref) Reference object should not support cloning

### Reviewers
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**) ⚠️ Review applies to [a0e6a0fd](https://git.openjdk.org/jdk8u-dev/pull/102/files/a0e6a0fdf1c3fdc524951d0908ac54a68d2c1a8b)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - Author) ⚠️ Review applies to [a0e6a0fd](https://git.openjdk.org/jdk8u-dev/pull/102/files/a0e6a0fdf1c3fdc524951d0908ac54a68d2c1a8b)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**) ⚠️ Review applies to [a0e6a0fd](https://git.openjdk.org/jdk8u-dev/pull/102/files/a0e6a0fdf1c3fdc524951d0908ac54a68d2c1a8b)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/102/head:pull/102` \
`$ git checkout pull/102`

Update a local copy of the PR: \
`$ git checkout pull/102` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/102/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 102`

View PR using the GUI difftool: \
`$ git pr show -t 102`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/102.diff">https://git.openjdk.org/jdk8u-dev/pull/102.diff</a>

</details>

### CODE REVIEW

**Review by mlchung — APPROVED** [review]
Looks good.

**Review by irisclark — APPROVED** [review]
Spec changes match those in JSR 337 MR 4.

**Review by gnu-andrew — APPROVED** [review]
Looks good. Approved.

**Comment by poonamparhar** [comment]
\integrate

**Pull request closed without merging**
