### PR TITLE
8231111: Cgroups v2: Rework Metrics in java.base so as to recognize unified hierarchy

### PR DESCRIPTION
**Pull request by jmtd**
This is a backport of [4def210a22faaec6b47912dd314e6365ea48d28f](https://github.com/openjdk/jdk/commit/4def210a22faaec6b47912dd314e6365ea48d28f) for jdk8u-dev as part of an effort to backport cgroups v2 support.

It does not apply clean. Paths need unshuffling. A number of changes were needed for 8u support. I've structured the PR as separate commits, with each change made in a separate commit for (hopefully) ease of review.

Not all the new tests pass:     TestDockerMemoryMetrics  failing one, specifically:

    Exception in thread "main" java.lang.RuntimeException: Memory and swap limit not equal, expected : [209715200, 1073741824], got : [209715200, 864026624]

I think this is fixed in a further patch to backport, and will confirm.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8231111](https://bugs.openjdk.org/browse/JDK-8231111): Cgroups v2: Rework Metrics in java.base so as to recognize unified hierarchy
 * [JDK-8275713](https://bugs.openjdk.org/browse/JDK-8275713): TestDockerMemoryMetrics test fails on recent runc
 * [JDK-8228585](https://bugs.openjdk.org/browse/JDK-8228585): jdk/internal/platform/cgroup/TestCgroupMetrics.java - NumberFormatException because of large long values (memory limit_in_bytes)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/121/head:pull/121` \
`$ git checkout pull/121`

Update a local copy of the PR: \
`$ git checkout pull/121` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/121/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 121`

View PR using the GUI difftool: \
`$ git pr show -t 121`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/121.diff">https://git.openjdk.org/jdk8u-dev/pull/121.diff</a>

</details>

### CODE REVIEW

**Comment by jmtd** [comment]
I'm probably going to rebase this on #123 (8206456). I had conflicts in this backport due to that missing in 8u that I just resolved in this PR, but I've hit further conflicts in the next patch in series, so now addressing 8206456 properly (in #123).

**Comment by jmtd** [comment]
> I'm probably going to rebase this on https://github.com/openjdk/jdk8u-dev/pull/123 (8206456).

Not necessary. Sorry for the noise!

**Comment by jmtd** [comment]
I have ended up (artificially) making this PR depend upon pr/123, so that another PR, https://github.com/openjdk/jdk8u-dev/pull/124, can depend upon this one and get both - it depends upon both.

**Comment by jerboaa** [comment]
@jmtd Please rebase this onto latest master. Right now it looks like changes from #127 are included here, which shouldn't be?

**Comment by jmtd** [comment]
> @jmtd Please rebase this onto latest master. Right now it looks like changes from https://github.com/openjdk/jdk8u-dev/pull/127 are included here, which shouldn't be?

Done.

**Review by jerboaa — APPROVED** [review]

**Review by gnu-andrew — APPROVED** [review]
This looks ok, though again I don't see why two additional changes have been mixed in with this backport, when they could have been in follow-ups.  Thanks to @jerboaa for catching that they were in there.

Approved for 8u.

**Pull request closed without merging**
