### PR TITLE
8287663: Add a regression test for JDK-8287073

### PR DESCRIPTION
**Pull request by jerboaa**
Simple low risk backport for a regression check of https://bugs.openjdk.org/browse/JDK-8287073 (forthcoming). The only changes were (other than context changes due to `optResult.equals(Optional.empty()` vs `optResult.isEmpty()` differences):

- Bug line in test. Fixed manually
- `Files.writeString()` => `Files.write()` changes in test.

Testing:
 - [x] New regression test fails without the product fix of JDK-8287073, passes with it.
 - [x] Linux container tests on x86_64 and cg1

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287663](https://bugs.openjdk.org/browse/JDK-8287663): Add a regression test for JDK-8287073 (**Bug** - P3)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [63a56c99](https://git.openjdk.org/jdk8u-dev/pull/323/files/63a56c9905f45ca530c5141649d79d9d53593550)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/323/head:pull/323` \
`$ git checkout pull/323`

Update a local copy of the PR: \
`$ git checkout pull/323` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/323/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 323`

View PR using the GUI difftool: \
`$ git pr show -t 323`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/323.diff">https://git.openjdk.org/jdk8u-dev/pull/323.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/323#issuecomment-1564510608)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by jerboaa** [comment]
Thanks for the review, @phohensee!

**Comment by jerboaa** [comment]
x86 tier1 one GHA failure seems unrelated to this patch.

**Comment by jerboaa** [comment]
Please keep open.

**Review by gnu-andrew — COMMENTED** [review]
The `@bug` line difference seems to have occurred because JDK-8293540 was backported before JDK-8287107 and JDK-8287073 in 8u.

Can we use this opportunity to get the bug line into numerical order, so any later patches apply cleanly? i.e. `@bug 8287107 8287073 8293540` as in https://github.com/openjdk/jdk/commit/6d83482a6b5f1898514fd450d8143dbfef57e362 ? Thanks.

We should probably be removing the `@modules` line in 8u, but I'm happy to let that stay if it makes backports easier.

**Comment by jerboaa** [comment]
> Can we use this opportunity to get the bug line into numerical order, so any later patches apply cleanly? i.e. `@bug 8287107 8287073 8293540` as in [openjdk/jdk@6d83482](https://github.com/openjdk/jdk/commit/6d83482a6b5f1898514fd450d8143dbfef57e362) ? Thanks.

Fixed. More thoughts?

**Review by gnu-andrew — APPROVED** [review]
No, that was the only issue I could see. Approved for 8u.

**Pull request closed without merging**
