### PR TITLE
8278794: Infinite loop in DeflaterOutputStream.finish()

### PR DESCRIPTION
**Pull request by yan-too**
This is a second fix after "8193682: Infinite loop in ZipOutputStream.close()".  Again, clean after 8193682 in code part, using jdk11 form as a prototype. The test added in the original fix had an issue  fixed later in 8284771. Test is included in that fixed form. The issue 8284771 will be added to the commit message.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8284771](https://bugs.openjdk.org/browse/JDK-8284771) needs maintainer approval
- [x] [JDK-8278794](https://bugs.openjdk.org/browse/JDK-8278794) needs maintainer approval

### Issues
 * [JDK-8278794](https://bugs.openjdk.org/browse/JDK-8278794): Infinite loop in DeflaterOutputStream.finish() (**Bug** - P4 - Approved)
 * [JDK-8284771](https://bugs.openjdk.org/browse/JDK-8284771): java/util/zip/CloseInflaterDeflaterTest.java failed with "AssertionError: Expected IOException to be thrown, but nothing was thrown" (**Bug** - P2 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/565/head:pull/565` \
`$ git checkout pull/565`

Update a local copy of the PR: \
`$ git checkout pull/565` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/565/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 565`

View PR using the GUI difftool: \
`$ git pr show -t 565`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/565.diff">https://git.openjdk.org/jdk8u-dev/pull/565.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/565#issuecomment-2301873758)

### CODE REVIEW

**Comment by yan-too** [comment]
Tests failures are unrelated: on macOS/hotspot it is again https://github.com/openjdk/jdk8u-dev/pull/544 it seems, and everything else is a certificate validation issue.

**Comment by yan-too** [comment]
Tests failures are unrelated: on macOS/hotspot it is again https://github.com/openjdk/jdk8u-dev/pull/544 it seems, and everything else is a certificate validation issue.

**Review by phohensee — APPROVED** [review]

**Comment by yan-too** [comment]
/approval request I'm backporting this as a follow-up to 8193682. The backport was already done in Oracle jdk8 and all update releases before jdk18. Risk seems low. The fix to 8278794 substituted a new regtest which itself had to be fixed soon after in 8284771. The test is included in this updated form and 8284771 is added as a second issue to this commit.

**Comment by jerboaa** [comment]
> Tests failures are unrelated: on macOS/hotspot it is again #544 it seems, and everything else is a certificate validation issue.

Agreed.

/approve yes

**Review by jerboaa — APPROVED** [review]

**Pull request closed without merging**
