### PR TITLE
8139668: Generate README-build.html from markdown

### PR DESCRIPTION
**Pull request by gnu-andrew**
This updates the build documentation so it `README-builds.html` is generated from `README-builds,md`

This is a precursor to [JDK-8176509](https://bugs.openjdk.org/browse/JDK-8176509) which also updates the `README`, simplifying #75 

There are deliberately no content changes here. In fact, JDK 9 changes to the documentation prior to this change are reverted (VS2010->VS2013 bump and other build requirement changes (namely [JDK-8041593](https://bugs.openjdk.org/browse/JDK-8041593) (JDK9 update), [JDK-8062223](https://bugs.openjdk.org/browse/JDK-8062223) (ccache update), [JDK-8076531](https://bugs.openjdk.org/browse/JDK-8076531) (Windows default compiler change) and [JDK-8072023](https://bugs.openjdk.org/browse/JDK-8072023) (make version change)). We can make our own updates once these changes are in.

The updated `README-builds.html` was generated from the new `README-builds.md`. I fixed a bug in `common/bin/update-build-readme.sh` which checks the variable `MARKDOWN` for the location of the processor but then uses a bare `markdown` in the actual invocation.  This script is removed in JDK-8176509 anyway, being replaced with `pandoc`.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8139668](https://bugs.openjdk.org/browse/JDK-8139668): Generate README-build.html from markdown

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/79/head:pull/79` \
`$ git checkout pull/79`

Update a local copy of the PR: \
`$ git checkout pull/79` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/79/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 79`

View PR using the GUI difftool: \
`$ git pr show -t 79`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/79.diff">https://git.openjdk.org/jdk8u-dev/pull/79.diff</a>

</details>

### CODE REVIEW

**Comment by mrserb** [comment]
Probably we should move this document to the new doc folder? Do we have a plans to align Readme/BuildDoc to the jdk/jdk version, simple readme with a few links and other docs in "doc" folder?: https://github.com/openjdk/jdk

**Comment by gdams** [comment]
> Probably we should move this document to the new doc folder? Do we have a plans to align Readme/BuildDoc to the jdk/jdk version, simple readme with a few links and other docs in "doc" folder?: https://github.com/openjdk/jdk

It's unclear when the move to the `doc` folder happened, reading a few issues it looks like it happened as part of the consilidation into a mono repo. It possibly should have happened when the JDK8u repo was converted into a mono repo. @gnu-andrew I feel this backport is likely the best place to create the `docs` directory.

**Comment by gnu-andrew** [comment]
I can look at when the `doc` directory was added, but, if we add this to 8u, it should be a separate change, rather than part of this backport. I would prefer backports are as close to the original issue as possible, plus there's a follow-on fix I plan to backport that also happens before the directory is added.

I'll come back to this once the July security update is out. That's taking up all my time right now.

**Comment by gdams** [comment]
@gnu-andrew once you've got this good to merge I'll tackle [JDK-8176509](https://bugs.openjdk.org/browse/JDK-8176509) which should tidy up the README

**Comment by gnu-andrew** [comment]
This is good to go from my side. Waiting on a review.

**Comment by gnu-andrew** [comment]
> Probably we should move this document to the new doc folder? Do we have a plans to align Readme/BuildDoc to the jdk/jdk version, simple readme with a few links and other docs in "doc" folder?: https://github.com/openjdk/jdk

That sounds a sensible approach. I'd prefer to do that via backports where possible, but it sounds like the doc change is buried in the mono transition so it might not be possible with that one. This is the first step. [JDK-8176509](https://bugs.openjdk.org/browse/JDK-8176509) would be the second.

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by gnu-andrew** [comment]
> Lgtm.

Thanks Paul. Flagged for approval.

**Comment by gnu-andrew** [comment]
I see `jdk8u-fix-yes` now

**Comment by gdams** [comment]
@gnu-andrew is the plan to backport JDK-8176509 next?

**Pull request closed without merging**
