### PR TITLE
8248876: LoadObject with bad base address created for exec file on linux

### PR DESCRIPTION
**Pull request by ktakakuri**
I would like to backport
8248876: LoadObject with bad base address created for exec file on linux.

The original patch does not apply cleanly to 8u, and this is a clean backport from 11u.

Testing:
build on Linux x86_64
tier1 on Linux x86_64

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8248876](https://bugs.openjdk.java.net/browse/JDK-8248876): LoadObject with bad base address created for exec file on linux

### Reviewers
 * [Paul Hohensee](https://openjdk.java.net/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk8u-dev pull/47/head:pull/47` \
`$ git checkout pull/47`

Update a local copy of the PR: \
`$ git checkout pull/47` \
`$ git pull https://git.openjdk.java.net/jdk8u-dev pull/47/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 47`

View PR using the GUI difftool: \
`$ git pr show -t 47`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk8u-dev/pull/47.diff">https://git.openjdk.java.net/jdk8u-dev/pull/47.diff</a>

</details>

### CODE REVIEW

**Comment by ktakakuri** [comment]
Could anyone review this backport please?

**Review by phohensee — APPROVED** [review]
Confirmed the backport from 11u is clean.

**Comment by phohensee** [comment]
Pref-submit build failures appear to be due to incompatible compilers.

**Comment by ktakakuri** [comment]
@phohensee 
Thank you for your review.
I am not sure if I should continue to integrate.
Is there any other work that needs to be done?

**Comment by phohensee** [comment]
Yes. You need to tag the JBS issue with 'jdk8u-fix-request' and wait for a maintainer to approve it by adding the 'jdk8u-fix-yes' tag. Once that's done, you can integrate it. I'll sponsor if you like.

**Comment by phohensee** [comment]
/sponsor

Got the approval. Presubmit failures appear to be an infrastructure problem.

**Comment by gnu-andrew** [comment]
> /sponsor
> 
> Got the approval. Presubmit failures appear to be an infrastructure problem.

This has been fixed by JDK-8284772 for some time. For future such PRs, I'd suggest a rebase so the tests are re-run.

**Pull request closed without merging**
