### PR TITLE
8031567: Better model for storing source revision information

### PR DESCRIPTION
**Pull request by gnu-andrew**
In implementing [JDK-8222975](https://bugs.openjdk.java.net/browse/JDK-8222975) and backporting [JDK-8210283](https://bugs.openjdk.java.net/browse/JDK-8210283), we have avoided backporting [JDK-8031567](https://bugs.openjdk.java.net/browse/JDK-8031567) in order to keep things simple. However, the net result has been that we have introduced [unique 8u bugs](https://mail.openjdk.java.net/pipermail/jdk8u-dev/2022-April/014842.html)

Rather than just patching up 8u again, it seems to make sense to just bring it into line with later JDKs. There might have been a reason to keep 8u different when it was a forest of Mercurial repositories, but it is now a single Git tree like the other JDK repositories. Handling the same thing but in a unique way just makes any future backporting harder to deal with.

In light of this, I've now backported 8031567. I started by reverting the two 8u-specific patches, 8210283 & 8222975, and then applied 8136771 & 8031567 (which includes 8222975), along with follow-up fixes 8170385 & 8170392. 8210283 was then rebackported on top of this.

A couple of additional fixes were then made to workaround Makefile differences in 8u. Due to the lack of [JDK-8069261](https://bugs.openjdk.java.net/browse/JDK-8069261) the `MakeDir` usage needs to be wrapped in `eval`. 8u also doesn't have the modern macro format from  [JDK-8074988](https://bugs.openjdk.java.net/browse/JDK-8074988) and earlier fixes, so the `SetupGetRevisionForRepo` macro was modified to work in a similar way to other macros do in 8u. The stripping of `$1` is necessary to avoid it trying to create variables beginning with a space (something which led to empty variables and confused me for some time)

I did consider backporting those as well, but felt there were too intrusive to other areas of the build. At least we now have a template in this patch for how to convert any future instances.

The end result actually looks pretty straightforward and differences between this and the `make/SourceRevision.gmk` file in 11u are small.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (1 review required, with at least 1 reviewer)

### Issues
 * [JDK-8031567](https://bugs.openjdk.java.net/browse/JDK-8031567): Better model for storing source revision information
 * [JDK-8170385](https://bugs.openjdk.java.net/browse/JDK-8170385): JDK-8031567 broke source bundles
 * [JDK-8170392](https://bugs.openjdk.java.net/browse/JDK-8170392): JDK-8031567 broke builds from source bundles

### Reviewers
 * [Severin Gehwolf](https://openjdk.java.net/census#sgehwolf) (@jerboaa - **Reviewer**) ⚠️ Review applies to [3f4af272](https://git.openjdk.java.net/jdk8u-dev/pull/62/files/3f4af272acefb0007baa7649ad602f43c591cc54)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk8u-dev pull/62/head:pull/62` \
`$ git checkout pull/62`

Update a local copy of the PR: \
`$ git checkout pull/62` \
`$ git pull https://git.openjdk.java.net/jdk8u-dev pull/62/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 62`

View PR using the GUI difftool: \
`$ git pr show -t 62`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk8u-dev/pull/62.diff">https://git.openjdk.java.net/jdk8u-dev/pull/62.diff</a>

</details>

### CODE REVIEW

**Comment by gnu-andrew** [comment]
Looks like 8136771 is private.

**Comment by gnu-andrew** [comment]
Note that this PR also updates `common/autoconf/generated-configure.sh` which was missed by #33

**Review by jerboaa — APPROVED** [review]
This looks OK to me. I've tested this with an tar archive as sources and works fine. Same with git.

@shiyuexw If you could test this too, I'd appreciate it. Thanks!

**Comment by jerboaa** [comment]
@gnu-andrew Could you please merge with master please, then mac os x builds should be happy too.

**Comment by shiyuexw** [comment]
> This looks OK to me. I've tested this with an tar archive as sources and works fine. Same with git.
> 
> @shiyuexw If you could test this too, I'd appreciate it. Thanks!

I have verified it. It can work now.

**Comment by gnu-andrew** [comment]
@jerboaa I've flagged the bug with `jdk8u-fix-request`

**Comment by gnu-andrew** [comment]
I see `jdk8u-fix-yes`.

**Pull request closed without merging**
