### PR TITLE
8137329: [windows] Build broken on VS2010 after  "8046148: JEP 158: Unified JVM Logging"

### PR DESCRIPTION
**Pull request by ktakakuri**
Hi all, This is a backport of JDK-8137329: [windows] Build broken on VS2010 after "8046148: JEP 158: Unified JVM Logging".
I worked on backporting JDK-8159695 to jdk8u ( https://github.com/openjdk/jdk8u-dev/pull/428 ), and found that VS2010 build fails. This is because strtoull function, which the JDK-8159695 patch contains, is not predefined in VS2010. This patch defines strtoull macro when the earlier versions of Visual Studio are used, so this patch need to be backported for builing with VS2010 if JDK-8159695 is backported as proposed.

This patch couldn't be applied cleanly due to a previously backported fix for earlier versions of Visual Studio at the same location, which needs to be merged.

The risk is low as this only affects earlier VS builds and introduces one macro.  
Testing: GHA

Thank you.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8137329](https://bugs.openjdk.org/browse/JDK-8137329) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8137329](https://bugs.openjdk.org/browse/JDK-8137329): [windows] Build broken on VS2010 after  "8046148: JEP 158: Unified JVM Logging" (**Bug** - P4 - Approved)

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**) ⚠️ Review applies to [7b175458](https://git.openjdk.org/jdk8u-dev/pull/434/files/7b175458c34c3f7a8b5b3be39bbb79e5a874e179)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/434/head:pull/434` \
`$ git checkout pull/434`

Update a local copy of the PR: \
`$ git checkout pull/434` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/434/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 434`

View PR using the GUI difftool: \
`$ git pr show -t 434`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/434.diff">https://git.openjdk.org/jdk8u-dev/pull/434.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/434#issuecomment-1911515432)

### CODE REVIEW

**Review by tstuefe — APPROVED** [review]
Okay.

**Comment by tstuefe** [comment]
Please look at the test errors in GHAs and check them. Provided they have nothing to do with the patch, my approval still stands.

**Comment by ktakakuri** [comment]
Some tests are failing in GHA, but they are irrelevant as they are related to certification or GC.

**Comment by ktakakuri** [comment]
/approval request Fix Request 8u  
Backporting JDK-8159695 requires this patch. The patch applies with trivial conflict resolution. Low risk, defining macro.
Tesing: GHA, and hotspot_tier1.

**Comment by gnu-andrew** [comment]
Given #428 breaks the build because this function is not present on VS2010, I think this change should go in before #428, not after.

@ktakakuri can you update this PR to apply against latest master, so we can get it in? Thanks.

**Comment by ktakakuri** [comment]
I reverted JDK-8159695 fix.

**Review by gnu-andrew — APPROVED** [review]
Thanks for updating. Change looks good to me.

**Pull request closed without merging**
