### PR TITLE
8318039: GHA: Bump macOS and Xcode versions

### PR DESCRIPTION
**Pull request by zzambers**
This backport is written from scratch, as GHA workflows in jdk8u differ significantly from newer jdk versions.

Notes:
- additionally installed `gawk` to prevent build error on newer macos (see my [comment](https://github.com/openjdk/jdk17u-dev/pull/2206#issuecomment-2217722646))
- interestingly, unlike for newer jdks (11, 17), additional backports do not seem necessary to pass the build, probably build system of jdk8 is more relaxed, when it comes to warnings as errors
- fixes problem of stuck macos jobs in GHA (caused by dropping of macos-11 by GitHub)

Testing:
- macos builds pass
- there are some test failures on updated macos, probably problem in test environment, seem to be hostname related -> to be fixed (either here, or in separate PR)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8318039](https://bugs.openjdk.org/browse/JDK-8318039) needs maintainer approval

### Issue
 * [JDK-8318039](https://bugs.openjdk.org/browse/JDK-8318039): GHA: Bump macOS and Xcode versions (**Enhancement** - P4 - Approved)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/544/head:pull/544` \
`$ git checkout pull/544`

Update a local copy of the PR: \
`$ git checkout pull/544` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/544/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 544`

View PR using the GUI difftool: \
`$ git pr show -t 544`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/544.diff">https://git.openjdk.org/jdk8u-dev/pull/544.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/544#issuecomment-2217972185)

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
Looks fine to me. The warnings are still there and it would probably be good to fix them. In separate PRs though.

**Comment by zzambers** [comment]
/approval request Fixes MacOS testing in GHA by updating MacOS/XCode to newer versions, affects GHA testing only

**Comment by zzambers** [comment]
Most of macos test failures seem to be caused by machine hostname not being resolved to IP, as expected. When I tried to add entry to `/etc/hosts` assigning `127.0.0.1` to hostname of the machine, in separate branch, it [fixes](https://github.com/zzambers/jdk8u-dev/actions/runs/9860081409) most of the failures. (there are few remaining failures though)

@jerboaa Should I include fix here or rather create separate followup issue?

**Comment by jerboaa** [comment]
> @jerboaa Should I include fix here or rather create separate followup issue?

We need to include any necessary fixes before we can include this one. So I'd either be a) backport separately as preparation for this backport b) include with this. Leaning towards a).

**Comment by zzambers** [comment]
I have done some additional testing and  `macos-13` machines indeed do not resolve their own hostname to IP address. I see this infra/environment issue by GitHub.

This causes many tier1 test failures on jdk8 (many `com/sun/jdi/*` and `runtime/7158988/FieldMonitor.java`). However on newer jdk, it does not cause tier1 test failures, even without any workaround (I also checked on jdk11 with some not-yet-integrated fixes cherry-picked and disabled-warning-as-errors on mac). So (hopefully temporary) workaround could probably be jdk8 specific. 

Ideally this would be fixed by GitHub in their infra/images, I have found there was the same macos issue in the past. I [commented](https://github.com/actions/runner-images/issues/1335#issuecomment-2220149413) there (I can open new issue, if it does not get attention).

**Comment by zzambers** [comment]
I have done some additional testing and  `macos-13` machines indeed do not resolve their own hostname to IP address. I see this infra/environment issue by GitHub.

This causes many tier1 test failures on jdk8 (many `com/sun/jdi/*` and `runtime/7158988/FieldMonitor.java`). It does not cause failures on openjdk/jdk, jdk21u-dev, even without workaround as it seems. It does, however, cause failures on jdk11 (checked on jdk11 with some not-yet-integrated fixes cherry-picked and disabled-warning-as-errors on macos-13). So failures are not jdk8 specific as I previously thought...

Ideally this would be fixed by GitHub in their infra/images, I have found there was the same macos issue in the past. I [commented](https://github.com/actions/runner-images/issues/1335#issuecomment-2220149413) there (I can open new issue, if it does not get attention). Maybe I should wait for their reaction, before doing workaround and backporting it.

**Comment by vieiro** [comment]
Hi @zzambers @jerboaa ,

In [the latest 11 builds on macos-13](https://github.com/openjdk/jdk11u-dev/pull/2854/checks?check_run_id=27365009791) the tests that are failing [1] are all related to JDI/JDWP, and report connection failures, and the tests fail only on this platform.

An example stack trace (attached): [stack-trace.txt](https://github.com/user-attachments/files/16192857/stack-trace.txt) shows (note the empty `localAddress`):

```
Caused by: java.lang.InternalError: Failed remote listen: java.util.concurrent.ExecutionException: com.sun.jdi.connect.TransportTimeoutException: timeout waiting for connection @ com.sun.jdi.SocketListen (defaults: timeout=, port=, localAddress=) -- {timeout=timeout=5000, port=port=50478, localAddress=localAddress=}
```

And then times out:
```
2024-07-12T08:44:34.5430720Z Caused by: com.sun.jdi.connect.TransportTimeoutException: timeout waiting for connection
2024-07-12T08:44:34.5432330Z 	at jdk.jdi/com.sun.tools.jdi.SocketTransportService.accept(SocketTransportService.java:379)
2024-07-12T08:44:34.5460550Z 	at jdk.jdi/com.sun.tools.jdi.GenericListeningConnector.accept(GenericListeningConnector.java:155)
```

I was wondering if this is something related to `-Djava.net.preferIPv4Stack=true` perhaps? 

[1]
```
jdk/jshell/ExceptionMessageTest.java: Test exception().getMessage() in events returned by eval()
jdk/jshell/JdiFailingLaunchExecutionControlTest.java: Tests for JDI connector failure
jdk/jshell/JdiFailingListenExecutionControlTest.java: Tests for JDI connector failure
jdk/jshell/JdiHangingLaunchExecutionControlTest.java: Tests for JDI connector timeout failure 

com/sun/jdi/AccessSpecifierTest.java: Test fix for JDI: methods Accessible.is...() lie about array types
com/sun/jdi/AfterThreadDeathTest.java: Creating a StepRequest on a nonexistant thread fails
com/sun/jdi/ArrayRangeTest.java: Test access to ranges within ArrayReferences
com/sun/jdi/ConstantPoolInfo.java: Test ReferenceType.majorVersion(), minorVersion, constantPoolCount and ConstantPool apis.
com/sun/jdi/CountFilterTest.java: Check correct processing of filters after a count filter
com/sun/jdi/EarlyReturnNegativeTest.java: Unexpected ClassCastException in ThreadReference.forceEarlyReturn
com/sun/jdi/EarlyReturnTest.java: Need a way to create JDI VoidValue for use in ThreadReference.forceEarlyReturn
com/sun/jdi/FieldWatchpoints.java: Test fix for: JDWP: WatchpointEvents outside of class filtered out
com/sun/jdi/FramesTest.java: Test ThreadReference.frames(int,int)
com/sun/jdi/InstanceFilter.java: Verify that an instance filter on a MethodEntryRequest works properly.
com/sun/jdi/InterfaceMethodsTest.java: JDI: Add support for static, private and default methods in interfaces
com/sun/jdi/InvokeTest.java: Test argument types for invoke
com/sun/jdi/LocalVariableEqual.java: Test
com/sun/jdi/LocationTest.java: Test that Method.location() returns the right values
com/sun/jdi/ModificationWatchpoints.java: Test all info returned by modification watchpoints
com/sun/jdi/MonitorEventTest.java: Simple basic test of jdi Monitor request and event.
com/sun/jdi/MonitorFrameInfo.java: MonitorInfo objects aren't invalidated when the owning thread is resumed
com/sun/jdi/NullThreadGroupNameTest.java: Ensure that JDWP doesn't crash with a null thread group name
com/sun/jdi/PopAndStepTest.java: Hin says that doing a step over after a popframe acts like a resume.
com/sun/jdi/PopAsynchronousTest.java: Test the popping of frames in an asynchronous context (that is, when suspended by the debugger at random points)
com/sun/jdi/ReferrersTest.java: Add support for backtracking reference graph.
com/sun/jdi/RequestReflectionTest.java: RequestReflectionTest checks to see that reflective accessors on EventRequests return what they are given.
com/sun/jdi/ResumeOneThreadTest.java: Thread resume invalidates all stack frames, even from other threads
com/sun/jdi/SourceNameFilterTest.java: JDI add addSourceNameFilter to ClassPrepareRequest
com/sun/jdi/VarargsTest.java: JPDA: Add support for RFE 4856541 - varargs
com/sun/jdi/Vars.java: Test Method.variables() and the like.
com/sun/jdi/redefineMethod/RedefineTest.java: Test class redefinition - method data line numbers and local vars,
com/sun/jdi/sde/MangleTest.java: Test the new SourceDebugExtension facility
com/sun/jdi/sde/TemperatureTableTest.java: Test the new SourceDebugExtension facility
```

**Comment by zzambers** [comment]
@vieiro problem, which causes these failures on jdk8 is, that `macos-13` does not correctly resolve it's own hostname (see my [comment](https://github.com/openjdk/jdk8u-dev/pull/544#issuecomment-2220418158) higher). I have tried to work-around this issue by modifying `/etc/hosts` ( see: https://github.com/zzambers/jdk8u-dev/commit/53cac798f4615ad414e7a7eb2bd5706b86fce67b ), and it [fixed](https://github.com/zzambers/jdk8u-dev/actions/runs/9860081409/job/27226368604) most of the tests. You can try equivalent on jdk11 to see, to verify, if you face the same issue.
However it is something, which would better be fixed in GitHub images/infra.

**Comment by vieiro** [comment]
Hi  @zzambers , @jerboaa 
The [/etc/hosts](https://github.com/openjdk/jdk11u-dev/commit/3ac6cd6165b4779290f23f260ce5aee0bc392c49) fix does indeed work. I think this is related to https://github.com/actions/runner-images/issues/8649

**Comment by gnu-andrew** [comment]
> > @jerboaa Should I include fix here or rather create separate followup issue?
> 
> We need to include any necessary fixes before we can include this one. So it would either be a) backport separately as preparation for this backport b) include with this. Leaning towards a).

I don't see why. Having a Mac OS build is better than none at all, even if it fails a few tests (which is already true on 11u where this has been merged). Having this change in will also enable others to look at the Mac OS issues, without having to depend on this PR.

**Review by gnu-andrew — APPROVED** [review]
Backport looks good to me.

**Comment by vieiro** [comment]
For 11 I opened JDK-8336451. Also the  PRs below https://github.com/openjdk/jdk11u-dev/pull/2861 should bring the macos-build back online in 11. 

It's `getaddrinfo` that is having trouble resolving  (here's a reproducer https://github.com/vieiro/gha-macos-resolve-hostname)

**Comment by zzambers** [comment]
Considering latest comments, I am going forward with this one. Once workaround for hostname resolution is in 11, it can be backported to 8.

/integrate

**Comment by zzambers** [comment]
So there are to problems after macos update:
- Hostname resolve issue (to be fixed by backport of [JDK-8336451](https://bugs.openjdk.org/browse/JDK-8336451), after 11)
```
runtime/7158988/FieldMonitor.java
com/sun/jdi/AccessSpecifierTest.java 
com/sun/jdi/AfterThreadDeathTest.java 
com/sun/jdi/AllLineLocations.java 
com/sun/jdi/ArrayRangeTest.java 
com/sun/jdi/BacktraceFieldTest.java 
com/sun/jdi/BreakpointTest.java 
com/sun/jdi/ClassLoaderClassesTest.java 
com/sun/jdi/ClassesByName.java 
com/sun/jdi/ClassesByName2Test.java 
com/sun/jdi/ConnectedVMs.java 
com/sun/jdi/ConstantPoolInfo.java 
com/sun/jdi/CountEvent.java 
com/sun/jdi/CountFilterTest.java 
com/sun/jdi/DebuggerThreadTest.java 
com/sun/jdi/DeleteAllBkptsTest.java 
com/sun/jdi/DeleteEventRequestsTest.java 
com/sun/jdi/EarlyReturnNegativeTest.java 
com/sun/jdi/EarlyReturnTest.java 
com/sun/jdi/EnumTest.java 
com/sun/jdi/EventQueueDisconnectTest.java 
com/sun/jdi/ExceptionEvents.java 
com/sun/jdi/ExpiredRequestDeletionTest.java 
com/sun/jdi/FieldWatchpoints.java 
com/sun/jdi/FilterMatch.java 
com/sun/jdi/FilterNoMatch.java 
com/sun/jdi/FinalLocalsTest.java 
com/sun/jdi/FinalizerTest.java 
com/sun/jdi/FramesTest.java 
com/sun/jdi/GenericsTest.java 
com/sun/jdi/GetLocalVariables2Test.java 
com/sun/jdi/GetUninitializedStringValue.java 
com/sun/jdi/HomeTest.java 
com/sun/jdi/InstanceFilter.java 
com/sun/jdi/InstancesTest.java 
com/sun/jdi/InterfaceMethodsTest.java 
com/sun/jdi/InterruptHangTest.java 
com/sun/jdi/InvokeHangTest.java 
com/sun/jdi/InvokeTest.java 
com/sun/jdi/InvokeVarArgs.java 
com/sun/jdi/Java_gTest.java 
com/sun/jdi/LambdaBreakpointTest.java 
com/sun/jdi/LambdaStepTest.java 
com/sun/jdi/LaunchCommandLine.java 
com/sun/jdi/LineNumberInfo.java 
com/sun/jdi/LocalVariableEqual.java 
com/sun/jdi/LocationTest.java 
com/sun/jdi/MethodEntryExitEvents.java 
com/sun/jdi/MethodExitReturnValuesTest.java 
com/sun/jdi/MethodInvokeWithTraceOnTest.java 
com/sun/jdi/ModificationWatchpoints.java 
com/sun/jdi/MonitorEventTest.java 
com/sun/jdi/MonitorFrameInfo.java 
com/sun/jdi/MultiBreakpointsTest.java 
com/sun/jdi/NativeInstanceFilter.java 
com/sun/jdi/NewInstanceTest.java 
com/sun/jdi/NoLocInfoTest.java 
com/sun/jdi/NullThreadGroupNameTest.java 
com/sun/jdi/PopAndStepTest.java 
com/sun/jdi/PopAsynchronousTest.java 
com/sun/jdi/PopSynchronousTest.java 
com/sun/jdi/PrivateTransportTest.sh 
com/sun/jdi/RedefineCrossEvent.java 
com/sun/jdi/RedefineCrossStart.java 
com/sun/jdi/ReferrersTest.java 
com/sun/jdi/RepStep.java 
com/sun/jdi/RequestReflectionTest.java 
com/sun/jdi/ResumeOneThreadTest.java 
com/sun/jdi/SDENullTest.java 
com/sun/jdi/SimulResumerTest.java 
com/sun/jdi/SourceNameFilterTest.java 
com/sun/jdi/StepTest.java 
com/sun/jdi/SuspendThreadTest.java 
com/sun/jdi/TemplateTest.java 
com/sun/jdi/ThreadGroupTest.java 
com/sun/jdi/TwoThreadsTest.java 
com/sun/jdi/UTF8Test.java 
com/sun/jdi/UnpreparedByName.java 
com/sun/jdi/UnpreparedClasses.java 
com/sun/jdi/VMDeathLastTest.java 
com/sun/jdi/VMDeathRequestTest.java 
com/sun/jdi/VarargsTest.java 
com/sun/jdi/Vars.java 
com/sun/jdi/VisibleMethods.java 
com/sun/jdi/connect/spi/DebugUsingCustomConnector.java 
com/sun/jdi/oom/OomDebugTest.java 
com/sun/jdi/redefine/RedefineTest.java 
com/sun/jdi/redefineMethod/RedefineTest.java 
com/sun/jdi/sde/FilterMangleTest.java 
com/sun/jdi/sde/MangleStepTest.java 
com/sun/jdi/sde/MangleTest.java 
com/sun/jdi/sde/SourceDebugExtensionTest.java 
com/sun/jdi/sde/TemperatureTableTest.java  
```
- segfault in 2 tests (addressed by: https://github.com/openjdk/jdk8u-dev/pull/553)
```
compiler/unsafe/OpaqueAccesses.java
sun/misc/CopyMemory.java
```

**Pull request closed without merging**
