### PR TITLE
8282458: Update .jcheck/conf file for 8u move to git

### PR DESCRIPTION
**Pull request by gnu-andrew**
This space deliberately left empty.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282458](https://bugs.openjdk.java.net/browse/JDK-8282458): Update .jcheck/conf file for 8u move to git

### Reviewers
 * [Severin Gehwolf](https://openjdk.java.net/census#sgehwolf) (@jerboaa - no project role)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk8u-dev pull/2/head:pull/2` \
`$ git checkout pull/2`

Update a local copy of the PR: \
`$ git checkout pull/2` \
`$ git pull https://git.openjdk.java.net/jdk8u-dev pull/2/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 2`

View PR using the GUI difftool: \
`$ git pr show -t 2`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk8u-dev/pull/2.diff">https://git.openjdk.java.net/jdk8u-dev/pull/2.diff</a>

</details>

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
LGTM

**Comment by gnu-andrew** [comment]
Just waiting on jdk8u-fix-yes before push.

**Comment by jerboaa** [comment]
> Just waiting on jdk8u-fix-yes before push.

I've approved. Looking forward to see the bots resolve the bugs correctly once it's integrated :)

**Comment by gnu-andrew** [comment]
> > Just waiting on jdk8u-fix-yes before push.
> 
> I've approved. Looking forward to see the bots resolve the bugs correctly once it's integrated :)

And it worked! :)

**Pull request closed without merging**
