### PR TITLE
8205653: test/jdk/sun/management/jmxremote/bootstrap/RmiRegistrySslTest.java and RmiSslBootstrapTest.sh fail with handshake_failure

### PR DESCRIPTION
**Pull request by alexeybakhtin**
Follow-up fix for JDK-8145919
Almost clean backport except for /jdk/test/ProblemList.txt

The patch fixes intermittent failure in test/jdk/sun/management/jmxremote/bootstrap/RmiSslBootstrapTest.sh test.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] [JDK-8205653](https://bugs.openjdk.org/browse/JDK-8205653) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8205653](https://bugs.openjdk.org/browse/JDK-8205653): test/jdk/sun/management/jmxremote/bootstrap/RmiRegistrySslTest.java and RmiSslBootstrapTest.sh fail with handshake_failure (**Bug** - P3 - Requested)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) Review applies to [cd915175](https://git.openjdk.org/jdk8u-dev/pull/548/files/cd915175d1f06698da87e26e3b18788fe186f752)
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/548/head:pull/548` \
`$ git checkout pull/548`

Update a local copy of the PR: \
`$ git checkout pull/548` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/548/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 548`

View PR using the GUI difftool: \
`$ git pr show -t 548`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/548.diff">https://git.openjdk.org/jdk8u-dev/pull/548.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/548#issuecomment-2228937482)
</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by alexeybakhtin** [comment]
CI failures are not related to the changes in this PR

**Comment by alexeybakhtin** [comment]
Keep it open

**Review by mrserb — APPROVED** [review]

**Comment by alexeybakhtin** [comment]
Please review it to fix RmiRegistrySslTest.java and RmiSslBootstrapTest.sh test issues

**Pull request closed without merging**
