### PR TITLE
Merge jdk8u:master

### PR DESCRIPTION
**Pull request by gnu-andrew**
Merge `8u362-b08` to 8u-dev

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/230/head:pull/230` \
`$ git checkout pull/230`

Update a local copy of the PR: \
`$ git checkout pull/230` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/230/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 230`

View PR using the GUI difftool: \
`$ git pr show -t 230`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/230.diff">https://git.openjdk.org/jdk8u-dev/pull/230.diff</a>

</details>

### CODE REVIEW

**Comment by jerboaa** [comment]
Merge of `jdk8u362-b09` over `jdk8u362-b08`?

Anyway, 32 bit Windows GHA failure seems legit. @stooke Could you please take a look when you get a chance?

**Comment by jerboaa** [comment]
> Anyway, 32 bit Windows GHA failure seems legit. @stooke Could you please take a look when you get a chance?

@stooke tells me that we need this one to fix it:
https://github.com/openjdk/jdk8u/commit/36321be7840c8e044340b8c162a75dce3ae7698f

@gnu-andrew Any thoughts why that isn't part of the merge?

**Comment by jerboaa** [comment]
https://github.com/openjdk/jdk8u/compare/jdk8u362-b08...jdk8u362-b09?expand=1 suggests it's part of the `jdk8u362-b09` merge :)

**Comment by gnu-andrew** [comment]
> Merge of `jdk8u362-b09` over `jdk8u362-b08`?
> 
> Anyway, 32 bit Windows GHA failure seems legit. @stooke Could you please take a look when you get a chance?

Yeah, failure was expected. I wanted to see if GHA would have caught it if it had been public, so only merged b08.
Also, I noticed I used the wrong ID on the commit in jdk8u so will fix that in the jdk8u-dev version, so there is a least one version with the right ID.

**Pull request closed without merging**
