### PR TITLE
8254178: Remove .hgignore

### PR DESCRIPTION
**Pull request by gdams**
backports https://bugs.openjdk.org/browse/JDK-8254178 as it's a low-risk change

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8254178](https://bugs.openjdk.org/browse/JDK-8254178): Remove .hgignore

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/83/head:pull/83` \
`$ git checkout pull/83`

Update a local copy of the PR: \
`$ git checkout pull/83` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/83/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 83`

View PR using the GUI difftool: \
`$ git pr show -t 83`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/83.diff">https://git.openjdk.org/jdk8u-dev/pull/83.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by gdams** [comment]
@phohensee would you mind adding the fix request label to the issue on my behalf?

**Comment by gdams** [comment]
Yeah I'll backport that one separately

**Review by gnu-andrew — APPROVED** [review]
Looks good to me. Thanks for catching all the instances in the old subrepos. We should also clean up the `.jcheck` directories in those subdirectories. I doubt there is a backport for that one, so it would likely have to be an 8u bug.
Approved for 8u.

**Comment by gdams** [comment]
Thanks for the review @gnu-andrew please can you sponsor this?

**Comment by gdams** [comment]
> That would be a backport of [JDK-8254318](https://bugs.openjdk.org/browse/JDK-8254318).

@phohensee I've covered this in https://github.com/openjdk/jdk8u-dev/pull/108

**Comment by gdams** [comment]
> We should also clean up the .jcheck directories in those subdirectories. I doubt there is a backport for that one, so it would likely have to be an 8u bug.

@gnu-andrew please see https://github.com/openjdk/jdk8u-dev/pull/110 (and https://bugs.openjdk.org/browse/JDK-8292762)

**Pull request closed without merging**
