### PR TITLE
8268916: Tests for AffirmTrust roots

### PR DESCRIPTION
**Pull request by jerboaa**
Clean backport modulo context differences (after path suffeling). After this, `CAInterop.java` is the same as in openjdk/jdk11u. Patch as requested in #401 

Testing:
 - [x] GHA (includes new tests).

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8268916](https://bugs.openjdk.org/browse/JDK-8268916) needs maintainer approval

### Issue
 * [JDK-8268916](https://bugs.openjdk.org/browse/JDK-8268916): Tests for AffirmTrust roots (**Enhancement** - P3 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/406/head:pull/406` \
`$ git checkout pull/406`

Update a local copy of the PR: \
`$ git checkout pull/406` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/406/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 406`

View PR using the GUI difftool: \
`$ git pr show -t 406`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/406.diff">https://git.openjdk.org/jdk8u-dev/pull/406.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/406#issuecomment-1856449976)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by phohensee** [comment]
linux-x86 GHA failure is unrelated.

**Comment by jerboaa** [comment]
> linux-x86 GHA failure is unrelated.

Yes, thanks. We see the 32-bit failure of `gc/concurrentMarkSweep/CheckAllocateAndSystemGC.java` regularly. This patch doesn't change anything that could be related.

**Comment by jerboaa** [comment]
Keep open please.

**Comment by jerboaa** [comment]
Keep open.

**Review by gnu-andrew — APPROVED** [review]
Backport looks clean, other than the context difference from applying the eMudhra changes first.

**Comment by gnu-andrew** [comment]
Approval comment from bug: "Please approve this low-risk test addition for 8u. The patch applies cleanly but it has been re-ordered so as to match the final JDK 11u file (CAInterop.java). Test-only change low risk. Patch reviewed by Paul Hohensee."
/approve yes

**Comment by jerboaa** [comment]
Failing test `gc/logging/TestGCId.java` on 32 bit linux is unrelated.

/integrate

**Pull request closed without merging**
