### PR TITLE
8235385: Crash on aarch64 JDK due to long offset

### PR DESCRIPTION
**Pull request by apavlyutkin**
Hi!

Please review backport of 8235385 from jdk11u-dev. Original patch is applied with the following changes (except path shuffling):

- the overload of 'loadStore()' updated to be conform with the baseline
- fixed baseline conflicts in copyright sections

Verified (18.04.6 LTS/aarch64) with the reproducers from JBS, 10 of 10 runs passed. Aproximately a half of runs crashed before I've applied the patch.

Regression (18.04.6 LTS/aarch64): compiler & runtime

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.java.net/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8235385](https://bugs.openjdk.java.net/browse/JDK-8235385): Crash on aarch64 JDK due to long offset
 * [JDK-8287508](https://bugs.openjdk.java.net/browse/JDK-8287508): The tests added to jdk-8 by 8235385 are to be ported to jdk-11

### Reviewers
 * [Andrew Haley](https://openjdk.java.net/census#aph) (@theRealAph - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.java.net/census#andrew) (@gnu-andrew - **Reviewer**)

### Contributors
 * Wang Zhuo `<wzhuo@openjdk.org>`
 * Andrew Haley `<aph@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk8u-dev pull/30/head:pull/30` \
`$ git checkout pull/30`

Update a local copy of the PR: \
`$ git checkout pull/30` \
`$ git pull https://git.openjdk.java.net/jdk8u-dev pull/30/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 30`

View PR using the GUI difftool: \
`$ git pr show -t 30`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk8u-dev/pull/30.diff">https://git.openjdk.java.net/jdk8u-dev/pull/30.diff</a>

</details>

### CODE REVIEW

**Comment by apavlyutkin** [comment]
@theRealAph could you review this one as well? Thank you

**Comment by theRealAph** [comment]
I think the test case should be included in this patc.

**Comment by apavlyutkin** [comment]
> I think the test case should be included in this patc.

Do you mean adopting MyTest.java for JTReg and putting it under Git?

**Comment by theRealAph** [comment]
> > I think the test case should be included in this patc.
> 
> Do you mean adopting MyTest.java for JTReg and putting it under Git?

Is there already a regression test for this bug in the tests? If there is, you don't have to do anything. if there isn't, then yes, please put it in, under git.

**Comment by apavlyutkin** [comment]
> > > I think the test case should be included in this patc.
> > 
> > 
> > Do you mean adopting MyTest.java for JTReg and putting it under Git?
> 
> Is there already a regression test for this bug in the tests? If there is, you don't have to do anything. if there isn't, then yes, please put it in, under git.

done

**Review by theRealAph — APPROVED** [review]

**Review by gnu-andrew — COMMENTED** [review]
The testcase is only in this backport. Is there a bug to get this into trunk as well?

Also, please check you have GitHub actions enabled on this repository. It doesn't matter so much for this PR, as there is currently no AArch64 build, but it's important for more general changes.  Thanks.

**Comment by apavlyutkin** [comment]
> The testcase is only in this backport. Is there a bug to get this into trunk as well?
> 
> Also, please check you have GitHub actions enabled on this repository. It doesn't matter so much for this PR, as there is currently no AArch64 build, but it's important for more general changes. Thanks.

[JDK-8287508](https://bugs.openjdk.java.net/browse/JDK-8287508) raised to port the tests to 11, 15 that incorporates full version of the patch includes the tests

**Comment by gnu-andrew** [comment]
Thanks for filing the bug. I've removed the linked backport issues as they were for the original fix, not the test, and it wrongly makes it look like it is already fixed in 11u. When the test is backported, SKARA will automatically create backport bugs and link them.

If you use the issue command above, you should be able to reference the bug in this PR too.

**Review by gnu-andrew — APPROVED** [review]
Thanks. This should be good to go now.

**Comment by RealCLanger** [comment]
> /issue add 8287508

Hm, why did you add this issue here? (Question also goes to @gnu-andrew). Now https://bugs.openjdk.java.net/browse/JDK-8287508 is marked as resolved although no tests have yet been backported there.

**Pull request closed without merging**
