### PR TITLE
8194873: right ALT key hotkeys no longer work in Swing components

### PR DESCRIPTION
**Pull request by omikhaltsova**
I'd like to backport JDK-8194873 to jdk8u. The same issue is observed there.
The original patch for JDK-8194873 applied not cleanly due to 2 files:   
>  MotifLookAndFeel.java - differences in the header and in the context;
>  SwingUtilities2.java - difference in the context.

The backport for JDK-8155742
```
8155742: [Windows] robot.keyPress(KeyEvent.VK_ALT_GRAPH) throws java.lang.IllegalArgumentException in windows
```
was included as a part of this patch due to dependency on it of the regression test "jdk/test/javax/swing/event/RightAltKeyTest.java" included into the patch for JDK-8194873 (this test fails without the patch for JDK-8155742 as was pointed out below by Anton Litvinov).
The original patch For JDK-8155742 applied not cleanly due to 1 file:
> AltGraphModifierTest.java - differences in the header and slight in the context.

Tested on Windows. All regular tests passed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issues
 * [JDK-8194873](https://bugs.openjdk.org/browse/JDK-8194873): right ALT key hotkeys no longer work in Swing components
 * [JDK-8155742](https://bugs.openjdk.org/browse/JDK-8155742): [Windows] robot.keyPress(KeyEvent.VK_ALT_GRAPH) throws java.lang.IllegalArgumentException in windows

### Reviewers
 * [Anton Litvinov](https://openjdk.org/census#alitvinov) (@alitvinv - Committer) ⚠️ Review applies to [ace410e2](https://git.openjdk.org/jdk8u-dev/pull/60/files/ace410e27e109021b069255f5227938a6ae843c0)
 * [Yuri Nesterenko](https://openjdk.org/census#yan) (@yan-too - **Reviewer**) ⚠️ Review applies to [ace410e2](https://git.openjdk.org/jdk8u-dev/pull/60/files/ace410e27e109021b069255f5227938a6ae843c0)
 * [Sergey Bylokhov](https://openjdk.org/census#serb) (@mrserb - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/60/head:pull/60` \
`$ git checkout pull/60`

Update a local copy of the PR: \
`$ git checkout pull/60` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/60/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 60`

View PR using the GUI difftool: \
`$ git pr show -t 60`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/60.diff">https://git.openjdk.org/jdk8u-dev/pull/60.diff</a>

</details>

### CODE REVIEW

**Review by alitvinv — COMMENTED** [review]
Hello Olga,

The backport of the fix for the bug JDK-8194873 itself looks correct. When I did backport of this fix, I experienced failure of the regression test "test/jdk/javax/swing/event/RightAltKeyTest.java" to resolve which it was necessary to backport the fix for the bug JDK-8155742. Does the test "test/jdk/javax/swing/event/RightAltKeyTest.java" pass successfully in your case with this backport fix?

Thank you,
Anton

**Comment by omikhaltsova** [comment]
Hi Anton,
RightAltKeyTest.java got to the wrong place after applying the patch. That's why I didn't notice its failure while running the automated testing. 
Moved RightAltKeyTest.java from
` test/jdk/javax/swing/event/RightAltKeyTest.java`
to
` jdk/test/javax/swing/event/RightAltKeyTest.java`
Now I see this failure. Thanks!

**Comment by omikhaltsova** [comment]
The backport for JDK-8155742 fixes the failure of the regression test "jdk/test/javax/swing/event/RightAltKeyTest.java".

**Review by alitvinv — APPROVED** [review]
Hi Olga. The version "03" of the fix looks good.

Thank you,
Anton

**Comment by alitvinv** [comment]
Hi Olga. It seems that my reviewer status in JDK Project does not have effect in this "jdk8u-dev" repository. So most probably you will have to find a person with the reviewer status in this particular repository and to ask him to review and approve this backport fix, otherwise the bot will not let you enter "/integrate" command.

**Comment by omikhaltsova** [comment]
Thanks, Anton, for helping me!
At the moment I'm thinking of reworking this PR into 2 separate PRs. One of them will be a dependant PR due to the test failure. How do you think it's worth doing?

**Comment by alitvinv** [comment]
No problem. If backports of the involved 2 bugs were clean, then it would make sense to accomplish them through 2 separate PRs in order to not involve anybody in their review, but in your case your backport has insignificant differences between it and the original fixes, as you wrote "difference in the context", therefore it will be required to get approval from the code reviewer for each of these possible PRs. Regarding the current PR, from my point of view it is also correct to combine backports of 2 bugs in one fix, because otherwise the test "RightAltKeyTest.java" will be failing.

Before pushing this change as is or under separate PRs, I would also recommend to look more carefully on 2 regression tests modified by the fix JDK-8155742: "ModifierRobotKeyTest.java", "AltGraphModifierTest.java". Make sure that they pass on the supported OS versions, not only on MS Windows OS. And, if they fail, and you decide to start porting other fixes, which could be connected to "AltGraphModifierTest.java" through the source code and which are specific to macOS and to keyboard events, I do not recommend even to touch these macOS specific fixes, it will be a chain of more than 10 fixes connected with each other as a regression of a fix for regression and in the end there will be couple of regressions still unresolved, so do not port those fixes specific to keyboard events on macOS. I personally did not port them for that reason.

**Comment by omikhaltsova** [comment]
Anton, thanks for the hint and the valuable explanation!
I reran ModifierRobotKeyTest.java and AltGraphModifierTest.java (modified by JDK-8155742) on Windows, MacOS and Linux. Before the fix they fail for all platforms. After the fix they pass only for Windows (JDK-8155742 was opened only for Windows). Your experience mentioned above does not inspire me with much optimism on this way but obviously additional investigation is needed how to fix these tests' failures on MacOS and Linux.
Concerning RightAltKeyTest.java it fails before this fix and passes after.

**Review by yan-too — APPROVED** [review]

**Comment by omikhaltsova** [comment]
The build for macOS was broken and fixed by https://github.com/openjdk/jdk8u-dev/pull/61. 
It was verified locally.

**Review by mrserb — APPROVED** [review]

**Pull request closed without merging**
