### PR TITLE
8304760: Add 2 Microsoft TLS roots

### PR DESCRIPTION
**Pull request by jerboaa**
Clean backport modulo path changes to adjust to the OpenJDK 8u layout. I'd like to get this into 8u382 for symmetry with Oracle JDK 8u381.

Testing:
- [x] `sun/security/lib/cacerts/VerifyCACerts.java` and `security/infra/java/security/cert/CertPathValidator/certification` passed.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8304760](https://bugs.openjdk.org/browse/JDK-8304760): Add 2 Microsoft TLS roots

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**) ⚠️ Review applies to [c8173f64](https://git.openjdk.org/jdk8u-dev/pull/320/files/c8173f6400420bb7393d05236cabec3839b0c0d7)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/320/head:pull/320` \
`$ git checkout pull/320`

Update a local copy of the PR: \
`$ git checkout pull/320` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/320/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 320`

View PR using the GUI difftool: \
`$ git pr show -t 320`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/320.diff">https://git.openjdk.org/jdk8u-dev/pull/320.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/320#issuecomment-1562521689)

### CODE REVIEW

**Comment by jerboaa** [comment]
This is a clean backport as the only changes have been path adjustments to match the 8u layout.

/clean

**Review by gnu-andrew — APPROVED** [review]
Confirmed clean and looks good to me. Approved for 8u.

**Comment by jerboaa** [comment]
The one x64 test failure seems unrelated to this PR.

**Pull request closed without merging**
