### PR TITLE
8030204: com/sun/jdi/JdbExprTest.sh: Required output "Can\\'t convert 2147483648 to int" not found

### PR DESCRIPTION
**Pull request by ktakakuri**
Hi all,

This test fix patch is  required for Backporting JDK-4660158  and should be backported at the same time. #496
The patch can be applied cleanly to JDK-4660158 applied code.

Testing: All tests under jdk/test/com/sun/jdi

Thank you.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8030204](https://bugs.openjdk.org/browse/JDK-8030204) needs maintainer approval

### Issue
 * [JDK-8030204](https://bugs.openjdk.org/browse/JDK-8030204): com/sun/jdi/JdbExprTest.sh: Required output "Can\\'t convert 2147483648 to int" not found (**Bug** - P4 - Approved)

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)
 * [Zdenek Zambersky](https://openjdk.org/census#zzambers) (@zzambers - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/497/head:pull/497` \
`$ git checkout pull/497`

Update a local copy of the PR: \
`$ git checkout pull/497` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/497/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 497`

View PR using the GUI difftool: \
`$ git pr show -t 497`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/497.diff">https://git.openjdk.org/jdk8u-dev/pull/497.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/497#issuecomment-2107083295)

### CODE REVIEW

**Comment by ktakakuri** [comment]
/approval request Backporting JDK-4660158 requires this follow-up patch. Applies cleanly. Low risk, test fix. Tesing: GHA and the affected test.

**Comment by ktakakuri** [comment]
I resolved the conflicts.
I adopted HEAD for all conflicts.

**Review by gnu-andrew — APPROVED** [review]
Confirmed clean.

**Review by zzambers — APPROVED** [review]

**Pull request closed without merging**
