### PR TITLE
8129827: [TEST_BUG] Test java/awt/Robot/RobotWheelTest/RobotWheelTest.java fails

### PR DESCRIPTION
**Pull request by caojoshua**
Parity with Oracle. This patch is applied on top of https://github.com/openjdk/jdk8u-dev/pull/140. Does not apply cleanly, mostly due to surrounding context missing from the following:

* https://bugs.openjdk.org/browse/JDK-8210039 (don't think there are plans to backport this to JDK8)
* https://bugs.openjdk.org/browse/JDK-8159690 (open issue to backport this to 8, but has not been active for >1 year. might get backported)

Only one serious conflict. We cannot use

```
private static int wheelSign = Platform.isOSX() ? -1 : 1;
```

Since https://bugs.openjdk.org/browse/JDK-8210039 is missing in JDK8, we don't have 

```
import jdk.test.lib.Platform;
```

Alternatively, I use the old code to get OS:

```
private static int wheelSign = OSInfo.getOSType().equals(OSInfo.OSType.MACOSX) ? -1 : 1;
```

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8129827](https://bugs.openjdk.org/browse/JDK-8129827): [TEST_BUG] Test java/awt/Robot/RobotWheelTest/RobotWheelTest.java fails

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [f144ec00](https://git.openjdk.org/jdk8u-dev/pull/141/files/f144ec007b7b6bb8089ceef4c576ea9f68158368)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/141/head:pull/141` \
`$ git checkout pull/141`

Update a local copy of the PR: \
`$ git checkout pull/141` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/141/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 141`

View PR using the GUI difftool: \
`$ git pr show -t 141`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/141.diff">https://git.openjdk.org/jdk8u-dev/pull/141.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by phohensee** [comment]
Tagged the JBS issue.

**Comment by phohensee** [comment]
Consider backporting JDK-8210039. It has been backported to 11u in order to make subsequent backports easier. Same for 8u.

**Comment by caojoshua** [comment]
ping so the PR is still active. waiting on `jdk-8u-fix-yes` label

**Pull request closed without merging**
