### PR TITLE
8200468: Port the native GSS-API bridge to Windows

### PR DESCRIPTION
**Pull request by alexeybakhtin**
Hello,
I'd like to backport JDK-8200568: port the native GSS-API bridge to Windows to JDK8u
This is a prerequisite of the JDK-6722928 and JDK-8225687

The backport is not clean. I have to to make the following changes:
jdk/make/lib/SecurityLibraries.gmk
- Patched manually, just removed platform dependency

jdk/src/share/native/sun/security/jgss/wrapper/NativeUtil.c
- Clean merge except for copyright year

jdk/src/share/native/sun/security/jgss/wrapper/NativeUtil.h
- Visual Studio 2010-2012 doesn't provide inttypes.h so provide appropriate definitions the header file
- Manually updated copyright year

jdk/src/share/classes/sun/security/jgss/GSSManagerImpl.java
- Manually removed platform OS dependency

jdk/src/solaris/native/sun/security/jgss/wrapper/NativeFunc.c is moved to jdk/src/share/native/sun/security/jgss/wrapper/NativeFunc.c
- All changes applied manually because of JDK-8238388 already applied 

jdk/src/solaris/native/sun/security/jgss/wrapper/NativeFunc.h is moved to jdk/src/share/native/sun/security/jgss/wrapper/NativeFunc.h
- All changes applied clean 

jdk/test/sun/security/krb5/auto/BasicProc.java
- Manually added Windows platform dependency code

jdk/test/java/security/testlibrary/Proc.java
- Manually extended debug output

All related jtreg tests passed successfully on Windows

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8200468](https://bugs.openjdk.org/browse/JDK-8200468): Port the native GSS-API bridge to Windows (**Enhancement** - P4)

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/335/head:pull/335` \
`$ git checkout pull/335`

Update a local copy of the PR: \
`$ git checkout pull/335` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/335/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 335`

View PR using the GUI difftool: \
`$ git pr show -t 335`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/335.diff">https://git.openjdk.org/jdk8u-dev/pull/335.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/335#issuecomment-1586669566)

### CODE REVIEW

**Review by gnu-andrew — COMMENTED** [review]
Mostly looks good but there are a couple of issues:

* You mention adjusting the copyright header for `NativeUtil.c` and `NativeUtil.h`, but I don't see them in the patch. They should be bumped from 2014 to 2018. The other omissions are correct, as the files already have newer copyright headers.
* The change of the `@library` line in `BasicProc.java` is unneeded. There is a Platform class in `jdk.testlibrary` which can be imported as `jdk.testlibrary.Platform`. We should aim to resolve this duplication (caused by the JFR import) going forward, but I think for now, the test should stick to one test library. Adding the `/lib` reference means it could potentially mix the two test libraries together as they have duplicated classes, so please drop the `lib` and use `jdk.testlibrary.Platform` for now.
* In the 11u patch, the `pc.env` line is outside the `!Platform.isWindows` block, but seems to be inside in the 8u version.
11u:
~~~
+            if (!Platform.isWindows()) {
+                Files.setPosixFilePermissions(Paths.get(label + ".ccache"),
+                        Set.of(PosixFilePermission.OWNER_READ,
+                                PosixFilePermission.OWNER_WRITE));
+            }
+            pc.env("KRB5CCNAME", "FILE:" + label + ".ccache");

$ find jdk/test/ -name 'Platform.java'
jdk/test/lib/testlibrary/jdk/testlibrary/Platform.java
jdk/test/lib/jdk/test/lib/Platform.java

~~~

**Comment by alexeybakhtin** [comment]
Hello Andrew!
Thank you for the review.
I agree with the Platform usage. Switched to the  jdk.testlibrary.Platform version.
The rest findings are also fixed.

**Review by gnu-andrew — APPROVED** [review]
Thanks. It looks good with the additional changes. If you flag with `jdk8u-fix-request`, I'll approve for 8u too.

What's the end goal here? [JDK-6722928](https://bugs.openjdk.org/browse/JDK-6722928)? I'm just wondering because that one will need a CSR, essentially a clone of what [was done for 11u](https://bugs.openjdk.org/browse/JDK-8256559)

**Comment by alexeybakhtin** [comment]
> What's the end goal here? [JDK-6722928](https://bugs.openjdk.org/browse/JDK-6722928)? I'm just wondering because that one will need a CSR, essentially a clone of what [was done for 11u](https://bugs.openjdk.org/browse/JDK-8256559)

Thank you for the review. Yes, you are right. The final goal is to backport the native GSS-API library for Windows on the basis of Windows SSPI APIs (JDK-6722928) and corresponding fixes (like JDK-8225687). The CSR for JDK-6722928 is a part of backport activity, so I'm going to submit it also.

**Comment by gnu-andrew** [comment]
Thanks. I've added `jdk8u-fix-yes`.

It is a little curious that Oracle apparently backported [8225687](https://bugs.openjdk.org/browse/JDK-8225687) to 8u & 11u, but not 6722928, and so there is no CSR in place already. Definitely worth making sure there's plenty of time to allow the CSR to be approved, so thanks for starting on this early in the 8u392 cycle.

**Pull request closed without merging**
