### PR TITLE
8205399: Set node color on pinned HashMap.TreeNode deletion

### PR DESCRIPTION
**Pull request by shipilev**
See the issue for details. It reproduces in 8u, which breaks applications that run with `-ea -esa` for extra safety. We have seen at least two in-production bug reports due to this.

The backport is not clean, because the test should reside in the different folder.

The verification barfs on discovering the red root, when it also discovers left/right child node is also red. This technically violates one of the basic properties of RB trees: a red node should not have red children. We can always change (sub-)root node color from red to black without violating RB properties, as the path to any descendant node would still have the same number of black nodes. AFAIU, leaving the (sub-)root red and the child red could potentially break something else. This is why I believe this backport is required and safe for 8u.

Additional testing:
 - [x] Linux x86_64, new regression test fails without the patch, passes with it
 - [x] Linux x86_64 `jdk_util`
 - [x] Linux x86_64 fastdebug `tier1` (some intermittent failures, which look unrelated and present in current master)

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8205399](https://bugs.openjdk.org/browse/JDK-8205399): Set node color on pinned HashMap.TreeNode deletion (**Bug** - P4)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/325/head:pull/325` \
`$ git checkout pull/325`

Update a local copy of the PR: \
`$ git checkout pull/325` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/325/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 325`

View PR using the GUI difftool: \
`$ git pr show -t 325`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/325.diff">https://git.openjdk.org/jdk8u-dev/pull/325.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/325#issuecomment-1568232819)

### CODE REVIEW

**Comment by phohensee** [comment]
/clean

File location change only.

**Comment by shipilev** [comment]
I also do not see any relevant bugtail in `HashMap.java` up to JDK 21.

Hey @DougLea, are you good with this going in 8u?

**Comment by DougLea** [comment]
Yes, this was a  rare bug that hadn't got checked for years in HashMap tests. There's no reason not to backport.

**Comment by shipilev** [comment]
> Yes, this was a rare bug that hadn't got checked for years in HashMap tests. There's no reason not to backport.

Thank you!

**Comment by shipilev** [comment]
Testing is clean, push approval is here.

/integrate

**Pull request closed without merging**
