### PR TITLE
8068305: [TEST_BUG] Test java/awt/Mixing/HWDisappear.java fails with GTKL&F

### PR DESCRIPTION
**Pull request by mrserb**
Hi all,

This pull request contains a backport of commit [bc24a0ce](https://github.com/openjdk/jdk/commit/bc24a0ce18373217b97dc3a8f4071a7ffc92691d) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Alexander Zvegintsev on 13 Jan 2015 and was reviewed by Alexander Scherbatiy and Sergey Bylokhov.

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8068305](https://bugs.openjdk.org/browse/JDK-8068305) needs maintainer approval

### Issue
 * [JDK-8068305](https://bugs.openjdk.org/browse/JDK-8068305): [TEST_BUG] Test java/awt/Mixing/HWDisappear.java fails with GTKL&amp;F (**Bug** - P4 - Approved)

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/575/head:pull/575` \
`$ git checkout pull/575`

Update a local copy of the PR: \
`$ git checkout pull/575` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/575/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 575`

View PR using the GUI difftool: \
`$ git pr show -t 575`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/575.diff">https://git.openjdk.org/jdk8u-dev/pull/575.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/575#issuecomment-2342650297)
</details>

### CODE REVIEW

**Comment by mrserb** [comment]
keep open

**Review by gnu-andrew — APPROVED** [review]
Confirmed clean.

**Comment by gnu-andrew** [comment]
Moved to 8u452; see https://mail.openjdk.org/pipermail/jdk8u-dev/2024-December/019551.html

**Pull request closed without merging**
