### PR TITLE
8239312: [macOS] javax/swing/JFrame/NSTexturedJFrame/NSTexturedJFrame.java

### PR DESCRIPTION
**Pull request by mrserb**
Hi all,

This pull request contains a backport of commit [40e667c1](https://github.com/openjdk/jdk/commit/40e667c174269a73cd9b5612673c5e4b2293d6c0) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Prasanta Sadhukhan on 26 Mar 2020 and was reviewed by Sergey Bylokhov.

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8239312](https://bugs.openjdk.org/browse/JDK-8239312) needs maintainer approval

### Issue
 * [JDK-8239312](https://bugs.openjdk.org/browse/JDK-8239312): [macOS] javax/swing/JFrame/NSTexturedJFrame/NSTexturedJFrame.java (**Bug** - P3 - Approved)

### Reviewers
 * [Andrew Haley](https://openjdk.org/census#aph) (@theRealAph - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/531/head:pull/531` \
`$ git checkout pull/531`

Update a local copy of the PR: \
`$ git checkout pull/531` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/531/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 531`

View PR using the GUI difftool: \
`$ git pr show -t 531`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/531.diff">https://git.openjdk.org/jdk8u-dev/pull/531.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/531#issuecomment-2198423348)

### CODE REVIEW

**Comment by mrserb** [comment]
/clean The patch is identical to openjdk/jdk.

**Review by theRealAph — APPROVED** [review]

**Review by gnu-andrew — APPROVED** [review]
Patch verified clean.

**Comment by gnu-andrew** [comment]
This is a MacOS patch but the GHA MacOS build has not been run. Please merge with the current jdk8u-dev so that the Mac build runs before we approve this patch. It should be working now (see https://github.com/gnu-andrew/jdk8u-dev/actions/runs/10619513292/job/29437308137 for example)

**Comment by mrserb** [comment]
> This is a MacOS patch but the GHA MacOS build has not been run. Please merge with the current jdk8u-dev so that the Mac build runs before we approve this patch. It should be working now (see https://github.com/gnu-andrew/jdk8u-dev/actions/runs/10619513292/job/29437308137 for example)

done. There are some known failed tests: ".../CertPathValidator/certification/CAInterop#..."

**Comment by phohensee** [comment]
All the GHA failures but one are cert issues that look unrelated. For that one (MacOS-x64 hotspot/test/compiler/unsafe/OpaqueAccesses.java) I merged the patch with the latest upstream 8u and ran it on my Intel Mac laptop and it passed. So did the modified test.

**Comment by gnu-andrew** [comment]
> All the GHA failures but one are cert issues that look unrelated. 

Yes, same as noted on #516. We should exclude them. They fail on trunk too.

> For that one (MacOS-x64 hotspot/test/compiler/unsafe/OpaqueAccesses.java) I merged the patch with the latest upstream 8u and ran it on my Intel Mac laptop and it passed. So did the modified test.

Shouldn't @mrserb's merge mean that GHA was run against latest upstream 8u-dev too? Maybe the test fails sporadically?

I'm approving this but please don't push until 8u442 is open.

/approve yes

**Comment by phohensee** [comment]
It does seem that this PR was merged with the latest upstream and ran GHA.

**Pull request closed without merging**
