### PR TITLE
8129572: Cleanup usage of getResourceAsStream in jaxp

### PR DESCRIPTION
**Pull request by akashche**
Please review a backport of a JAXP cleanup.

Original commit [17b47acf5b3d](https://hg.openjdk.java.net/jdk9/jdk9/jaxp/rev/17b47acf5b3d) in jdk9.

Commit [4ebbfc9](https://github.com/openjdk/jdk11u-dev/commit/4ebbfc918f558e73c05f471cfd3ab2b11dcf5a75) in jdk11u-dev.

This cleanup should allow to backport other JAXP changes (like [JDK-8163121](https://bugs.openjdk.java.net/browse/JDK-8163121)) easier.

All code changes apply cleanly (with reshuffled paths) except [LSSerializerTest.java](https://github.com/openjdk/jdk11u-dev/blob/4ebbfc918f558e73c05f471cfd3ab2b11dcf5a75/jaxp/test/javax/xml/jaxp/unittest/org/w3c/dom/ls/LSSerializerTest.java) that was excluded. LSSerializerTest.java is not present in 8u, it was added with JDK-8043084 (not public, jdk9 commit [29ba77ad2a87](https://hg.openjdk.java.net/jdk9/jdk9/jaxp/rev/29ba77ad2a87)).

Testing:

 - [x] jtreg:javax/xml/jaxp
 - [x] jck:api/javax_xml

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8129572](https://bugs.openjdk.java.net/browse/JDK-8129572): Cleanup usage of getResourceAsStream in jaxp

### Reviewers
 * [Andrew John Hughes](https://openjdk.java.net/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk8u-dev pull/4/head:pull/4` \
`$ git checkout pull/4`

Update a local copy of the PR: \
`$ git checkout pull/4` \
`$ git pull https://git.openjdk.java.net/jdk8u-dev pull/4/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4`

View PR using the GUI difftool: \
`$ git pr show -t 4`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk8u-dev/pull/4.diff">https://git.openjdk.java.net/jdk8u-dev/pull/4.diff</a>

</details>

### CODE REVIEW

**Comment by gnu-andrew** [comment]
This looks fine to me; only difference from the 11u patch, other than the paths, is the missing test change, which just adds some `println` statements to it. While it might be nice to bring in all those additional tests for 8u, JDK-8043084 is not a mandatory prerequisite of this change.

Please flag with `jdk8u-fix-request`.

**Comment by akashche** [comment]
Thanks for the review! I've marked the issue for approval.

**Comment by akashche** [comment]
Thanks for the approval! Should this PR be somehow marked as "reviewed" or can I go forward and integrate it?

**Review by gnu-andrew — APPROVED** [review]
Marked as reviewed. I was holding off as SKARA doesn't yet check for `jdk8u-fix-yes` (see SKARA-1199)

**Pull request closed without merging**
