### PR TITLE
8333724: Problem list security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#teliasonerarootcav1

### PR DESCRIPTION
**Pull request by sendaoYan**
Hi all,

This pull request contains a backport of commit [8ffc35d1](https://github.com/openjdk/jdk/commit/8ffc35d117846a7a2aa08afed662273d2f887770) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Matthias Baesken on 7 Jun 2024 and was reviewed by Lutz Schmidt and Sergey Bylokhov.

This backport not clean because the `jdk/test/Problemlist.txt` has been moved to `test/jdk/Problemlist.txt` Add the testcase to problemlist, no risk.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8333724](https://bugs.openjdk.org/browse/JDK-8333724) needs maintainer approval

### Issue
 * [JDK-8333724](https://bugs.openjdk.org/browse/JDK-8333724): Problem list security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#teliasonerarootcav1 (**Sub-task** - P4 - Approved)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/514/head:pull/514` \
`$ git checkout pull/514`

Update a local copy of the PR: \
`$ git checkout pull/514` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/514/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 514`

View PR using the GUI difftool: \
`$ git pr show -t 514`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/514.diff">https://git.openjdk.org/jdk8u-dev/pull/514.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/514#issuecomment-2154403096)

### CODE REVIEW

**Comment by sendaoYan** [comment]
/approval request Backport to add the testcase to problemlist, no risk.

**Review by jerboaa — APPROVED** [review]

**Comment by jerboaa** [comment]
Please merge master as the two failures of "Linux additional" and "Windows x86" should be solved then.

**Comment by sendaoYan** [comment]
> Please merge master as the two failures of "Linux additional" and "Windows x86" should be solved then.

Okey, thanks.

**Comment by jerboaa** [comment]
The remaining CA failures for sslcom root CAs are:
https://bugs.openjdk.org/browse/JDK-8333788

**Comment by sendaoYan** [comment]
All the failures reported by GHA, are all the two testcases run failed, which has been recorded by [JDK-8333788](https://bugs.openjdk.org/browse/JDK-8333788), unrelated to this PR.
```
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#sslrooteccca 
security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#sslrootevrsaca 
```


/integrate

**Comment by sendaoYan** [comment]
> /approve yes

Thanks for the approved.

**Comment by sendaoYan** [comment]
Thanks for the review and sponsor.

**Pull request closed without merging**
