### PR TITLE
6722928: Provide a default native GSS-API library on Windows

### PR DESCRIPTION
**Pull request by alexeybakhtin**
Please review the backport of sspi bridge to JDK8

The backport is based on the JDK11 version and is almost clean.
The copyright years are updated manually:
- NativeFunc.h already has a newer copyright year
- SunNativeProvider.java updated manually
The main difference is a build script for sspi_bridge. It is located in SecurityLibraries.gmk

No regressions on the sun/security/krb5 tests (Windows and Linux platforms)

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-6722928](https://bugs.openjdk.org/browse/JDK-6722928): Provide a default native GSS-API library on Windows (**Enhancement** - P3)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/340/head:pull/340` \
`$ git checkout pull/340`

Update a local copy of the PR: \
`$ git checkout pull/340` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/340/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 340`

View PR using the GUI difftool: \
`$ git pr show -t 340`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/340.diff">https://git.openjdk.org/jdk8u-dev/pull/340.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/340#issuecomment-1633625152)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by alexeybakhtin** [comment]
Pre-submit build test fails for macOS x64 but it is not related to the changes itself
CSR is approved
@gnu-andrew , Do you think this feature can be added to the next release?

**Review by gnu-andrew — COMMENTED** [review]
Thanks for getting the CSR sorted. If that's approved for 8u, I don't have an issue with this change going into 8u.

As to the backport itself, it mostly looks good. The `Makefile` changes seem appropriate, given its location in a more general file, and I presume that it does build :)

There is a hunk missing in `SunNativeProvider.java`:

~~~
-@@ -68,7 +68,7 @@ public final class SunNativeProvider extends Provider {
-     static {
-         MECH_MAP =
-             AccessController.doPrivileged(
--                new PrivilegedAction<HashMap<String, String>>() {
-+                new PrivilegedAction<>() {
-                     public HashMap<String, String> run() {
-                         DEBUG = Boolean.parseBoolean
-                             (System.getProperty(DEBUG_PROP));
~~~

While I'm not a fan of doing these kind of unrelated changes in the patch, it was in the original fix. Was the compiler unable to derive this type in 8u or was it just an accidental omission?

**Comment by alexeybakhtin** [comment]
> While I'm not a fan of doing these kind of unrelated changes in the patch, it was in the original fix. Was the compiler unable to derive this type in 8u or was it just an accidental omission?

Hi @gnu-andrew Thank you for review!

**Review by gnu-andrew — APPROVED** [review]
Ah, I thought it might be something like that. Ok, patch looks good as is to me, let's get this in. Approved for 8u.

**Pull request closed without merging**
