### PR TITLE
8285497: Add system property for Java SE specification maintenance version

### PR DESCRIPTION
**Pull request by jddarcy**
Same diff as used in the JDK 8u RI update.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8285497](https://bugs.openjdk.org/browse/JDK-8285497): Add system property for Java SE specification maintenance version

### Reviewers
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [cb3240d5](https://git.openjdk.org/jdk8u-dev/pull/100/files/cb3240d52016b05804261e095c6f05ab91546911)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - Author) ⚠️ Review applies to [cb3240d5](https://git.openjdk.org/jdk8u-dev/pull/100/files/cb3240d52016b05804261e095c6f05ab91546911)
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**) ⚠️ Review applies to [cb3240d5](https://git.openjdk.org/jdk8u-dev/pull/100/files/cb3240d52016b05804261e095c6f05ab91546911)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/100/head:pull/100` \
`$ git checkout pull/100`

Update a local copy of the PR: \
`$ git checkout pull/100` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/100/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 100`

View PR using the GUI difftool: \
`$ git pr show -t 100`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/100.diff">https://git.openjdk.org/jdk8u-dev/pull/100.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
Looks good. Thanks.

**Review by irisclark — APPROVED** [review]
Spec changes match those in JSR 337 MR 4.

**Review by mlchung — APPROVED** [review]

**Review by gnu-andrew — CHANGES_REQUESTED** [review]
Change looks good and nearly the same as that in 8u42. However, one copyright header change was missed in `System.c`, presumably due to 8189761 already having bumped it to 2019. Can we fix this please?

Also, please change the title to "Backport 31a63ba5f255e09349b3842984ac5bb3ad8e6c0b" so SKARA correctly identifies this as a backport. See https://wiki.openjdk.org/display/SKARA/Backports

**Comment by jddarcy** [comment]
> Change looks good and nearly the same as that in 8u42. However, one copyright header change was missed in `System.c`, presumably due to 8189761 already having bumped it to 2019. Can we fix this please?
> 
> Also, please change the title to "Backport 31a63ba5f255e09349b3842984ac5bb3ad8e6c0b" so SKARA correctly identifies this as a backport. 

I've done as you've requested.

> See https://wiki.openjdk.org/display/SKARA/Backports

Yes, I am familiar with the basic operation of Skara. I don't see anything on the referenced page that requires use of a Skara Backport PR when doing a backport. The impetus for adding the backport feature to Skara, a feature enabled several months after JDK mainline switched to Skara, was to reduce the overhead of the common case of backport a fix to an earlier release where few to no changes are needed.

Before sending out this PR, I looked for, but did not find, documentation for what procedures 8u wanted to use for a situation like this.

**Review by gnu-andrew — APPROVED** [review]
Updated patch looks good

**Comment by gnu-andrew** [comment]
> > Change looks good and nearly the same as that in 8u42. However, one copyright header change was missed in `System.c`, presumably due to 8189761 already having bumped it to 2019. Can we fix this please?
> > Also, please change the title to "Backport 31a63ba5f255e09349b3842984ac5bb3ad8e6c0b" so SKARA correctly identifies this as a backport.
> 
> I've done as you've requested.
> 
> > See https://wiki.openjdk.org/display/SKARA/Backports
> 
> Yes, I am familiar with the basic operation of Skara. I don't see anything on the referenced page that requires use of a Skara Backport PR when doing a backport. The impetus for adding the backport feature to Skara, a feature enabled several months after JDK mainline switched to Skara, was to reduce the overhead of the common case of backport a fix to an earlier release where few to no changes are needed.
> 
> Before sending out this PR, I looked for, but did not find, documentation for what procedures 8u wanted to use for a situation like this.

Thanks for the feedback. I can improve the documentation on the 8u wiki to make this clearer. If Skara doesn't recognise the issue as a backport, it doesn't seem to like the referenced bug. Prior to you updating the title, it was issuing a warning that the bug was not open (as we'd expect), so I'm not sure it would correctly resolve it with a backport issue when pushed. Using the "Backport <x>" nomenclature just seems to make things work well in all cases.

Thanks for making the changes. I've approved this for 8u now so it's good to integrate.

**Comment by gnu-andrew** [comment]
Also, it's not necessary for this PR, but you might want to enable GitHub Actions on your 8u fork for any future PRs.

**Comment by jddarcy** [comment]
> > > Change looks good and nearly the same as that in 8u42. However, one copyright header change was missed in `System.c`, presumably due to 8189761 already having bumped it to 2019. Can we fix this please?
> > > Also, please change the title to "Backport 31a63ba5f255e09349b3842984ac5bb3ad8e6c0b" so SKARA correctly identifies this as a backport.
> > 
> > 
> > I've done as you've requested.
> > > See https://wiki.openjdk.org/display/SKARA/Backports
> > 
> > 
> > Yes, I am familiar with the basic operation of Skara. I don't see anything on the referenced page that requires use of a Skara Backport PR when doing a backport. The impetus for adding the backport feature to Skara, a feature enabled several months after JDK mainline switched to Skara, was to reduce the overhead of the common case of backport a fix to an earlier release where few to no changes are needed.
> > Before sending out this PR, I looked for, but did not find, documentation for what procedures 8u wanted to use for a situation like this.
> 
> Thanks for the feedback. I can improve the documentation on the 8u wiki to make this  #clearer. If Skara doesn't recognise the issue as a backport, it doesn't seem to like the referenced bug. Prior to you updating the title, it was issuing a warning that the bug was not open (as we'd expect), so I'm not sure it would correctly resolve it with a backport issue when pushed. Using the `"Backport <x>"` nomenclature just seems to make things work well in all cases.

I also noticed the previous message about "bug not being open" before the PR was changed to a backport. I assume that is a opportunity-for-improvement for the bots to say "we noticed we'll need to create a new backport record if this gets pushed," which the bots should certainly be able to do.

My general advice on using JBS includes "don't create a backport record before it is needed." I didn't try to create an 8-pool record to see if it would making the warning go away since I assumed the right thing would happen on the push with respect to JBS.

**Pull request closed without merging**
