### PR TITLE
8307134: Add GTS root CAs

### PR DESCRIPTION
**Pull request by jerboaa**
Clean backport modulo path changes to match 8u layout. Parity backport for 8u381 Oracle.

Testing:
- [x]  `sun/security/lib/cacerts/VerifyCACerts.java` and `security/infra/java/security/cert/CertPathValidator/certification` passed.
- [x] GHA

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8307134](https://bugs.openjdk.org/browse/JDK-8307134): Add GTS root CAs

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**) ⚠️ Review applies to [8a359dee](https://git.openjdk.org/jdk8u-dev/pull/321/files/8a359deebb9298691041684064f74f42155a856f)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/321/head:pull/321` \
`$ git checkout pull/321`

Update a local copy of the PR: \
`$ git checkout pull/321` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/321/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 321`

View PR using the GUI difftool: \
`$ git pr show -t 321`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/321.diff">https://git.openjdk.org/jdk8u-dev/pull/321.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/321#issuecomment-1562554011)

### CODE REVIEW

**Comment by jerboaa** [comment]
The one GHA failure is unrelated. Seems a flaky test which occasionally fails on 32bit x86.

**Comment by jerboaa** [comment]
The only changes to the 11u version have been to the path to files which are different in 8u. Therefore marking as clean.

/clean

**Review by gnu-andrew — APPROVED** [review]
Confirmed to match https://github.com/openjdk/jdk11u-dev/pull/1892 bar path shuffling. Approved for 8u.

**Pull request closed without merging**
