### PR TITLE
8260380: Upgrade to LittleCMS 2.12

### PR DESCRIPTION
**Pull request by mrserb**
Hi all,

This pull request contains a backport of commit [4caeb39f](https://github.com/openjdk/jdk/commit/4caeb39f01b13b5472d8dacb268262fd418fd0c4) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Phil Race on 10 Feb 2021 and was reviewed by Jayathirth D V and Sergey Bylokhov.

The backport is mostly clean, I had to update the license in `THIRD_PARTY_README` instead of `lcms.md`.
No new issues found by the :jdk_desktop tests.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8260380](https://bugs.openjdk.org/browse/JDK-8260380) needs maintainer approval

### Issue
 * [JDK-8260380](https://bugs.openjdk.org/browse/JDK-8260380): Upgrade to LittleCMS 2.12 (**Bug** - P3 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/563/head:pull/563` \
`$ git checkout pull/563`

Update a local copy of the PR: \
`$ git checkout pull/563` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/563/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 563`

View PR using the GUI difftool: \
`$ git pr show -t 563`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/563.diff">https://git.openjdk.org/jdk8u-dev/pull/563.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/563#issuecomment-2295173751)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Review by gnu-andrew — APPROVED** [review]
Change looks good, with `lcms.md` changes adapted to `THIRD_PARTY_README`.

**Comment by gnu-andrew** [comment]
Approved, but please hold off on integrating until we move to 8u442. I'll post a PR for that shortly. Thanks.

**Pull request closed without merging**
