### PR TITLE
8251551: Use .md filename extension for README

### PR DESCRIPTION
**Pull request by gdams**
Backports https://bugs.openjdk.org/browse/JDK-8251551 as it's a low-risk change and generally improves the readability/usability in GitHub.

Currently, I've just converted the README to markdown format and added a little syntax highlighting. I'm not sure if people would like me to go one step further and rip out the mercurial/nested repo references?

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed (2 reviews required, with at least 2 [Reviewers](https://openjdk.org/bylaws#reviewer))

### Issue
 * [JDK-8251551](https://bugs.openjdk.org/browse/JDK-8251551): Use .md filename extension for README

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/75/head:pull/75` \
`$ git checkout pull/75`

Update a local copy of the PR: \
`$ git checkout pull/75` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/75/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 75`

View PR using the GUI difftool: \
`$ git pr show -t 75`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/75.diff">https://git.openjdk.org/jdk8u-dev/pull/75.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Review by gnu-andrew — CHANGES_REQUESTED** [review]
I think we need to bring in the changes to convert to markdown first (notably [JDK-8139668](https://bugs.openjdk.org/browse/JDK-8139668) and [JDK-8176509](https://bugs.openjdk.org/browse/JDK-8176509)) before doing this. 

Also, this patch looks to be removing the old file and adding a new one, when it should be a rename. That makes it hard to see what has actually changed.

**Comment by gdams** [comment]
> I think we need to bring in the changes to convert to markdown first (notably [JDK-8139668](https://bugs.openjdk.org/browse/JDK-8139668) and [JDK-8176509](https://bugs.openjdk.org/browse/JDK-8176509)) before doing this.

I hadn't seen those patches before, are they not focussed on the [README-builds.html](http://hg.openjdk.java.net/jdk8/jdk8/raw-file/tip/README-builds.html) file rather than the top-level `README` file? I'm not sure why one would block the other.

> Also, this patch looks to be removing the old file and adding a new one, when it should be a rename. That makes it hard to see what has actually changed.

That's the way the patch was applied from the top (see the original [commit](https://github.com/openjdk/jdk/commit/6ed221cb9ad2e81d92dda0ef32095dda5d52cb85)). I wouldn't like to change that now as it would be inconsistent with the other repos?

**Comment by gnu-andrew** [comment]
> > I think we need to bring in the changes to convert to markdown first (notably [JDK-8139668](https://bugs.openjdk.org/browse/JDK-8139668) and [JDK-8176509](https://bugs.openjdk.org/browse/JDK-8176509)) before doing this.
> 
> I hadn't seen those patches before, are they not focussed on the [README-builds.html](http://hg.openjdk.java.net/jdk8/jdk8/raw-file/tip/README-builds.html) file rather than the top-level `README` file? I'm not sure why one would block the other.
> 

8176509 also updates README and would essentially making this patch a clean backport as far as I can see. If we apply this change first as it is, we'll introduce changes unique to 8u into the README file.

> > Also, this patch looks to be removing the old file and adding a new one, when it should be a rename. That makes it hard to see what has actually changed.
> 
> That's the way the patch was applied from the top (see the original [commit](https://github.com/openjdk/jdk/commit/6ed221cb9ad2e81d92dda0ef32095dda5d52cb85)). I wouldn't like to change that now as it would be inconsistent with the other repos?

Ugh, I see. Well, we're already inconsistent with other repos with this patch, because the file being changed is quite different. Not having this as a rename makes it hard to see what changes have been made other than the rename.

I can accept the patch as it is in trunk and 11u if we're doing the same change on top of JDK-8176509. If we're going to do unique 8u changes, we should do the rename properly.

**Comment by gnu-andrew** [comment]
I've opened #79 for the first of these. Once both are in, you should be able to just do this change cleanly.

**Comment by gdams** [comment]
Adding a comment to prevent this from closing. @gnu-andrew is your other patch ready yet?

**Comment by gnu-andrew** [comment]
Still waiting on a review of my patch, sorry. It'd be good if someone could review it so we can start to move this forward.

**Comment by phohensee** [comment]
Andrew, I reviewed https://github.com/openjdk/jdk8u-dev/pull/79.

**Pull request closed without merging**
