### PR TITLE
8290832: It is no longer possible to change "user.dir" in the JDK8

### PR DESCRIPTION
**Pull request by mrserb**
This is the request to revert the fix for [JDK-8194154](https://bugs.openjdk.org/browse/JDK-8194154) integrated to the [openjdk8u342](https://github.com/openjdk/jdk8u/commit/5fcfb7acbe340c8347bd47413a36dd0b1e267dc1)

The fix for [JDK-8194154](https://bugs.openjdk.org/browse/JDK-8194154) disabled the possibility to change the "user.dir" property.
Changing the "user.dir" was not recommended from the beginning but it was not forbidden, so there are some old applications that rely on the old behavior. 

For compatibility reasons, it would be good to restore the old behavior.

Note that the test is simplified and saved under a different name, now it will check just the possibility to change the 'user.dir' using a simple path and name.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8290832](https://bugs.openjdk.org/browse/JDK-8290832): It is no longer possible to change "user.dir" in the JDK8

### Reviewers
 * [Christoph Langer](https://openjdk.org/census#clanger) (@RealCLanger - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/88/head:pull/88` \
`$ git checkout pull/88`

Update a local copy of the PR: \
`$ git checkout pull/88` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/88/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 88`

View PR using the GUI difftool: \
`$ git pr show -t 88`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/88.diff">https://git.openjdk.org/jdk8u-dev/pull/88.diff</a>

</details>

### CODE REVIEW

**Comment by dsamersoff** [comment]
Looks good to me.

**Review by RealCLanger — COMMENTED** [review]
The change itself looks good. But wouldn't it be better to do a clean backout of [JDK-8194154](https://bugs.openjdk.org/browse/JDK-8194154) and then add the test that user.dir can be changed in JDK8 with a different issue?

Or would it at least be possible that the test is not shown as renamed but rather as a deletion of the old test and the addition of a new test? (Not sure whether that's something that git did automatically or whether you can change this)

**Comment by mrserb** [comment]
> Or would it at least be possible that the test is not shown as renamed but rather as a deletion of the old test and the addition of a new test? (Not sure whether that's something that git did automatically or whether you can change this)

It is actually a deletion in one commit and adding a new test by another, it is how the github shows it, but I can split it by different commits.

**Comment by mrserb** [comment]
The patch is updated as requested, the test will be pushed separately.

**Review by RealCLanger — APPROVED** [review]
LGTM. You might consider renaming the JBS issue to something like "Backout JDK-8194154..." But I leave that to your or the 8u maintainers.

**Comment by gnu-andrew** [comment]
Thanks for catching this @mrserb and the patch itself looks like a clean backout to me.

However, I suggest we do this on https://github.com/openjdk/jdk8u for an interim 8u345 release.  I've just requested that version from ops and will update the jcheck rules on 8u when that is created.

Presumably we'll do the test under a different bug?

**Comment by mrserb** [comment]
> However, I suggest we do this on https://github.com/openjdk/jdk8u for an interim 8u345 release. I've just requested that version from ops and will update the jcheck rules on 8u when that is created.

Ok, I'll prepare the patch for that repo.

> Presumably we'll do the test under a different bug?

Yes, I'll add the test in a separate CR, so this patch will be as simple as "git revert"..

**Pull request closed without merging**
