### PR TITLE
8155590: Dubious collection management in sun.net.www.http.KeepAliveCache

### PR DESCRIPTION
**Pull request by dhanalla**
Issue:  [JDK-8155590](https://bugs.openjdk.org/browse/JDK-8155590) Dubious collection management in sun.net.www.http.KeepAliveCache

Backport 2e31cc7ee1b875af7c7b3a5367ac8056fbc60650

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8155590](https://bugs.openjdk.org/browse/JDK-8155590) needs maintainer approval

### Issue
 * [JDK-8155590](https://bugs.openjdk.org/browse/JDK-8155590): Dubious collection management in sun.net.www.http.KeepAliveCache (**Bug** - P4 - Approved)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/407/head:pull/407` \
`$ git checkout pull/407`

Update a local copy of the PR: \
`$ git checkout pull/407` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/407/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 407`

View PR using the GUI difftool: \
`$ git pr show -t 407`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/407.diff">https://git.openjdk.org/jdk8u-dev/pull/407.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/407#issuecomment-1858471616)

### CODE REVIEW

**Comment by jerboaa** [comment]
@dhanalla Please use `Backport 2e31cc7ee1b875af7c7b3a5367ac8056fbc60650` as the PR title so that the patch gets properly recognized as a backport.

**Comment by dhanalla** [comment]
> @dhanalla Please use `Backport 2e31cc7ee1b875af7c7b3a5367ac8056fbc60650` as the PR title so that the patch gets properly recognized as a backport.

Done, Thanks @jerboaa for reviewing this PR.

**Review by jerboaa — APPROVED** [review]
This patch seems fine to me.

**Comment by dhanalla** [comment]
> This patch seems fine to me.

Thanks @jerboaa for reviewing this PR.
Can you please review the main PR https://github.com/openjdk/jdk8u-dev/pull/409 that depends on this one.

**Comment by dhanalla** [comment]
/approval request Backport of bug [JDK-8155590] Dubious collection management in sun.net.www.http.KeepAliveCache

**Comment by jerboaa** [comment]
> /approval request Backport of bug [JDK-8155590] Dubious collection management in sun.net.www.http.KeepAliveCache

@dhanalla Fix request comments should be more than stating the obvious, please. See: https://openjdk.org/projects/jdk-updates/approval.html Mention the testing you've done and the risk you estimate for getting this integrated.

**Comment by dhanalla** [comment]
> > /approval request Backport of bug [JDK-8155590] Dubious collection management in sun.net.www.http.KeepAliveCache
> 
> @dhanalla Fix request comments should be more than stating the obvious, please. See: https://openjdk.org/projects/jdk-updates/approval.html Mention the testing you've done and the risk you estimate for getting this integrated.

Thanks @jerboaa , Updated the bug with a comment requesting the fix.

**Pull request closed without merging**
