### PR TITLE
8282398: EndingDotHostname.java test fails because SSL cert expired

### PR DESCRIPTION
**Pull request by wkia**
Almost clean backport. Test files changed only.

There were 2 changes with test files paths:

- Original `test/jdk/javax/net/ssl/ServerName/EndingDotHostname.java` path changed to `jdk/test/javax/net/ssl/ServerName/EndingDotHostname.java`.
- Original `test/jdk/javax/net/ssl/templates/SSLExampleCert.java` path changed to `jdk/test/javax/net/ssl/templates/SSLExampleCert.java`.

The original changes use JDK17 strings in SSLExampleCert.java, so it was adapted for JDK8 with the additional commit as it was done for JDK11 backport.

Please note that this PR is a part of dependant PR chain

- Prev PR #205 
- Next PR #207

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8282398](https://bugs.openjdk.org/browse/JDK-8282398): EndingDotHostname.java test fails because SSL cert expired

### Reviewers
 * [Yuri Nesterenko](https://openjdk.org/census#yan) (@yan-too - **Reviewer**) ⚠️ Review applies to [b86ea4cf](https://git.openjdk.org/jdk8u-dev/pull/206/files/b86ea4cf34e6643f1b52bce5f2cf31c80db57d79)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**) ⚠️ Review applies to [b86ea4cf](https://git.openjdk.org/jdk8u-dev/pull/206/files/b86ea4cf34e6643f1b52bce5f2cf31c80db57d79)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/206/head:pull/206` \
`$ git checkout pull/206`

Update a local copy of the PR: \
`$ git checkout pull/206` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/206/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 206`

View PR using the GUI difftool: \
`$ git pr show -t 206`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/206.diff">https://git.openjdk.org/jdk8u-dev/pull/206.diff</a>

</details>

### CODE REVIEW

**Review by gnu-andrew — APPROVED** [review]
Clean backport, necessary bug fix after integrating #205

**Comment by gnu-andrew** [comment]
Bug has `jdk8u-fix-yes` approval so this can be integrated once the dependent PR is integrated.

**Comment by wkia** [comment]
The original changes use JDK17 strings in SSLExampleCert.java, so it was adapted for JDK8 with the additional commit as it was done for JDK11 backport.

Force-pushed to keep the commit history clean to make reviewing easier.

**Comment by wkia** [comment]
The original changes use JDK17 strings in SSLExampleCert.java, so it was adapted for JDK8 with the additional commit as it was done for JDK11 backport.

Force-pushed to keep the commit history clean to make reviewing easier.

**Comment by phohensee** [comment]
Pre-submit test failures look like an infrastructure issue. @wkia, the backport has been approved, so if you add a "/integrate" comment, I or another committer can sponsor it.

**Comment by phohensee** [comment]
@wkia, please use "/integrate".

**Pull request closed without merging**
