### PR TITLE
8293828: JFR: jfr/event/oldobject/TestClassLoaderLeak.java still fails when GC cycles are not happening

### PR DESCRIPTION
**Pull request by Rudometov**
Backport for JDK-8293828

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8293828](https://bugs.openjdk.org/browse/JDK-8293828): JFR: jfr/event/oldobject/TestClassLoaderLeak.java still fails when GC cycles are not happening

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [62e6cf5f](https://git.openjdk.org/jdk8u-dev/pull/122/files/62e6cf5f97125b090691d2ac94a91073eba13f50)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/122/head:pull/122` \
`$ git checkout pull/122`

Update a local copy of the PR: \
`$ git checkout pull/122` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/122/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 122`

View PR using the GUI difftool: \
`$ git pr show -t 122`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/122.diff">https://git.openjdk.org/jdk8u-dev/pull/122.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by Rudometov** [comment]
> Can this change be rebased on top of https://github.com/openjdk/jdk8u-dev/pull/120/files?

@caojoshua, sure, I'll wait for 120 to go first.

**Pull request closed without merging**
