### PR TITLE
8291637: HttpClient default keep alive timeout not followed if server sends invalid value

### PR DESCRIPTION
**Pull request by dhanalla**
Backport b17a745d7f55941f02b0bdde83866aa5d32cce07

Clean backport from JDK11u patch.

Test performed:
1. JTreg jdk_tier1, hotspot_tier1
2. JTreg jdk_tier2
3. The backported test case in this PR passed after applying this patch.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8291637](https://bugs.openjdk.org/browse/JDK-8291637) needs maintainer approval

### Issue
 * [JDK-8291637](https://bugs.openjdk.org/browse/JDK-8291637): HttpClient default keep alive timeout not followed if server sends invalid value (**Bug** - P3 - Approved)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/466/head:pull/466` \
`$ git checkout pull/466`

Update a local copy of the PR: \
`$ git checkout pull/466` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/466/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 466`

View PR using the GUI difftool: \
`$ git pr show -t 466`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/466.diff">https://git.openjdk.org/jdk8u-dev/pull/466.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/466#issuecomment-1977233851)

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
LGTM.

**Comment by jerboaa** [comment]
GHA failures are https://bugs.openjdk.org/browse/JDK-8324583

**Comment by dhanalla** [comment]
> LGTM.
Thank you for reviewing this PR @jerboaa. I have submitted a bug approval request.

**Pull request closed without merging**
