### PR TITLE
8254318: Remove .hgtags

### PR DESCRIPTION
**Pull request by gdams**
Removes unused .hgtags files after the Git move. No code change. Low risk

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8254318](https://bugs.openjdk.org/browse/JDK-8254318): Remove .hgtags

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/108/head:pull/108` \
`$ git checkout pull/108`

Update a local copy of the PR: \
`$ git checkout pull/108` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/108/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 108`

View PR using the GUI difftool: \
`$ git pr show -t 108`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/108.diff">https://git.openjdk.org/jdk8u-dev/pull/108.diff</a>

</details>

### CODE REVIEW

**Review by gnu-andrew — APPROVED** [review]
Looks good to me. Are you able to add `jdk8u-fix-request` now? I see an authorship status: https://openjdk.org/census#gdams If not, i can do so (and approve at the same time)

**Comment by gdams** [comment]
> Looks good to me. Are you able to add jdk8u-fix-request now? I see an authorship status: https://openjdk.org/census#gdams If not, i can do so (and approve at the same time)

@gnu-andrew added the fix request

**Pull request closed without merging**
