### PR TITLE
8291226: Create Test Cases to cover scenarios for JDK-8278067

### PR DESCRIPTION
**Pull request by dhanalla**
Backport-of: 86ec158dfb7a770fe9a74ff8617bac938d0bb90f

Clean backport from JDK11u patch.

Test performed:

1. JTreg jdk_tier1, hotspot_tier1
2. JTreg jdk_tier2
3. The backported test case in this PR passed.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8291226](https://bugs.openjdk.org/browse/JDK-8291226) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8291226](https://bugs.openjdk.org/browse/JDK-8291226): Create Test Cases to cover scenarios for JDK-8278067 (**Bug** - P3 - Approved)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/453/head:pull/453` \
`$ git checkout pull/453`

Update a local copy of the PR: \
`$ git checkout pull/453` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/453/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 453`

View PR using the GUI difftool: \
`$ git pr show -t 453`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/453.diff">https://git.openjdk.org/jdk8u-dev/pull/453.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/453#issuecomment-1957833579)

### CODE REVIEW

**Comment by jerboaa** [comment]
Did you run the tests? If yes, what was the result?

**Comment by dhanalla** [comment]
> Did you run the tests? If yes, what was the result?
This test passes only with the other PR #454 which is depending on this PR . 
JTreg tests jdk_tier1, hotspot_tier1 passed with this PR & #454.

Thanks @jerboaa for reviewing this PR.

**Review by jerboaa — APPROVED** [review]
LGTM.

**Comment by dhanalla** [comment]
> LGTM.
Thanks @jerboaa for reviewing this PR. I've added a JDK8 patch request to the bug as the next step.

**Pull request closed without merging**
