### PR TITLE
8196770: Add JNDI test com/sun/jndi/ldap/blits/AddTests/AddNewEntry.java

### PR DESCRIPTION
**Pull request by mrserb**
Hi all,

This pull request contains a backport of commit https://github.com/openjdk/jdk/commit/bc690b263b577c2f5b88c0c9932dacbd87b3d26d from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The patch is not clean, the following changes were applied.
 - The next tags are updated/deleted: `@library`, `@run` and `@modules`.
 - The LDAPServer.java was initially added by the "8142968: Module System implementation" in jdk 9, so I picked up only that file in this patch since it is the first usage of LDAPServer in 8u.
Note:
In jdk 9 it is located in the: test/jdk/javax/naming/module/src/test/test/LDAPServer.java
In jdk 8 it is added into the: jdk/test/com/sun/jndi/ldap/lib/LDAPServer.java

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8196770](https://bugs.openjdk.org/browse/JDK-8196770) needs maintainer approval

### Issue
 * [JDK-8196770](https://bugs.openjdk.org/browse/JDK-8196770): Add JNDI test com/sun/jndi/ldap/blits/AddTests/AddNewEntry.java (**Enhancement** - P3 - Approved)

### Reviewers
 * [Yuri Nesterenko](https://openjdk.org/census#yan) (@yan-too - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/583/head:pull/583` \
`$ git checkout pull/583`

Update a local copy of the PR: \
`$ git checkout pull/583` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/583/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 583`

View PR using the GUI difftool: \
`$ git pr show -t 583`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/583.diff">https://git.openjdk.org/jdk8u-dev/pull/583.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/583#issuecomment-2378836497)

### CODE REVIEW

**Review by yan-too — APPROVED** [review]
A T1 test failure seems unrelated

**Review by gnu-andrew — APPROVED** [review]
Backport looks good and I agree with just adding `LDAPServer.java` here

Was there a reason `AddNewEntry.java` needed to be `othervm` on 8u when it wasn't on 11u?

**Comment by mrserb** [comment]
> Was there a reason `AddNewEntry.java` needed to be `othervm` on 8u when it wasn't on 11u?

The tag was changed by the https://bugs.openjdk.org/browse/JDK-8198931 at the time the "Java EE" has been removed from JDK 11.

**Comment by gnu-andrew** [comment]
> > Was there a reason `AddNewEntry.java` needed to be `othervm` on 8u when it wasn't on 11u?
> 
> The tag was changed by the https://bugs.openjdk.org/browse/JDK-8198931 at the time the "Java EE" has been removed from JDK 11.

Good catch. Thanks for including it in this backport.

**Pull request closed without merging**
