### PR TITLE
8251188: Update LDAP tests not to use wildcard addresses

### PR DESCRIPTION
**Pull request by mrserb**
Hi all,

This pull request contains a backport of commit [a75edc29](https://github.com/openjdk/jdk/commit/a75edc29c6ce41116cc99530aa1710efb62c6d5a) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Aleksei Efimov on 25 Sep 2020 and was reviewed by Daniel Fuchs.

The patch is not clean:
 - The change in ProblemList.txt was dropped, since the test is not present there.
 - The `@library` tag is changed from `@library /test/lib` to `@library /lib/testlibrary`.
 - `@modules` tags were deleted.
 - The usages of `var` were replaced by the actual types.
 - Some context is different since the next cleanup was not backported to the 8u:  https://github.com/openjdk/jdk/commit/aba017fa70011d7fa14de07d4c9db1932eeff0f9

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8251188](https://bugs.openjdk.org/browse/JDK-8251188) needs maintainer approval

### Issue
 * [JDK-8251188](https://bugs.openjdk.org/browse/JDK-8251188): Update LDAP tests not to use wildcard addresses (**Bug** - P4 - Approved)

### Reviewers
 * [Yuri Nesterenko](https://openjdk.org/census#yan) (@yan-too - **Reviewer**)
 * [Martin Balao](https://openjdk.org/census#mbalao) (@martinuy - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/585/head:pull/585` \
`$ git checkout pull/585`

Update a local copy of the PR: \
`$ git checkout pull/585` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/585/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 585`

View PR using the GUI difftool: \
`$ git pr show -t 585`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/585.diff">https://git.openjdk.org/jdk8u-dev/pull/585.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/585#issuecomment-2383894329)

### CODE REVIEW

**Review by yan-too — APPROVED** [review]

**Review by martinuy — APPROVED** [review]
Looks good to me. I observed no regressions in jdk/com/sun/jndi/ldap.

**Review by gnu-andrew — APPROVED** [review]
Changes look good to me. We certainly shouldn't be backporting a cleanup change like [JDK-8214694](https://bugs.openjdk.org/browse/JDK-8214694).

**Pull request closed without merging**
