### PR TITLE
8315731: Open source several Swing Text related tests

### PR DESCRIPTION
**Pull request by mrserb**
Hi all,

This pull request contains a backport of commit [0dc17ca0](https://github.com/openjdk/jdk11u-dev/commit/0dc17ca068b837606252e1db614fd005a2f2b942) from the [openjdk/jdk11u-dev](https://git.openjdk.org/jdk11u-dev) repository.

The commit being backported was authored by Jonathan Dowland on 5 Feb 2024 and was reviewed by Sergey Bylokhov.

Thanks!

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8315731](https://bugs.openjdk.org/browse/JDK-8315731) needs maintainer approval

### Issue
 * [JDK-8315731](https://bugs.openjdk.org/browse/JDK-8315731): Open source several Swing Text related tests (**Bug** - P4 - Approved)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/516/head:pull/516` \
`$ git checkout pull/516`

Update a local copy of the PR: \
`$ git checkout pull/516` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/516/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 516`

View PR using the GUI difftool: \
`$ git pr show -t 516`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/516.diff">https://git.openjdk.org/jdk8u-dev/pull/516.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/516#issuecomment-2157081496)

### CODE REVIEW

**Comment by mrserb** [comment]
/clean the fix is identical to openjdk/jdk11u-dev

**Comment by mrserb** [comment]
keep open

**Comment by mrserb** [comment]
keep open

**Review by gnu-andrew — COMMENTED** [review]
This looks clean but then it is just introducing new files.

Can you confirm these tests all build, run and pass on 8u?

**Comment by phohensee** [comment]
GHA failures are unrelated cert issues, or unrelated (in the case of linux-x86) GC test failures.

**Comment by gnu-andrew** [comment]
> GHA failures are unrelated cert issues, or unrelated (in the case of linux-x86) GC test failures. The new tests pass on my Intel Mac laptop.

Thanks for confirming the new tests pass, as they won't be covered by the GHA tiers.
As to the failing GHA tests, I agree these are unrelated and we should consider excluding the failing ones.

**Comment by gnu-andrew** [comment]
Approving now but please wait for 8u442 to open before committing (see #572)
/approve yes

**Comment by gnu-andrew** [comment]
> Approving now but please wait for 8u442 to open before committing (see #572) /approve yes

Good to go now.

**Pull request closed without merging**
