### PR TITLE
8263404: RsaPrivateKeySpec is always recognized as RSAPrivateCrtKeySpec in RSAKeyFactory.engineGetKeySpec

### PR DESCRIPTION
**Pull request by phohensee**
Backport for Oracle parity from 11u is almost clean.

1. PKCS11Test.java	is unchanged because 8u does not throw a RuntimeException for an unknown command.
2. In TestP11KeyFactoryGetRSAKeySpec.java, /test/lib is unneeded in the @library comment, and the @module comment was deleted.

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8263404](https://bugs.openjdk.org/browse/JDK-8263404): RsaPrivateKeySpec is always recognized as RSAPrivateCrtKeySpec in RSAKeyFactory.engineGetKeySpec

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/214/head:pull/214` \
`$ git checkout pull/214`

Update a local copy of the PR: \
`$ git checkout pull/214` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/214/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 214`

View PR using the GUI difftool: \
`$ git pr show -t 214`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/214.diff">https://git.openjdk.org/jdk8u-dev/pull/214.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/214#issuecomment-1355451248)

### CODE REVIEW

**Review by gnu-andrew — COMMENTED** [review]
Changes mostly look ok, but will need a rebase before push.

Is there a reason the `*_SHA3_*` definitions have been removed from `p11-nss-sensitive.txt`? Those should be defined, having been added by JDK-8244154

**Comment by mrserb** [comment]
@gnu-andrew @phohensee this fix should be merged into the upcoming openjdk8u382

**Comment by mrserb** [comment]
this PR is for /8u-dev, we probably need to recreate it for /8u

**Comment by phohensee** [comment]
This PR was incorrectly based on the original JDK 17 commit rather than the 11u backport. Closing.

**Pull request closed without merging**
