### PR TITLE
8185736: missing default exception handler in calls to rethrow_Stub

### PR DESCRIPTION
**Pull request by dongbohe**
Hi,

I would like to backport this patch to fix missing of default exception handler in catch table produced by C2.
Patch apply cleanly, worked correctly after patch.

Testing:  Performed hotspot jtreg test on linux x86-64 platforms with  -XX:-TieredCompilation -Xcomp options.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8185736](https://bugs.openjdk.org/browse/JDK-8185736): missing default exception handler in calls to rethrow_Stub

### Reviewers
 * [Roland Westrelin](https://openjdk.org/census#roland) (@rwestrel - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/231/head:pull/231` \
`$ git checkout pull/231`

Update a local copy of the PR: \
`$ git checkout pull/231` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/231/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 231`

View PR using the GUI difftool: \
`$ git pr show -t 231`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/231.diff">https://git.openjdk.org/jdk8u-dev/pull/231.diff</a>

</details>

### CODE REVIEW

**Comment by jerboaa** [comment]
@rwestrel Could you please take a look at this backport? Is this safe to approve in your opinion?

**Comment by dongbohe** [comment]
This crash can always be reproduced in our environment, and worked correctly after patch. Unfortunately, it is difficult to extract a simple test case.

**Review by rwestrel — APPROVED** [review]
Looks reasonable to me.

**Comment by dongbohe** [comment]
Thank you for your review, Roland.

**Comment by dongbohe** [comment]
It seems that the failed tests in the pre-test were not caused by this PR and I couldn't reproduce this in my environment.
It appears to be a random cms crash, I created JDK-8303159 to track this issue.

**Comment by dongbohe** [comment]
Got the jdk8u-fix-yes.
/integrate

**Pull request closed without merging**
