### PR TITLE
Backport  ad5488458e7ed590802d739250ce954295a74a75

### PR DESCRIPTION
**Pull request by psawant19**
---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] Commit message must refer to an issue

### Error
&nbsp;⚠️ OCA signatory status must be verified

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/472/head:pull/472` \
`$ git checkout pull/472`

Update a local copy of the PR: \
`$ git checkout pull/472` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/472/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 472`

View PR using the GUI difftool: \
`$ git pr show -t 472`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/472.diff">https://git.openjdk.org/jdk8u-dev/pull/472.diff</a>

</details>

### CODE REVIEW

**Comment by psawant19** [comment]
This contribution is on behalf of my employer, IBM, which is a corporate OCA signatory.

**Comment by zzambers** [comment]
@psawant19 Not related to OCA, but this seems like unfinished backport. There are some unresolved merge conflicts in your changeset:
```
<<<<<<< HEAD:jdk/test/sun/nio/cs/TestIBMBugs.java
...
=======
...
>>>>>>> ad5488458e7 (8235834: IBM-943 charset encoder needs updating):test/jdk/sun/nio/cs/TestIBMBugs.java
```

**Comment by psawant19** [comment]
Hi [zzambers](https://github.com/zzambers) 
Could you please review these changes?

**Pull request closed without merging**
