### PR TITLE
8315506: C99 compatibility issue in LinuxNativeDispatcher

### PR DESCRIPTION
**Pull request by fweimer-rh**
The `Java_sun_nio_fs_LinuxNativeDispatcher_getlinelen` function calls the `free` function without including `<stdlib.h>`. This results in an implicit function declarations, and some compilers no longer support that by default, leading to a build failure.

Per the comment in the file, this function was introduced in the backport from jdk11, so this bug is specific to jdk8u.

Patch originally submitted by @djdelorie as openjdk/jdk8u#42.

Related to:

* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8315506](https://bugs.openjdk.org/browse/JDK-8315506): C99 compatibility issue in LinuxNativeDispatcher (**Bug** - P4)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Contributors
 * DJ Delorie `<dj@redhat.com>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/362/head:pull/362` \
`$ git checkout pull/362`

Update a local copy of the PR: \
`$ git checkout pull/362` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/362/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 362`

View PR using the GUI difftool: \
`$ git pr show -t 362`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/362.diff">https://git.openjdk.org/jdk8u-dev/pull/362.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/362#issuecomment-1702531052)

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
LGTM.

**Comment by jerboaa** [comment]
For the future please enable GHA on your fork! Thanks.

**Comment by jerboaa** [comment]
> > For the future please enable GHA on your fork! Thanks.
> 
> Already done.

Could you please trigger test runs for this? I don't see them. Also, please don't integrate without approval on the bug.

**Review by gnu-andrew — APPROVED** [review]
The function that introduces the `free` was added in `UnixNativeDispatcher.c` on 11u, which had a `stdlib.h` import since creation. As mentioned on the bug report, it was moved to `LinuxNativeDispatcher.c` in the backport of [JDK-8229872](https://bugs.openjdk.org/browse/JDK-8229872) to 8u, so this is 8u-specific.

Patch looks ok for 8u. Please run the GHA tests and then add `jdk8u-fix-request` to the bug, with a note on why this should be included.

**Comment by gnu-andrew** [comment]
Out of interest, what flags are you building with to make this a build failure? I've not seen that when building 8u. I don't believe this code is built with `-Werror` by default.

**Comment by gnu-andrew** [comment]
> > Out of interest, what flags are you building with to make this a build failure? I've not seen that when building 8u. I don't believe this code is built with `-Werror` by default.
> 
> @gnu-andrew This was originally detected with an instrumented compilers that treats such issues errors, and logs them so that build scripts have a hard time suppressing errors (relevant to configure scripts).
> 

Ah, that explains why I haven't seen it. I have built with some newer GCCs and even have a PR in flight to get GCC 11 working (https://github.com/openjdk/jdk8u-dev/pull/357 - still  need to work out why that is failing on cross-compile)

> Current Clang defaults `-Werror=implict-function-declaration`, so no special build flags are necessary there to trigger this issue (but I haven't tried building OpenJDK with Clang). For quite some time, expected GCC 14 to something like this as well, but I'm not sure if things will work out.
> 

I think later JDK versions should support Clang, but probably not 8u. I did have backporting support on a long TODO list at one point, but it's probably not worth it at this stage. That said, the situation might be better due to the MacOS support that's been added since, making Linux Clang support less problematic.

If we did support it, we'd probably need to add a build-only run with Clang to GHA.

> Speaking of flags, I plan to add `-Werror=implict-function-declaration -Werror=implicit-int` to the default flags in Fedora. Should I backport this change proactively to the `java-1.8.0-openjdk-portable`?

Do you mean this change or the additional flags? I thought this change was already in there.

There is a `-Wno-error` added in the Fedora build which I expect may cancel this out even if the flags you suggest are added. `-Werror=implicit-function-declaration` is certainly a useful one to have and one I ran with myself locally for a while. But fixing stuff like that in a JDK as old as 8u might be problematic and I'd certainly start with `java-21-openjdk` first.

**Comment by jerboaa** [comment]
Thanks for the test run trigger. I'll sponsor.

**Pull request closed without merging**
