### PR TITLE
8235218: Minimal VM is broken after JDK-8173361

### PR DESCRIPTION
**Pull request by dongbohe**
Hi,

I would like to backport this as follow up of [JDK-8173361](https://bugs.openjdk.java.net/browse/JDK-8173361), only a different context.

Thanks,
hedongbo

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8235218](https://bugs.openjdk.org/browse/JDK-8235218): Minimal VM is broken after JDK-8173361

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/19/head:pull/19` \
`$ git checkout pull/19`

Update a local copy of the PR: \
`$ git checkout pull/19` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/19/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 19`

View PR using the GUI difftool: \
`$ git pr show -t 19`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/19.diff">https://git.openjdk.org/jdk8u-dev/pull/19.diff</a>

</details>

### CODE REVIEW

**Comment by dongbohe** [comment]
According to the description of [New Skara feature: dependent pull requests](https://mail.openjdk.org/pipermail/jdk-dev/2021-March/005232.html), we need to target to pr/9.

It seems that I need to merge master, I will try.

**Comment by dongbohe** [comment]
It looks ok.

**Comment by dongbohe** [comment]
@gnu-andrew Hi, Andrew. Could you please take another look?

**Review by jerboaa — APPROVED** [review]
Looks OK.

**Comment by dongbohe** [comment]
Got the push approval.
/integrate

**Comment by gnu-andrew** [comment]
> According to the description of [New Skara feature: dependent pull requests](https://mail.openjdk.org/pipermail/jdk-dev/2021-March/005232.html), we need to target to pr/9.
> 
> It seems that I need to merge master, I will try.

Ah ok, that's the first I've heard of that. It seems the mail was only sent to jdk-dev and not the jdk-updates or jdk8u lists.

**Review by gnu-andrew — APPROVED** [review]
Backport itself looks clean.

**Pull request closed without merging**
