### PR TITLE
8286582: Build fails on macos aarch64 when using --with-zlib=bundled

### PR DESCRIPTION
**Pull request by mrserb**
Hi all,
This pull request contains a backport of commit [50d47de8](https://github.com/openjdk/jdk/commit/50d47de8358e2f22bf3a4a165d660c25ef6eacbc) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.
The commit being backported was authored by Jaikiran Pai on 12 May 2022 and was reviewed by Magnus Ihse Bursie and Lance Andersen.

The patch for JDK8 is slightly different:
 * The main code patch is moved from the `make/autoconf/lib-bundled.m4` to the `jdk/make/lib/CoreLibraries.gmk` the same place where `":= -lz"` option is set.
 * All disabled warnings are removed from the patch, seems we do not have such DISABLED_WARNINGS_XX in JDK8

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8286582](https://bugs.openjdk.org/browse/JDK-8286582): Build fails on macos aarch64 when using --with-zlib=bundled

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [5b2db66e](https://git.openjdk.org/jdk8u-dev/pull/80/files/5b2db66ec9efb7543bf364a708004617398549d5)
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/80/head:pull/80` \
`$ git checkout pull/80`

Update a local copy of the PR: \
`$ git checkout pull/80` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/80/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 80`

View PR using the GUI difftool: \
`$ git pr show -t 80`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/80.diff">https://git.openjdk.org/jdk8u-dev/pull/80.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by jerboaa** [comment]
@mrserb This is not being recognized as a backport. Please fix that.

**Review by gnu-andrew — COMMENTED** [review]
Change itself looks ok, but title needs to be changed to "Backport 8363d9db801314f13e708db62993da5b73634f69" for the backport to be correctly identified.

Please reopen and fix this.

**Comment by mrserb** [comment]
@gnu-andrew please take a look, PR is update to have a backport label.

**Review by jerboaa — APPROVED** [review]
Looks OK.

**Pull request closed without merging**
