### PR TITLE
8305815: Update Libpng to 1.6.39

### PR DESCRIPTION
**Pull request by martinuy**
Hi all,

This pull request contains a backport of commit [c1f759e9d01d646eac69442452151b0467eab306](https://github.com/openjdk/jdk11u-dev/commit/c1f759e9d01d646eac69442452151b0467eab306) from the [openjdk/jdk11u-dev](https://github.com/openjdk/jdk11u-dev) repository.

This backport is a follow up fix of [JDK-8295685](https://bugs.openjdk.org/browse/JDK-8295685).

This backport applied cleanly, except for the changes to the THIRD_PARTY_README files that are specific to 8u.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305815](https://bugs.openjdk.org/browse/JDK-8305815): Update Libpng to 1.6.39 (**Bug** - P3)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/373/head:pull/373` \
`$ git checkout pull/373`

Update a local copy of the PR: \
`$ git checkout pull/373` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/373/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 373`

View PR using the GUI difftool: \
`$ git pr show -t 373`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/373.diff">https://git.openjdk.org/jdk8u-dev/pull/373.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/373#issuecomment-1720135820)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by martinuy** [comment]
Thanks @phohensee for your review. I had to rebase after https://github.com/openjdk/jdk8u-dev/pull/372/commits/3fa3cfaf04acf444b55957fec1e82f8994360e57 in PR 372. Nothing was changed as part of this.

**Review by phohensee — APPROVED** [review]
The GHA failure looks unrelated to me, but please check it out.

**Comment by martinuy** [comment]
The macOS x64 failure (build release) shown in the GHA looks unrelated to me as it happened while compiling hotspot. This backport is not related in any meaningful way to hotspot code.

**Comment by phohensee** [comment]
Then you're good to go. I saw the same failure on a few other PRs.

**Review by gnu-andrew — APPROVED** [review]
Looks good. Approved for 8u.

**Pull request closed without merging**
