### PR TITLE
8278067: Make HttpURLConnection default keep alive timeout configurable

### PR DESCRIPTION
**Pull request by dhanalla**
The JDK11 patch didn't apply cleanly 1/4 hunks needed to be port manually.

Test performed and passed:

1. JTreg jdk_tier1, hotspot_tier1
2. Testcase attached this PR

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Change requires CSR request [JDK-8326435](https://bugs.openjdk.org/browse/JDK-8326435) to be approved
- [x] Commit message must refer to an issue
- [x] [JDK-8278067](https://bugs.openjdk.org/browse/JDK-8278067) needs maintainer approval

### Issues
 * [JDK-8278067](https://bugs.openjdk.org/browse/JDK-8278067): Make HttpURLConnection default keep alive timeout configurable (**Enhancement** - P4 - Approved)
 * [JDK-8326435](https://bugs.openjdk.org/browse/JDK-8326435): Make HttpURLConnection default keep alive timeout configurable (**CSR**)

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**) ⚠️ Review applies to [a78d9dc2](https://git.openjdk.org/jdk8u-dev/pull/437/files/a78d9dc26f590069a0dd1e5e0de5cab849403ac6)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/437/head:pull/437` \
`$ git checkout pull/437`

Update a local copy of the PR: \
`$ git checkout pull/437` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/437/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 437`

View PR using the GUI difftool: \
`$ git pr show -t 437`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/437.diff">https://git.openjdk.org/jdk8u-dev/pull/437.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/437#issuecomment-1932497499)

### CODE REVIEW

**Comment by jerboaa** [comment]
Note the CSR for this is likely this one:
https://bugs.openjdk.org/browse/JDK-8288978

I've asked on the specifics of the 8u version, though.

**Comment by dhanalla** [comment]
> Note the CSR for this is likely this one: https://bugs.openjdk.org/browse/JDK-8288978
> 
> I've asked on the specifics of the 8u version, though.

Thanks @jerboaa

**Comment by dhanalla** [comment]
> > Note the CSR for this is likely this one: https://bugs.openjdk.org/browse/JDK-8288978
> > I've asked on the specifics of the 8u version, though.
> 
> Thanks @jerboaa

@jerboaa I've added a follow-up request in the bug. In the meantime, could you please review this PR and the main PR https://github.com/openjdk/jdk8u-dev/pull/409 ?

**Comment by dhanalla** [comment]
> Note the CSR for this is likely this one: https://bugs.openjdk.org/browse/JDK-8288978
> 
> I've asked on the specifics of the 8u version, though.

**Comment by dhanalla** [comment]
> > Note the CSR for this is likely this one: https://bugs.openjdk.org/browse/JDK-8288978
> > I've asked on the specifics of the 8u version, though.

@jerboaa, I have created a CSR https://bugs.openjdk.org/browse/JDK-8326435.

**Review by gnu-andrew — COMMENTED** [review]
The text in `jdk/src/share/classes/java/net/doc-files/net-properties.html` seems to be indented differently to the 11u version:
~~~
+--- a/jdk/src/share/classes/java/net/doc-files/net-properties.html
++++ b/jdk/src/share/classes/java/net/doc-files/net-properties.html
+@@ -172,6 +172,16 @@ <H2>Misc HTTP properties</H2>
        If HTTP keepalive is enabled (see above) this value determines the
        maximum number of idle connections that will be simultaneously kept
        alive, per destination.</P>
-+      <LI><P><B>{@systemProperty http.keepAlive.time.server}</B> and
-+        <B>{@systemProperty http.keepAlive.time.proxy}</B> </P>
++      <LI><P><B>http.keepAlive.time.server</B> and
++      <B>http.keepAlive.time.proxy</B> </P>
 +      <P>These properties modify the behavior of the HTTP keepalive cache in the case
-+        where the server (or proxy) has not specified a keepalive time. If the
-+        property is set in this case, then idle connections will be closed after the 
-+        specified number of seconds. If the property is set, and the server does
-+        specify a keepalive time in a "Keep-Alive" response header, then the time specified 
-+        by the server is used. If the property is not set and also the server
-+        does not specify a keepalive time, then connections are kept alive for an
-+        implementation defined time, assuming {@code http.keepAlive} is {@code true}.</P>
++      where the server (or proxy) has not specified a keepalive time. If the
++      property is set in this case, then idle connections will be closed after the
++      specified number of seconds. If the property is set, and the server does
++      specify a keepalive time in a "Keep-Alive" response header, then the time specified
++      by the server is used. If the property is not set and also the server
++      does not specify a keepalive time, then connections are kept alive for an
++      implementation defined time, assuming {@code http.keepAlive} is {@code true}.</P>
        <LI><P><B>http.maxRedirects</B> (default: 20)<BR>
        This integer value determines the maximum number, for a given request,
        of HTTP redirects that will be automatically followed by the
~~~

Can we please align these? Removing the `@systemProperty` tag should not mean changing the indentation of the entire block. Comparing while ignoring whitespace changes shows that most of it is identical, bar the first two lines.

Otherwise seems mostly clean. The change to the test library looks fine and the absence of the empty line removal is due to [8279842: HTTPS Channel Binding support for Java GSS/Kerberos](https://bugs.openjdk.org/browse/JDK-8279842) being absent (which we should probably also backport at some point as it is in Oracle 8u341)

**Comment by dhanalla** [comment]
> The text in `jdk/src/share/classes/java/net/doc-files/net-properties.html` seems to be indented differently to the 11u version:
> 
> ```
> +--- a/jdk/src/share/classes/java/net/doc-files/net-properties.html
> ++++ b/jdk/src/share/classes/java/net/doc-files/net-properties.html
> +@@ -172,6 +172,16 @@ <H2>Misc HTTP properties</H2>
>         If HTTP keepalive is enabled (see above) this value determines the
>         maximum number of idle connections that will be simultaneously kept
>         alive, per destination.</P>
> -+      <LI><P><B>{@systemProperty http.keepAlive.time.server}</B> and
> -+        <B>{@systemProperty http.keepAlive.time.proxy}</B> </P>
> ++      <LI><P><B>http.keepAlive.time.server</B> and
> ++      <B>http.keepAlive.time.proxy</B> </P>
>  +      <P>These properties modify the behavior of the HTTP keepalive cache in the case
> -+        where the server (or proxy) has not specified a keepalive time. If the
> -+        property is set in this case, then idle connections will be closed after the 
> -+        specified number of seconds. If the property is set, and the server does
> -+        specify a keepalive time in a "Keep-Alive" response header, then the time specified 
> -+        by the server is used. If the property is not set and also the server
> -+        does not specify a keepalive time, then connections are kept alive for an
> -+        implementation defined time, assuming {@code http.keepAlive} is {@code true}.</P>
> ++      where the server (or proxy) has not specified a keepalive time. If the
> ++      property is set in this case, then idle connections will be closed after the
> ++      specified number of seconds. If the property is set, and the server does
> ++      specify a keepalive time in a "Keep-Alive" response header, then the time specified
> ++      by the server is used. If the property is not set and also the server
> ++      does not specify a keepalive time, then connections are kept alive for an
> ++      implementation defined time, assuming {@code http.keepAlive} is {@code true}.</P>
>         <LI><P><B>http.maxRedirects</B> (default: 20)<BR>
>         This integer value determines the maximum number, for a given request,
>         of HTTP redirects that will be automatically followed by the
> ```
> 
> Can we please align these? Removing the `@systemProperty` tag should not mean changing the indentation of the entire block. Comparing while ignoring whitespace changes shows that most of it is identical, bar the first two lines.
> 
> Otherwise seems mostly clean. The change to the test library looks fine and the absence of the empty line removal is due to [8279842: HTTPS Channel Binding support for Java GSS/Kerberos](https://bugs.openjdk.org/browse/JDK-8279842) being absent (which we should probably also backport at some point as it is in Oracle 8u341)

Thanks @gnu-andrew for reviewing this PR.
Adjusted the Indentation according to 11u.

**Review by jerboaa — APPROVED** [review]
This seems fine to me. @gnu-andrew should ack it as well.

Nit: This tiny diff still makes it more different than it needs to be as compared to the 11u version (some trailing whitespace):

```
diff --git a/jdk/src/share/classes/java/net/doc-files/net-properties.html b/jdk/src/share/classes/java/net/doc-files/net-properties.html
index b1964ac4da..2d25e1b9f3 100644
--- a/jdk/src/share/classes/java/net/doc-files/net-properties.html
+++ b/jdk/src/share/classes/java/net/doc-files/net-properties.html
@@ -176,9 +176,9 @@ of proxies.</P>
         <B>http.keepAlive.time.proxy</B> </P>
        <P>These properties modify the behavior of the HTTP keepalive cache in the case
         where the server (or proxy) has not specified a keepalive time. If the
-        property is set in this case, then idle connections will be closed after the
+        property is set in this case, then idle connections will be closed after the 
         specified number of seconds. If the property is set, and the server does
-        specify a keepalive time in a "Keep-Alive" response header, then the time specified
+        specify a keepalive time in a "Keep-Alive" response header, then the time specified 
         by the server is used. If the property is not set and also the server
         does not specify a keepalive time, then connections are kept alive for an
         implementation defined time, assuming {@code http.keepAlive} is {@code true}.</P>
```

**Review by gnu-andrew — COMMENTED** [review]
Yes, the two lines Severin mentions still need to be fixed.
I recommend getting a local copy of the 11u patch - e.g. `git show c9a72595aa2de5df5849d0b9458ed453bd0dfbad > /tmp/8278067.11u` - and comparing that with what you have in your 8u repository.  The only difference in the two patches for `net-properties.html` should be the `http.keepAlive.time.server` lines.

**Review by gnu-andrew — APPROVED** [review]
Thanks for persisting with this. Updated version looks good.

**Pull request closed without merging**
