### PR TITLE
8295322: Tests for JDK-8271459 were not backported to 11u

### PR DESCRIPTION
**Pull request by apavlyutkin**
Hi!

Here is the backport of [JDK-8295322](https://bugs.openjdk.org/browse/JDK-8295322) that adds missed tests for [JDK-8271459](https://bugs.openjdk.org/browse/JDK-8271459). Except the path shuffling the following changes were done to the original https://github.com/openjdk/jdk11u-dev/commit/70ddb1b025ce3b8eed4d8ad5af1b1fa4d0e0b015

- visibility of test class and methods was changed to `public` to support older JTReg
- `requires` annotation was removed to support older JTReg

Verification (amd64/20.04 LTS): running new `hotspot/test/compiler/c2/TestNegativeStringBuilderCapacity.java`

7 of 7 PASS on https://github.com/openjdk/jdk8u-dev/commit/dfeeceb224a62bd7ffbe5adfd36eebe6c853935a (integration of [JDK-8271459](https://bugs.openjdk.org/browse/JDK-8271459))
4 of 7 FAIL on the previous https://github.com/openjdk/jdk8u-dev/commit/43cfe27fa3a11dd6d4fffcb1c1336ac7fdd0233b

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8295322](https://bugs.openjdk.org/browse/JDK-8295322): Tests for JDK-8271459 were not backported to 11u

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/152/head:pull/152` \
`$ git checkout pull/152`

Update a local copy of the PR: \
`$ git checkout pull/152` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/152/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 152`

View PR using the GUI difftool: \
`$ git pr show -t 152`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/152.diff">https://git.openjdk.org/jdk8u-dev/pull/152.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by apavlyutkin** [comment]
Thank you for the review

**Comment by phohensee** [comment]
I'd ping a maintainer directly.

**Pull request closed without merging**
