### PR TITLE
8282552: Bump update version of OpenJDK: 8u342

### PR DESCRIPTION
**Pull request by jerboaa**
Bump update version of jdk8u-dev to 8u342

------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] Change must be properly reviewed

### Issue
 * [JDK-8282552](https://bugs.openjdk.java.net/browse/JDK-8282552): Bump update version of OpenJDK: 8u342

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk8u-dev pull/1/head:pull/1` \
`$ git checkout pull/1`

Update a local copy of the PR: \
`$ git checkout pull/1` \
`$ git pull https://git.openjdk.java.net/jdk8u-dev pull/1/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1`

View PR using the GUI difftool: \
`$ git pr show -t 1`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk8u-dev/pull/1.diff">https://git.openjdk.java.net/jdk8u-dev/pull/1.diff</a>

</details>

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8282552](https://bugs.openjdk.java.net/browse/JDK-8282552): Bump update version of OpenJDK: 8u342

### Reviewers
 * [Erik Joelsson](https://openjdk.java.net/census#erikj) (@erikj79 - **Reviewer**) ⚠️ Review applies to 7d9e3b51ba761e04294e78ccdea6e6aa5c5dc079
 * [Andrew John Hughes](https://openjdk.java.net/census#andrew) (@gnu-andrew - **Reviewer**) ⚠️ Review applies to feaf07b6402ca601a592574bf6e605aadd0f47ea

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk8u-dev pull/1/head:pull/1` \
`$ git checkout pull/1`

Update a local copy of the PR: \
`$ git checkout pull/1` \
`$ git pull https://git.openjdk.java.net/jdk8u-dev pull/1/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 1`

View PR using the GUI difftool: \
`$ git pr show -t 1`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk8u-dev/pull/1.diff">https://git.openjdk.java.net/jdk8u-dev/pull/1.diff</a>

</details>

### CODE REVIEW

**Review by erikj79 — APPROVED** [review]

**Review by gnu-andrew — CHANGES_REQUESTED** [review]
This is doing a lot more than bumping the update version.

I already filed a bug for the .jcheck/conf change: https://bugs.openjdk.java.net/browse/JDK-8282458 

That change should happen under that bug ID.

As to changing JDK_UPDATE_VERSION, we have not set this in the past for 8u and there was objection at the time to doing this. It certainly should have its own PR, separate from the necessary .jcheck/conf change.

**Comment by jerboaa** [comment]
> This is doing a lot more than bumping the update version.
> 
> I already filed a bug for the .jcheck/conf change: https://bugs.openjdk.java.net/browse/JDK-8282458

I didn't know that existed. Happy to withdraw the `.jcheck/conf` changes from this PR, or withdraw entirely.

> That change should happen under that bug ID.

Sure.

> As to changing JDK_UPDATE_VERSION, we have not set this in the past for 8u and there was objection at the time to doing this. It certainly should have its own PR, separate from the necessary .jcheck/conf change.

I was thinking it would be something we could be doing for 8u so that `java -version` gives the developer an idea which update cycle this would be. We'd have to do `.jcheck/conf` updates every quarter now anyway. Example:

```
$ java -version
openjdk version "1.8.0_342-internal"
OpenJDK Runtime Environment (build 1.8.0_342-internal-sgeholf_2022_03_02_12_07-b00)
OpenJDK 64-Bit Server VM (build 25.342-b00, mixed mode)
```

It still doesn't look like a real production build, which would match 11u IMO. Do you remember what the objection was?

**Comment by gnu-andrew** [comment]
> > This is doing a lot more than bumping the update version.
> > I already filed a bug for the .jcheck/conf change: https://bugs.openjdk.java.net/browse/JDK-8282458
> 
> I didn't know that existed. Happy to withdraw the `.jcheck/conf` changes from this PR, or withdraw entirely.

Thanks. No worries, I did link it to the SKARA bug but I guess you missed it. I was going to try and move further with this on Monday but the transition wasn't ready in time.

No objection to the content - i just copied your changes to the other PR, after comparing with 11u - I just wanted it to be clearer what change was being made. It took me a while to find the change in 11u because it was hidden in one of these 'bump' changes.

> 
> > That change should happen under that bug ID.
> 
> Sure.
> 
> > As to changing JDK_UPDATE_VERSION, we have not set this in the past for 8u and there was objection at the time to doing this. It certainly should have its own PR, separate from the necessary .jcheck/conf change.
> 
> I was thinking it would be something we could be doing for 8u so that `java -version` gives the developer an idea which update cycle this would be. We'd have to do `.jcheck/conf` updates every quarter now anyway. Example:
> 
> ```
> $ java -version
> openjdk version "1.8.0_342-internal"
> OpenJDK Runtime Environment (build 1.8.0_342-internal-sgeholf_2022_03_02_12_07-b00)
> OpenJDK 64-Bit Server VM (build 25.342-b00, mixed mode)
> ```
> 
> It still doesn't look like a real production build, which would match 11u IMO. Do you remember what the objection was?

Yeah, I have no objection. I originally proposed even doing the build number, but that was some pushback from Azul that I never really understood. I'll dig out the original thread.

**Comment by gnu-andrew** [comment]
Thanks. Just waiting on a jdk8u-fix-yes, I think.

**Comment by gnu-andrew** [comment]
This is the thread I was referring to: https://mail.openjdk.java.net/pipermail/jdk8u-dev/2019-June/009598.html

Re-reading it, I think Gil's main objection was to change the default to "fcs" with a release. I don't see any objection to setting the update version and there seems to have been none to this on 11u.

They also seem to be doing the same bump in 13u - https://github.com/openjdk/jdk13u-dev/commit/9e30b3d316dcbbb1e31fafac6d622cba77a7629f - so I can't see an objection to this. I was probably going too far with my change (though I still think it was the right thing)

**Review by gnu-andrew — APPROVED** [review]

**Pull request closed without merging**
