### PR TITLE
8071507: (ref) Clear phantom reference as soft and weak references do

### PR DESCRIPTION
**Pull request by poonamparhar**
Backport of 8071507 and 8143847 from jdk8u-ri to jdk8u-dev.

    8071507: (ref) Clear phantom reference as soft and weak references do
    8143847: Remove REF_CLEANER reference category

With these changes, phantom references are automatically cleared by the garbage collector like soft and weak references.

The changes are clean backport apart from a little manual adjustment for the hunk at line 246 in referenceProcessor.cpp.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (3 reviews required, with at least 3 [Reviewers](https://openjdk.org/bylaws#reviewer))

### Issues
 * [JDK-8071507](https://bugs.openjdk.org/browse/JDK-8071507): (ref) Clear phantom reference as soft and weak references do
 * [JDK-8143847](https://bugs.openjdk.org/browse/JDK-8143847): Remove REF_CLEANER reference category

### Reviewers
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - Author) ⚠️ Review applies to [f0ee3e01](https://git.openjdk.org/jdk8u-dev/pull/94/files/f0ee3e01ad3aedd6ca2e11882ff3ed35b6de0f52)
 * [David Holmes](https://openjdk.org/census#dholmes) (@dholmes-ora - **Reviewer**) ⚠️ Review applies to [f0ee3e01](https://git.openjdk.org/jdk8u-dev/pull/94/files/f0ee3e01ad3aedd6ca2e11882ff3ed35b6de0f52)
 * [Mandy Chung](https://openjdk.org/census#mchung) (@mlchung - **Reviewer**) ⚠️ Review applies to [f0ee3e01](https://git.openjdk.org/jdk8u-dev/pull/94/files/f0ee3e01ad3aedd6ca2e11882ff3ed35b6de0f52)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/94/head:pull/94` \
`$ git checkout pull/94`

Update a local copy of the PR: \
`$ git checkout pull/94` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/94/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 94`

View PR using the GUI difftool: \
`$ git pr show -t 94`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/94.diff">https://git.openjdk.org/jdk8u-dev/pull/94.diff</a>

</details>

### CODE REVIEW

**Review by dholmes-ora — APPROVED** [review]
This is an accurate backport. Thanks @poonamparhar !

**Review by mlchung — APPROVED** [review]
LGTM

**Review by gnu-andrew — CHANGES_REQUESTED** [review]
Is there a reason for backporting two changes in one PR? I see this was done in 8u42 as well. It makes it harder to review than necessary, notably where the two change the same code in `referenceProcessor.cpp`.

Also, SKARA does not appear to be picking this up as a backport, as the "Backport <commit>" style was not used (https://wiki.openjdk.org/display/SKARA/Backports). Ideally it would refer to the changeset in 8u42, [ad6cdea5ae385623afa86251a8278c9c5274f4c1](https://git.openjdk.java.net/jdk8u-ri/commit/ad6cdea5ae385623afa86251a8278c9c5274f4c1), but it may have to be one of the three original changesets from jdk

In the code itself, three files are missing copyright header changes where they are newer than the current version: `referenceProcessor.hpp`, `referenceProcessor.cpp" and `referenceType.hpp`.  8143847 bumps all of these to 2016 and this change should do the same. The other files already have a newer copyright year than in 8143847.

**Comment by mlchung** [comment]
> Is there a reason for backporting two changes in one PR? I see this was done in 8u42 as well. It makes it harder to review than necessary, notably where the two change the same code in `referenceProcessor.cpp`.

It could be done in two separate PRs.  I agree it would be easier to review if they are two separate PRs.   8143847 mainly removed the cleaner related code.  As I was familiar with the code, I didn't ask to do two separate PRs.  Will bear that in mind in the future.

**Comment by poonamparhar** [comment]
> Also, SKARA does not appear to be picking this up as a backport, as the "Backport " style was not used (https://wiki.openjdk.org/display/SKARA/Backports). Ideally it would refer to the changeset in 8u42, [ad6cdea5ae385623afa86251a8278c9c5274f4c1](https://git.openjdk.java.net/jdk8u-ri/commit/ad6cdea5ae385623afa86251a8278c9c5274f4c1), but it may have to be one of the three original changesets from jdk
> 
> In the code itself, three files are missing copyright header changes where they are newer than the current version: `referenceProcessor.hpp`, `referenceProcessor.cpp" and `referenceType.hpp`. 8143847 bumps all of these to 2016 and this change should do the same. The other files already have a newer copyright year than in 8143847.

I have updated the copyright years and also fixed the SAKARA backport.

**Comment by kimbarrett** [comment]
> Is there a reason for backporting two changes in one PR? I see this was done in 8u42 as well. It makes it harder to review than necessary, notably where the two change the same code in `referenceProcessor.cpp`.

There was a change before 8071507 in mainline (and backported to jdk8u) that wasn’t in the RI. That change was rendered moot (the changed code was entirely removed) by 8143847. So if we’d separated 8071507 and 8143847 in the RI we would have needed to first apply that other change to the RI (8071507 without that earlier change would have been wrong), only to have it disappear with 8143847.

**Comment by gnu-andrew** [comment]
> > Also, SKARA does not appear to be picking this up as a backport, as the "Backport " style was not used (https://wiki.openjdk.org/display/SKARA/Backports). Ideally it would refer to the changeset in 8u42, [ad6cdea5ae385623afa86251a8278c9c5274f4c1](https://git.openjdk.java.net/jdk8u-ri/commit/ad6cdea5ae385623afa86251a8278c9c5274f4c1), but it may have to be one of the three original changesets from jdk
> > In the code itself, three files are missing copyright header changes where they are newer than the current version: `referenceProcessor.hpp`, `referenceProcessor.cpp" and `referenceType.hpp`. 8143847 bumps all of these to 2016 and this change should do the same. The other files already have a newer copyright year than in 8143847.
> 
> I have updated the copyright years and also fixed the SAKARA backport part.

Thanks. Patch looks good and seems SKARA is happier now :-)

**Comment by gnu-andrew** [comment]
> > Is there a reason for backporting two changes in one PR? I see this was done in 8u42 as well. It makes it harder to review than necessary, notably where the two change the same code in `referenceProcessor.cpp`.
> 
> There was a change before 8071507 in mainline (and backported to jdk8u) that wasn’t in the RI. That change was rendered moot (the changed code was entirely removed) by 8143847. So if we’d separated 8071507 and 8143847 in the RI we would have needed to first apply that other change to the RI (8071507 without that earlier change would have been wrong), only to have it disappear with 8143847.

Thanks. Having reviewed the code, that makes sense.

**Review by gnu-andrew — APPROVED** [review]

**Comment by gnu-andrew** [comment]
I've set `jdk8u-fix-yes` on the bug so this can be integrated now. Thanks again for the contribution.

**Pull request closed without merging**
