### PR TITLE
8222323: ChildAlwaysOnTopTest.java fails with "RuntimeException: Failed to unset alwaysOnTop"

### PR DESCRIPTION
**Pull request by kurashige23**
Hi,

This is a backport of JDK-8222323: ChildAlwaysOnTopTest.java fails with "RuntimeException: Failed to unset alwaysOnTop"

Original patch does not apply cleanly to JDK-8021961 applied code, because the fix uses "StringBuffer.isEmpty()" published in JDK15. I fixed the test so as not to use "StringBuffer.isEmpty()".

Testing: jdk_awt on RHEL7, GHA testing

Thanks.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8222323](https://bugs.openjdk.org/browse/JDK-8222323) needs maintainer approval

### Issue
 * [JDK-8222323](https://bugs.openjdk.org/browse/JDK-8222323): ChildAlwaysOnTopTest.java fails with "RuntimeException: Failed to unset alwaysOnTop" (**Bug** - P4 - Approved)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/378/head:pull/378` \
`$ git checkout pull/378`

Update a local copy of the PR: \
`$ git checkout pull/378` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/378/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 378`

View PR using the GUI difftool: \
`$ git pr show -t 378`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/378.diff">https://git.openjdk.org/jdk8u-dev/pull/378.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/378#issuecomment-1738826635)

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
Seems OK.

**Comment by jerboaa** [comment]
Please ask for approval of the bug using the `/approval` [SKARA command](https://wiki.openjdk.org/display/SKARA/Pull+Request+Commands#PullRequestCommands-/approval) so that the dependency and this one can get approved together.

**Comment by kurashige23** [comment]
/approval JDK-8021961 request Test-only backport, no risk.

**Comment by phohensee** [comment]
This PR has been approved, please add /integrate.

**Comment by jerboaa** [comment]
> This PR has been approved, please add /integrate.

This needs https://github.com/openjdk/jdk8u-dev/pull/377 first.

**Pull request closed without merging**
