### PR TITLE
8214427: probable bug in logic of ConcurrentHashMap.addCount()

### PR DESCRIPTION
**Pull request by tianshuang**
8214427: probable bug in logic of ConcurrentHashMap.addCount()

This backport fixes the problem that the MAX_RESIZERS control does not take effect when multi-threaded expansion in ConcurrentHashMap.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed (2 reviews required, with at least 2 [Reviewers](https://openjdk.org/bylaws#reviewer))

### Issue
 * [JDK-8214427](https://bugs.openjdk.org/browse/JDK-8214427): probable bug in logic of ConcurrentHashMap.addCount()

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [7658e302](https://git.openjdk.org/jdk8u-dev/pull/18/files/7658e302dc3ae1c2dea6c9a6f2cb0ca7a68b4967)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/18/head:pull/18` \
`$ git checkout pull/18`

Update a local copy of the PR: \
`$ git checkout pull/18` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/18/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 18`

View PR using the GUI difftool: \
`$ git pr show -t 18`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/18.diff">https://git.openjdk.org/jdk8u-dev/pull/18.diff</a>

</details>

### CODE REVIEW

**Comment by tianshuang** [comment]
waiting for reviewer's review...

**Review by phohensee — APPROVED** [review]
Clean backport net of file location. Lgtm.

**Comment by phohensee** [comment]
Passes java.util.concurrent jtreg tests.

**Comment by phohensee** [comment]
I'll sponsor this backport. Waiting for maintainer approval (jdk8u-fix-yes tag). See https://wiki.openjdk.java.net/display/jdk8u/Main for details.

**Comment by jerboaa** [comment]
This is not in 11u as far as I can see. It should go there first before going into 8.

**Review by gnu-andrew — COMMENTED** [review]
I've opened a PR for the 11u backport: https://github.com/openjdk/jdk11u-dev/pull/1114

Can you merge this with jdk8u-dev/master so that the full set of build checks run?

I've see some whitespace differences with the 8u version:

```
-+                        (nt = nextTable) == null || transferIndex <= 0)
++                            (nt = nextTable) == null || transferIndex <= 0)
```

```
-+                    transferIndex <= 0)
++                        transferIndex <= 0)
```

Do you see this locally or is it introduced by the `webrev` tool?

The change from `compareAndSetInt` to `compareAndSwapInt` looks correct to match the 8u version.

**Comment by gnu-andrew** [comment]
Name change is solely a renaming; see https://bugs.openjdk.java.net/browse/JDK-8159995 and https://bugs.openjdk.java.net/browse/JDK-8181292

**Review by gnu-andrew — CHANGES_REQUESTED** [review]
Fix is in 11u: https://git.openjdk.java.net/jdk11u-dev/commit/a2e64948eb12089bd45c2b734c405ead87977276

Awaiting response to my previous comments and test runs.

**Comment by tianshuang** [comment]
@jerboaa 11u now includes a backport of 8214427.

**Comment by tianshuang** [comment]
@jerboaa Test has passed.

**Comment by gnu-andrew** [comment]
> I've opened a PR for the 11u backport: [openjdk/jdk11u-dev#1114](https://github.com/openjdk/jdk11u-dev/pull/1114)
> 
> Can you merge this with jdk8u-dev/master so that the full set of build checks run?
> 
> I've see some whitespace differences with the 8u version:
> 
> ```
> -+                        (nt = nextTable) == null || transferIndex <= 0)
> ++                            (nt = nextTable) == null || transferIndex <= 0)
> ```
> 
> ```
> -+                    transferIndex <= 0)
> ++                        transferIndex <= 0)
> ```
> 
> Do you see this locally or is it introduced by the `webrev` tool?
> 
> The change from `compareAndSetInt` to `compareAndSwapInt` looks correct to match the 8u version.

These whitespace issues are still not resolved in the current patch.

**Comment by gnu-andrew** [comment]
> @gnu-andrew The total number of required reviews for this PR (including the jcheck configuration and the last /reviewers command) is now set to 1 (with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer)).

"The requirements are in addition to the ones specified by the .jcheck/conf file. "

Clearly not, because 1 (from jcheck) + 1 (from reviewers command) should equal 2.

**Comment by tianshuang** [comment]
> > I've opened a PR for the 11u backport: [openjdk/jdk11u-dev#1114](https://github.com/openjdk/jdk11u-dev/pull/1114)
> > Can you merge this with jdk8u-dev/master so that the full set of build checks run?
> > I've see some whitespace differences with the 8u version:
> > ```
> > -+                        (nt = nextTable) == null || transferIndex <= 0)
> > ++                            (nt = nextTable) == null || transferIndex <= 0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > -+                    transferIndex <= 0)
> > ++                        transferIndex <= 0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do you see this locally or is it introduced by the `webrev` tool?
> > The change from `compareAndSetInt` to `compareAndSwapInt` looks correct to match the 8u version.
> 
> These whitespace issues are still not resolved in the current patch.

Already fixed

**Review by gnu-andrew — APPROVED** [review]
Diff looks right now, thanks.
~~~
@@ -24,16 +15,16 @@
 +                    if (sc == rs + MAX_RESIZERS || sc == rs + 1 ||
 +                        (nt = nextTable) == null || transferIndex <= 0)
                          break;
-                     if (U.compareAndSetInt(this, SIZECTL, sc, sc + 1))
+                     if (U.compareAndSwapInt(this, SIZECTL, sc, sc + 1))
                          transfer(tab, nt);
                  }
--                else if (U.compareAndSetInt(this, SIZECTL, sc,
+-                else if (U.compareAndSwapInt(this, SIZECTL, sc,
 -                                             (rs << RESIZE_STAMP_SHIFT) + 2))
-+                else if (U.compareAndSetInt(this, SIZECTL, sc, rs + 2))
++                else if (U.compareAndSwapInt(this, SIZECTL, sc, rs + 2))
                      transfer(tab, null);
                  s = sumCount();
              }
-@@ -2358,11 +2356,11 @@ public class ConcurrentHashMap<K,V> extends AbstractMap<K,V>
+@@ -2298,11 +2296,11 @@ final Node<K,V>[] helpTransfer(Node<K,V>[] tab, Node<K,V> f) {
          Node<K,V>[] nextTab; int sc;
          if (tab != null && (f instanceof ForwardingNode) &&
              (nextTab = ((ForwardingNode<K,V>)f).nextTable) != null) {
@@ -46,5 +37,5 @@
 +                if (sc == rs + MAX_RESIZERS || sc == rs + 1 ||
 +                    transferIndex <= 0)
                      break;
-                 if (U.compareAndSetInt(this, SIZECTL, sc, sc + 1)) {
+                 if (U.compareAndSwapInt(this, SIZECTL, sc, sc + 1)) {
                      transfer(tab, nextTab);
~~~

**Comment by gnu-andrew** [comment]
I've added `jdk8u-fix-yes` to the bug so ready for integration.

**Pull request closed without merging**
