### PR TITLE
4660158: TTY: NumberFormatException while trying to set values by 'set' command

### PR DESCRIPTION
**Pull request by ktakakuri**
Hi all,

JDK8 reproduces the reported bug and I would like to backport this patch. The patch is clean.
There is a related patch JDK-8030204, and I have proposed a separate backport for it. #497

Testing: All tests under jdk/test/com/sun/jdi

Thank you.

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-4660158](https://bugs.openjdk.org/browse/JDK-4660158) needs maintainer approval

### Issue
 * [JDK-4660158](https://bugs.openjdk.org/browse/JDK-4660158): TTY: NumberFormatException while trying to set values by 'set' command (**Bug** - P4 - Approved)

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/496/head:pull/496` \
`$ git checkout pull/496`

Update a local copy of the PR: \
`$ git checkout pull/496` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/496/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 496`

View PR using the GUI difftool: \
`$ git pr show -t 496`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/496.diff">https://git.openjdk.org/jdk8u-dev/pull/496.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/496#issuecomment-2107057172)

### CODE REVIEW

**Comment by ktakakuri** [comment]
TheGHA build failures for s390x and ppc64le, as well as the test failures for security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java are unrelated.
Test failures for com/sun/jdi/JdbExprTest.sh are resolved by the related backport.

**Review by gnu-andrew — APPROVED** [review]
The backport is not completely clean, though Skara claims it is. A fragment from `jdk/src/share/classes/com/sun/tools/example/debug/expr/TokenMgrError.java` was dropped due to the copyright header already being changed by JDK-8029235, a private bug which did a blanket copyright update on a number of files.

Changes look fine though and I'm happy if the tests are passing on the updated version.

**Pull request closed without merging**
