### PR TITLE
8233019: java.lang.Class.isPrimitive() (C1) returns wrong result if Klass* is aligned to 32bit

### PR DESCRIPTION
**Pull request by dongbohe**
Hi,

I would like to backport this as follow up of [JDK-8150669](https://bugs.openjdk.java.net/browse/JDK-8150669)
This resolves the corner case that leads to incorrect result for C1 intrinsic,

Original patch for 11u: https://hg.openjdk.java.net/jdk-updates/jdk11u-dev/rev/e1b6631cbd2f 
Patch does not apply cleanly to 8u: arm and s390 ports are not there and we don’t have c1 compiler support in ppc port in 8u.

Performed full jtreg test both on x86_64-linux-gnu and aarch64-linux-gnu platforms. 
(I made this PR on behalf of fyang)

Thanks,
hedongbo

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8233019](https://bugs.openjdk.org/browse/JDK-8233019): java.lang.Class.isPrimitive() (C1) returns wrong result if Klass* is aligned to 32bit

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [5274a23f](https://git.openjdk.org/jdk8u-dev/pull/43/files/5274a23fb73cfd7213d7007e6418cb49ffea3d8a)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/43/head:pull/43` \
`$ git checkout pull/43`

Update a local copy of the PR: \
`$ git checkout pull/43` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/43/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 43`

View PR using the GUI difftool: \
`$ git pr show -t 43`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/43.diff">https://git.openjdk.org/jdk8u-dev/pull/43.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Lgtm.

**Comment by dongbohe** [comment]
Got the push approval.
/integrate

**Pull request closed without merging**
