### PR TITLE
8316328: Test jdk/jfr/event/oldobject/TestSanityDefault.java times out for some heap sizes

### PR DESCRIPTION
**Pull request by mrserb**
Hi all,

This pull request contains a backport of commit [9b1d6d66](https://github.com/openjdk/jdk/commit/9b1d6d66b8297d53c6b96b9e2f9bd69af90ab8fb) from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Sergey Bylokhov on 23 May 2024 and was reviewed by Paul Hohensee, Aleksey Shipilev and Erik Gahlin.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8316328](https://bugs.openjdk.org/browse/JDK-8316328) needs maintainer approval

### Issue
 * [JDK-8316328](https://bugs.openjdk.org/browse/JDK-8316328): Test jdk/jfr/event/oldobject/TestSanityDefault.java times out for some heap sizes (**Bug** - P3 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/506/head:pull/506` \
`$ git checkout pull/506`

Update a local copy of the PR: \
`$ git checkout pull/506` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/506/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 506`

View PR using the GUI difftool: \
`$ git pr show -t 506`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/506.diff">https://git.openjdk.org/jdk8u-dev/pull/506.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/506#issuecomment-2128502881)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by phohensee** [comment]
GHA failures appear unrelated.

**Comment by mrserb** [comment]
keep open

**Comment by mrserb** [comment]
keep open

**Review by gnu-andrew — APPROVED** [review]
Looks like a trivial clean backport to me.

**Pull request closed without merging**
