### PR TITLE
8301400: Allow additional characters for GB18030-2022 support

### PR DESCRIPTION
**Pull request by naotoj**
This is a backport of GB18030 Level 1 part of the JSR337 MR5 (https://jcp.org/aboutJava/communityprocess/mrel/jsr337/index5.html) Reference Implementation

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8301400](https://bugs.openjdk.org/browse/JDK-8301400): Allow additional characters for GB18030-2022 support

### Reviewers
 * [Lance Andersen](https://openjdk.org/census#lancea) (@LanceAndersen - **Reviewer**)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - Author)
 * [Roger Riggs](https://openjdk.org/census#rriggs) (@RogerRiggs - Committer)

### Contributors
 * Justin Lu `<jlu@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/314/head:pull/314` \
`$ git checkout pull/314`

Update a local copy of the PR: \
`$ git checkout pull/314` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/314/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 314`

View PR using the GUI difftool: \
`$ git pr show -t 314`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/314.diff">https://git.openjdk.org/jdk8u-dev/pull/314.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/314#issuecomment-1540719136)

### CODE REVIEW

**Review by LanceAndersen — APPROVED** [review]

**Comment by jerboaa** [comment]
@naotoj Please enable testing on your fork. Thanks!

**Comment by naotoj** [comment]
> @naotoj Please enable testing on your fork. Thanks!

Oh I did not know that. Started the pre-submit tests: https://github.com/naotoj/jdk8u-dev/actions/runs/4929876090

**Review by RogerRiggs — APPROVED** [review]

**Comment by zzambers** [comment]
> > @naotoj Please enable testing on your fork. Thanks!
> 
> Oh I did not know that. Started the pre-submit tests: https://github.com/naotoj/jdk8u-dev/actions/runs/4929876090

Seems like you have accidentally tested current master branch commit, instead of branch from which this PR was made

**Comment by naotoj** [comment]
> Seems like you have accidentally tested current master branch commit, instead of branch from which this PR was made

Resubmitted with the correct branch (includes both #314 and #315 changes)

**Pull request closed without merging**
