### PR TITLE
8189687: Swing: Invalid position of candidate pop-up of InputMethod in Hi-DPI on Windows

### PR DESCRIPTION
**Pull request by ktakakuri**
This is a backport of JDK-8189687: Swing: Invalid position of candidate pop-up of InputMethod in Hi-DPI on Windows.
JDK-8189687 contains two fixes to AwtComponent:.OpenCandidateWindow, one of which is backported in this pull request.
The other fix is an enhancement to JEP 263 (JDK-8055212) and is not needed since JDK8 does not implement JEP 263.

1. Fix to make OpenCandidateWindow reference the correct Window
Fix OpenCandidateWindow to reference the proxy window that has focus when getting "HWND."

```diff
--- a/src/java.desktop/windows/native/libawt/windows/awt_Component.cpp
+++ b/src/java.desktop/windows/native/libawt/windows/awt_Component.cpp
@@ -3880,19 +3880,21 @@ void AwtComponent::OpenCandidateWindow(int x, int y)
 {
     UINT bits = 1;
     POINT p = {0, 0}; // upper left corner of the client area
-    HWND hWnd = GetHWnd();
+    HWND hWnd = ImmGetHWnd();
     if (!::IsWindowVisible(hWnd)) {
         return;
     }

```

2. Scaling fixes to enhance JDK-8073320
OpenJDK9 has supported HiDPI Graphics since JEP 263 (JDK-8055212). This fix is one of its enhancements: when OpenCandidateWindow opens an IME conversion candidate, it corrects the coordinates for the device.

In the attached test that reproduces the issue problem, the Panel containing the TextField is a child component, so it refers to the wrong window to get the position coordinate of the candidate window.
Therefore, the candidate window will appear in the correct position with the "1" fix.
Note that OpenJDK8 does not implement JEP 263, so the "2" fix is not included in this pull request.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8189687](https://bugs.openjdk.org/browse/JDK-8189687) needs maintainer approval

### Issue
 * [JDK-8189687](https://bugs.openjdk.org/browse/JDK-8189687): Swing: Invalid position of candidate pop-up of InputMethod in Hi-DPI on Windows (**Bug** - P3 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/564/head:pull/564` \
`$ git checkout pull/564`

Update a local copy of the PR: \
`$ git checkout pull/564` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/564/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 564`

View PR using the GUI difftool: \
`$ git pr show -t 564`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/564.diff">https://git.openjdk.org/jdk8u-dev/pull/564.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/564#issuecomment-2298650597)
</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by ktakakuri** [comment]
/approval request This bug is reproducible in JDK8, and backporting this patch is needed. JDK-8189687 contains two fixes to AwtComponent:.OpenCandidateWindow, one of which is backported in this pull request. The other fix is an enhancement to JEP 263 (JDK-8055212) and is not needed since JDK8 does not implement JEP 263.

**Comment by ktakakuri** [comment]
This pull request is pending approval of the Fix Request.
I comment to not close.

**Comment by ktakakuri** [comment]
This pull request is pending approval of the Fix Request.
I comment to not close.

**Comment by stooke** [comment]
(Disclaimer: I am not an official reviewer)
I have reproduced the issue, reviewed and tested this change and the tier1 Windows failures which are all certificate failures (unrelated), and my opinion is that this is good to go.

**Pull request closed without merging**
