### PR TITLE
8132256: jaxp: Investigate removal of com/sun/org/apache/bcel/internal/util/ClassPath.java

### PR DESCRIPTION
**Pull request by akashche**
Please review a backport of a JAXP cleanup.

Original commit [dcdbd67e6408](https://hg.openjdk.java.net/jdk9/jdk9/jaxp/rev/dcdbd67e6408) in jdk9.

Commit [6e586e8](https://github.com/openjdk/jdk11u-dev/commit/6e586e8a3b8807652218c4caf97ef501f42d7f36) in jdk11u-dev.

This cleanup should allow to backport other JAXP changes (like [JDK-8163121](https://bugs.openjdk.java.net/browse/JDK-8163121)) easier.

Patch does not apply cleanly because in jdk9 ClassPath.java (that is deleted in this backport) was changed in [JDK-8049367](https://bugs.openjdk.java.net/browse/JDK-8049367) that is not in 8u.

Testing:

 - [x] jtreg:javax/xml/jaxp
 - [x] jck:api/javax_xml

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change must be properly reviewed

### Issue
 * [JDK-8132256](https://bugs.openjdk.java.net/browse/JDK-8132256): jaxp: Investigate removal of com/sun/org/apache/bcel/internal/util/ClassPath.java

### Reviewers
 * [Andrew John Hughes](https://openjdk.java.net/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jdk8u-dev pull/5/head:pull/5` \
`$ git checkout pull/5`

Update a local copy of the PR: \
`$ git checkout pull/5` \
`$ git pull https://git.openjdk.java.net/jdk8u-dev pull/5/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 5`

View PR using the GUI difftool: \
`$ git pr show -t 5`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jdk8u-dev/pull/5.diff">https://git.openjdk.java.net/jdk8u-dev/pull/5.diff</a>

</details>

### CODE REVIEW

**Comment by gnu-andrew** [comment]
Looks fine to me. It doesn't matter about changes for the module system we don't want being missing from a file we're deleting anyway :)

Please flag with `jdk8u-fix-request`

**Comment by akashche** [comment]
Thanks for the review! I've marked the issue for approval.

**Review by gnu-andrew — APPROVED** [review]
Fix approved for 8u.

**Pull request closed without merging**
