### PR TITLE
8294767: 8u contains two copies of test/../FileUtils.java, one uses JDK9+ features

### PR DESCRIPTION
**Pull request by jmtd**
There are two copies of the test utility class FileUtils.java in the jdk8u-dev source tree:

```
$ find . -name FileUtils.java
./jdk/test/lib/testlibrary/jdk/testlibrary/FileUtils.java
./jdk/test/lib/jdk/test/lib/util/FileUtils.java
```

One of them is not used by anything. It also uses language features that are not present in 8u:

```
$ $JAVA_HOME/bin/javac ./jdk/test/lib/jdk/test/lib/util/FileUtils.java
# snip
./jdk/test/lib/jdk/test/lib/util/FileUtils.java:166: error: cannot infer type arguments for SimpleFileVisitor<T>
            java.nio.file.Files.walkFileTree(dir, new SimpleFileVisitor<>() {
                                                                       ^
  reason: cannot use '<>' with anonymous inner classes
```

The soluton for this case is simple, just remove the above file.

This is part of a wider issue of duplicated test material, but I'm filing for the one I found for now. 

* https://bugs.openjdk.org/browse/JDK-8294767

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8294767](https://bugs.openjdk.org/browse/JDK-8294767): 8u contains two copies of test/../FileUtils.java, one uses JDK9+ features

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/129/head:pull/129` \
`$ git checkout pull/129`

Update a local copy of the PR: \
`$ git checkout pull/129` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/129/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 129`

View PR using the GUI difftool: \
`$ git pr show -t 129`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/129.diff">https://git.openjdk.org/jdk8u-dev/pull/129.diff</a>

</details>

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
OK with me.

**Review by gnu-andrew — APPROVED** [review]
This is fine by me. Please add `jdk8u-fix-yes` to the bug and I'll approve.

I'm aware of the whole mess created by the JFR import. I'd like to clean this up and move the tests to top-level, as they are in later JDKs, but this should wait until after this CGroup backlog is done.

**Comment by jerboaa** [comment]
> This is fine by me. Please add `jdk8u-fix-yes` to the bug and I'll approve.

`jdk8u-fix-request` not, `jdk8u-fix-yes` ;-)

**Comment by gnu-andrew** [comment]
> > This is fine by me. Please add `jdk8u-fix-yes` to the bug and I'll approve.
> 
> `jdk8u-fix-request` not, `jdk8u-fix-yes` ;-)

Heh, yeah :) I see you both added the right ones now, so this is ready to integrate.

**Pull request closed without merging**
