### PR TITLE
8193682: Infinite loop in ZipOutputStream.close()

### PR DESCRIPTION
**Pull request by yan-too**
This is a backport of JDK-8193682 already present in all 11+ releases of OpenJDK and in Oracle release 8u341. The problem was encountered in the wild and reported as a blocker.

The backport of jdk11 version is clean with paths adjustments only. Performed testing did not reveal any issues.

There will be a second fix in this series, JDK-8278794.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8283331](https://bugs.openjdk.org/browse/JDK-8283331) to be approved
- [x] [JDK-8193682](https://bugs.openjdk.org/browse/JDK-8193682) needs maintainer approval

### Issues
 * [JDK-8193682](https://bugs.openjdk.org/browse/JDK-8193682): Infinite loop in ZipOutputStream.close() (**Bug** - P4 - Approved)
 * [JDK-8283331](https://bugs.openjdk.org/browse/JDK-8283331): Infinite loop in ZipOutputStream.close() (**CSR**)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/558/head:pull/558` \
`$ git checkout pull/558`

Update a local copy of the PR: \
`$ git checkout pull/558` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/558/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 558`

View PR using the GUI difftool: \
`$ git pr show -t 558`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/558.diff">https://git.openjdk.org/jdk8u-dev/pull/558.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/558#issuecomment-2286509843)

### CODE REVIEW

**Comment by yan-too** [comment]
Most pre-submit failures are unrelated, even build failures on Windows x86 -- but these are my debt from July release, 8320097, isinf/isnan not sufficiently covered in this case.

**Review by jerboaa — APPROVED** [review]
Looks OK to me.

**Comment by yan-too** [comment]
Thank you Severin!

macOS test failures are connection problems, apparently. 
Windows x86 does pass after JDK-8337312, thank you Andrew. I'm sorry I was too slow to fix it :-(

**Comment by jerboaa** [comment]
> macOS test failures are connection problems, apparently.

Yes. Known issues. See: https://github.com/openjdk/jdk8u-dev/pull/544#issuecomment-2250636257

**Pull request closed without merging**
