### PR TITLE
8313081: MonitoringSupport_lock should be unconditionally initialized after 8304074

### PR DESCRIPTION
**Pull request by phohensee**
Follow-on bug fix for [JDK-8304074](https://bugs.openjdk.org/browse/JDK-8304074) backport. Unclean backport from 11u, see https://github.com/openjdk/jdk11u-dev/pull/2287. Other than file location and context, the lock definition macro changed between 8 and 11, so the definition of MonitoringSupport_lock is different.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [ ] [JDK-8313081](https://bugs.openjdk.org/browse/JDK-8313081) needs maintainer approval
- [x] Commit message must refer to an issue

### Integration blocker
&nbsp;⚠️ Dependency #392 must be integrated first

### Issue
 * [JDK-8313081](https://bugs.openjdk.org/browse/JDK-8313081): MonitoringSupport_lock should be unconditionally initialized after 8304074 (**Bug** - P4 - Requested)

### Reviewers
 * [Volker Simonis](https://openjdk.org/census#simonis) (@simonis - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/393/head:pull/393` \
`$ git checkout pull/393`

Update a local copy of the PR: \
`$ git checkout pull/393` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/393/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 393`

View PR using the GUI difftool: \
`$ git pr show -t 393`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/393.diff">https://git.openjdk.org/jdk8u-dev/pull/393.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/393#issuecomment-1826887555)

### CODE REVIEW

**Review by simonis — APPROVED** [review]
Trivial fix. Looks good.

**Comment by phohensee** [comment]
/approval request Almost clean backport of a follow-on fix for the JDK-8304074 backport at https://github.com/openjdk/jdk8u-dev/pull/392. In production at Amazon for over two months.

**Comment by zhaosongzs** [comment]
Hi @phohensee, since the target branch `pr/392` has been deleted(https://github.com/openjdk/jdk8u-dev/tree/pr/392), please update the target branch of your pr, then your command `/open` will be processed by skara bot.

**Comment by jerboaa** [comment]
@phohensee Please target this PR onto `master` (or create a new one if you want). This PR is closed and is in the approval queue, which is strange. Ensure it's open, please.

**Comment by phohensee** [comment]
I've filed a replacement PR at https://github.com/openjdk/jdk8u-dev/pull/475.

**Comment by phohensee** [comment]
Submitted approval request for https://github.com/openjdk/jdk8u-dev/pull/475.

**Pull request closed without merging**
