### PR TITLE
8212677: X11 default visual support for IM status window on VNC

### PR DESCRIPTION
**Pull request by mrserb**
Hi all,

This pull request contains a backport of commit https://github.com/openjdk/jdk/commit/86cf7f8768977aea7b9ea1c90da498a1d91d2891 from the [openjdk/jdk](https://git.openjdk.org/jdk) repository.

The commit being backported was authored by Ichiroh Takiguchi on Feb 1, 2019 and was reviewed by Naoto Sato and Sergey Bylokhov

@takiguc please take a look.

Thanks!

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8212677](https://bugs.openjdk.org/browse/JDK-8212677): X11 default visual support for IM status window on VNC (**Bug** - P3)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/345/head:pull/345` \
`$ git checkout pull/345`

Update a local copy of the PR: \
`$ git checkout pull/345` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/345/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 345`

View PR using the GUI difftool: \
`$ git pr show -t 345`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/345.diff">https://git.openjdk.org/jdk8u-dev/pull/345.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/345#issuecomment-1648582484)

### CODE REVIEW

**Comment by takiguc** [comment]
Hello @mrserb .

Sorry I'm late.
I rebuilt test environment.
I could recreate the issue without the patch.
Also your patch worked fine with my test environment.

I don't have reviewer role.
Please find another reviewer.

Thanks.

**Comment by mrserb** [comment]
>I could recreate the issue without the patch.
>Also your patch worked fine with my test environment.

@takiguc, Thank you for the confirmation!

**Review by phohensee — APPROVED** [review]

**Review by gnu-andrew — APPROVED** [review]
Patch looks like a clean backport to me.
Please flag with `jdk8u-fix-request` for approval.

**Comment by gnu-andrew** [comment]
Approved.

**Pull request closed without merging**
