### PR TITLE
8173361: various crashes in JvmtiExport::post_compiled_method_load

### PR DESCRIPTION
**Pull request by dongbohe**
Hi,

This PR has been reviewed before move to github: https://mail.openjdk.java.net/pipermail/jdk8u-dev/2022-January/014487.html

Thanks,
hedongbo

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8173361](https://bugs.openjdk.org/browse/JDK-8173361): various crashes in JvmtiExport::post_compiled_method_load

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)
 * [Serguei Spitsyn](https://openjdk.org/census#sspitsyn) - Committer ⚠️ Added manually

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/9/head:pull/9` \
`$ git checkout pull/9`

Update a local copy of the PR: \
`$ git checkout pull/9` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/9/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 9`

View PR using the GUI difftool: \
`$ git pr show -t 9`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/9.diff">https://git.openjdk.org/jdk8u-dev/pull/9.diff</a>

</details>

### CODE REVIEW

**Comment by dongbohe** [comment]
Hi,

Can I get another review from 8u reviewer?

**Comment by dongbohe** [comment]
ping...

**Review by gnu-andrew — COMMENTED** [review]
This looks like a fairly clean backport. The only differences I see are `NoSafepointVerifier` and `No_Safepoint_Verifier` and the lack of the `#ifndef USDT2` block in 8u.

Can you merge this with jdk8u-dev/master so that the GitHub build checks run? Thanks.

**Comment by dongbohe** [comment]
Thanks for picking this up, I also reopened #19 .

**Comment by gnu-andrew** [comment]
I've approved the bug with `jdk8u-fix-yes` and can sponsor once you integrate.

**Pull request closed without merging**
