### PR TITLE
8283277: ISO 4217 Amendment 171 Update

### PR DESCRIPTION
**Pull request by dimitryc**
Please review the currency data update (ISO 4217 Amendment 171 Update)

CurrencyData.properties - conflict in copyright year
ValidateISO4217.java - conflict in copyright year and bug id list
tablea1.txt - conflict in FILEVERSION
LocaleDataTest.java - conflict in bug id list

Testing: jdk/test/java/util/Currency and jdk/test/sun/text/resources passed

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8283277](https://bugs.openjdk.org/browse/JDK-8283277): ISO 4217 Amendment 171 Update

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/202/head:pull/202` \
`$ git checkout pull/202`

Update a local copy of the PR: \
`$ git checkout pull/202` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/202/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 202`

View PR using the GUI difftool: \
`$ git pr show -t 202`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/202.diff">https://git.openjdk.org/jdk8u-dev/pull/202.diff</a>

</details>

### CODE REVIEW

**Comment by phohensee** [comment]
Does the FILEVERSION conflict point to another backport to do?

**Review by phohensee — APPROVED** [review]
Lgtm, but see comment.

**Comment by dimitryc** [comment]
> Does the FILEVERSION conflict point to another backport to do?

yes, it points to another bug (https://bugs.openjdk.org/browse/JDK-7102969) but I'm not really sure it makes sense to port this second patch.

**Comment by dimitryc** [comment]
> Lgtm, but see comment.

Thanks for the review. Added jdk8u-fix-request label.

**Comment by phohensee** [comment]
Imo worth backporting [JDK-7102969](https://bugs.openjdk.org/browse/JDK-7102969) because it covers 3 issues that are worth fixing.

7102969: currency.properties supercede not working correctly
8149452: j.t.SimpleDateFormat.getDateFormatSymbols().getZoneStrings() returns incorrect result for some time zones
8157138: Error while fetching currency instance by Currency.getInstance(currencycode)

**Review by gnu-andrew — APPROVED** [review]
Backport looks good to me, just a few adjustments for metadata and header differences.

Looks like the bug already has approval, so can we get this integrated please? I'd like to follow it up with the remaining data updates, including the recent Croatian adoption of the Euro, and include them with the security bundle for the upcoming release.

**Comment by gnu-andrew** [comment]
> Imo worth backporting [JDK-7102969](https://bugs.openjdk.org/browse/JDK-7102969) because it covers 3 issues that are worth fixing.
> 
> 7102969: currency.properties supercede not working correctly 8149452: j.t.SimpleDateFormat.getDateFormatSymbols().getZoneStrings() returns incorrect result for some time zones 8157138: Error while fetching currency instance by Currency.getInstance(currencycode)

I agree this looks worth backporting, though it's largely separate to the pending data updates which are more critical. I'll look into this for 8u372 once those are in.

**Comment by gnu-andrew** [comment]
PR for the next ISO 4217 update: https://github.com/openjdk/jdk8u-dev/pull/224

**Pull request closed without merging**
