### PR TITLE
8288865: [aarch64] LDR instructions must use legitimized addresses

### PR DESCRIPTION
**Pull request by apavlyutkin**
Hi! Here is a backport fixing offset large offsets on memory reading by Unsafe API for Aarch64. Except 11->8 path suffling the fix applied with the only change: only LDR-related part of the test is being backported cuz 8u-dev already has got STR-related one.

Verification (Ubuntu 18.04.6 LTS (GNU/Linux 4.9.0 aarch64)): 

hotspot/test/compiler/8235385/NonVolatileMemoryAccessWithLongOffset.java

10 of 10 runs PASS (5 of 10 runs FAILED before the patch applied)

Regression: hotspot/test/compiler

@theRealAph could you take a look, it's almost clean except the fact that STR-related part of test already presents in 8u-dev

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8288865](https://bugs.openjdk.org/browse/JDK-8288865): [aarch64] LDR instructions must use legitimized addresses

### Reviewers
 * [Andrew Dinn](https://openjdk.org/census#adinn) (@adinn - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/84/head:pull/84` \
`$ git checkout pull/84`

Update a local copy of the PR: \
`$ git checkout pull/84` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/84/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 84`

View PR using the GUI difftool: \
`$ git pr show -t 84`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/84.diff">https://git.openjdk.org/jdk8u-dev/pull/84.diff</a>

</details>

### CODE REVIEW

**Comment by apavlyutkin** [comment]
@jerboaa could you look at this one and approve if it's Ok? Thank you

**Comment by jerboaa** [comment]
I'll let @theRealAph approve this one.

**Pull request closed without merging**
