### PR TITLE
8320597: RSA signature verification fails on signed data that does not encode params correctly

### PR DESCRIPTION
**Pull request by alexeybakhtin**
Almost clean backport from [JDK11 PR](https://github.com/openjdk/jdk11u-dev/pull/2384)
the only differences in the removed decodeSignature() method

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8320597](https://bugs.openjdk.org/browse/JDK-8320597) needs maintainer approval

### Issue
 * [JDK-8320597](https://bugs.openjdk.org/browse/JDK-8320597): RSA signature verification fails on signed data that does not encode params correctly (**Bug** - P3 - Approved)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**) ⚠️ Review applies to [73e9909f](https://git.openjdk.org/jdk8u-dev/pull/404/files/73e9909f3e16e8b82f3cdca350c33e6f58caac3c)
 * [Martin Balao](https://openjdk.org/census#mbalao) (@martinuy - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/404/head:pull/404` \
`$ git checkout pull/404`

Update a local copy of the PR: \
`$ git checkout pull/404` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/404/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 404`

View PR using the GUI difftool: \
`$ git pr show -t 404`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/404.diff">https://git.openjdk.org/jdk8u-dev/pull/404.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/404#issuecomment-1855066149)

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
Seems OK. Please apply for approval.

**Comment by gnu-andrew** [comment]
> Seems OK. Please apply for approval.

Please wait until the dependency is in first, as this will then need to be rebased.

**Comment by alexeybakhtin** [comment]
Fixed merge conflicts after 8302017 is integrated into 8u-dev

**Review by martinuy — APPROVED** [review]
Thanks @alexeybakhtin for this backport. Looks good to me.

**Comment by alexeybakhtin** [comment]
Pre-submit test failures are not related to the current changes

**Review by gnu-andrew — APPROVED** [review]
Looks clean, bar the differing `decodeSignature` method.

**Pull request closed without merging**
