### PR TITLE
8202952: C2: Unexpected dead nodes after matching

### PR DESCRIPTION
**Pull request by dongbohe**
I would like to backport this patch to fix crash during C2 compilation. 

This patch doesn't apply cleanly due to context differences, and
I selected fuzzer tests from Fei Yang because the tests in the original commit cannot be reproduced on JDK8u.

Performed hotspot jtreg test on linux x86-64 platforms with -Xcomp options, new test fails without product change and passes with it.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8202952](https://bugs.openjdk.org/browse/JDK-8202952): C2: Unexpected dead nodes after matching (**Bug** - P2)

### Reviewers
 * [Roland Westrelin](https://openjdk.org/census#roland) (@rwestrel - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/291/head:pull/291` \
`$ git checkout pull/291`

Update a local copy of the PR: \
`$ git checkout pull/291` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/291/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 291`

View PR using the GUI difftool: \
`$ git pr show -t 291`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/291.diff">https://git.openjdk.org/jdk8u-dev/pull/291.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/291#issuecomment-1482403585)

### CODE REVIEW

**Review by rwestrel — APPROVED** [review]
Looks reasonable to me.

**Review by jerboaa — COMMENTED** [review]
If I'm not mistaken, then this patch applies to shared code, right? The [JDK 11 version](https://hg.openjdk.org/jdk-updates/jdk11u/rev/6ad83ea7dda7) did not, since it's in file `src/hotspot/cpu/x86/x86.ad` there. Thus, architecture specific (x86). Has this been tested on various architecture combinations (aarch64, ppc64le)? Am I missing something?

**Comment by dongbohe** [comment]
> Performed hotspot jtreg test on linux x86-64 platforms with -Xcomp options

I also performed hotspot jtreg test on linux aarch64 platforms with -Xcomp options, no regression found.

I don't have the architecture of ppc64le, can someone help me perform the test on ppc64le?

**Comment by jerboaa** [comment]
@sxa Hi! Could you please help with testing this 8u patch on ppc64le when you get a chance?

**Review by gnu-andrew — COMMENTED** [review]
Bot, please keep this one open.

The code was split into aarch64, ppc64 and x86 specific handling with [JDK-8154826](https://bugs.openjdk.org/browse/JDK-8154826). I don't think we should try backporting such a change into 8u, especially as [Volker already investigating this](https://mail.openjdk.org/pipermail/jdk8u-dev/2021-May/013899.html) for an AArch64 issue.

Could we not just change the line to use `X86_ONLY` instead of `LP64_ONLY`? The change would then be equivalent to what is in 11u.

**Comment by gnu-andrew** [comment]
Actually you would need to make it `X86_ONLY(LP64_ONLY(x))`, I believe, in order to exclude i686.

**Comment by dongbohe** [comment]
Good idea, the change looks better now.

**Review by gnu-andrew — APPROVED** [review]
Thanks. Looks safer to me now. @jerboaa?

**Comment by jerboaa** [comment]
Yes, this seems the better approach. Please let @rwestrel ack this updated patch version as well.

**Review by rwestrel — APPROVED** [review]
Update looks good.

**Comment by dongbohe** [comment]
Flagged for approval with jdk8u-fix-request.

**Comment by dongbohe** [comment]
Got the jdk8u-fix-yes.
/integrate

**Pull request closed without merging**
