### PR TITLE
8287132: Retire Runtime.runFinalizersOnExit so that it always throws UOE

### PR DESCRIPTION
**Pull request by dholmes-ora**
Forward port of the changes for SE 8 Maintenance release 4, as applied to jdk8u-ri, for:

[JDK-8287132](https://bugs.openjdk.org/browse/JDK-8287132): Retire Runtime.runFinalizersOnExit so that it always throws UOE

The changes applied "unclean" only with regard to trivial things like copyright year updates.

Thanks.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287132](https://bugs.openjdk.org/browse/JDK-8287132): Retire Runtime.runFinalizersOnExit so that it always throws UOE

### Reviewers
 * [Harold Seigel](https://openjdk.org/census#hseigel) (@hseigel - Committer)
 * [Iris Clark](https://openjdk.org/census#iris) (@irisclark - Author)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/92/head:pull/92` \
`$ git checkout pull/92`

Update a local copy of the PR: \
`$ git checkout pull/92` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/92/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 92`

View PR using the GUI difftool: \
`$ git pr show -t 92`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/92.diff">https://git.openjdk.org/jdk8u-dev/pull/92.diff</a>

</details>

### CODE REVIEW

**Review by hseigel — APPROVED** [review]
The changes look good.  Thanks for doing this.
Harold

**Review by irisclark — APPROVED** [review]
Spec changes as expected in JSR 337 MR 4.

Thanks!

**Comment by dholmes-ora** [comment]
Thanks for the reviews @hseigel  and @irisclark .

**Review by gnu-andrew — APPROVED** [review]
I agree this matches the version in jdk8u-ri with appropriate adjustments for newer copyright headers in 8u-dev. Changes also match the appropriate subset of [JDK-8198249](https://bugs.openjdk.org/browse/JDK-8198249) as also verified by Mandy on the original PR.

I've added `jdk8u-fix-yes` approval so this can be integrated now.

**Comment by dholmes-ora** [comment]
Thank you @gnu-andrew !

/integrate

**Pull request closed without merging**
