### PR TITLE
8305931: jdk/jfr/jcmd/TestJcmdDumpPathToGCRoots.java failed with "Expected chains but found none"

### PR DESCRIPTION
**Pull request by roberttoyonaga**
This is a backport of https://github.com/openjdk/jdk/commit/65be5e0c547d74ca7de288b164aa9bd6d6855685

This change to JFR test code is needed because TestJcmdDumpPathToGCRoots transiently fails because it can't guarantee the expected objects are sampled. The change improves cleanups between checks and also adds retries.

This should help resolve some test failures for Adoptium (see https://github.com/adoptium/aqa-tests/issues/2766)

Testing: the updated test/jdk/jdk/jfr/jcmd/TestJcmdDumpPathToGCRoots.java test passes.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] [JDK-8305931](https://bugs.openjdk.org/browse/JDK-8305931) needs maintainer approval
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8305931](https://bugs.openjdk.org/browse/JDK-8305931): jdk/jfr/jcmd/TestJcmdDumpPathToGCRoots.java failed with "Expected chains but found none" (**Bug** - P4 - Approved)

### Reviewers
 * [Thomas Stuefe](https://openjdk.org/census#stuefe) (@tstuefe - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/490/head:pull/490` \
`$ git checkout pull/490`

Update a local copy of the PR: \
`$ git checkout pull/490` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/490/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 490`

View PR using the GUI difftool: \
`$ git pr show -t 490`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/490.diff">https://git.openjdk.org/jdk8u-dev/pull/490.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/490#issuecomment-2093752763)

### CODE REVIEW

**Comment by roberttoyonaga** [comment]
Commenting so that this won't be closed due to inactivity. Could someone please help review this? I didn't have to make any additional changes, the backport was applied cleanly.

**Comment by tstuefe** [comment]
Hi Robert, what's wrong with the red GHA tests?

Besides that, please make sure, especially for a PR that has been dormant for a longer time, that you merge in the latest changes from upstream (we prefer merging over rebasing for a PR that is being discussed). Then the GHAs should be green, or the reds explainable. Then you can apply for approval (slash approval).

The fix itself looks good.

**Comment by roberttoyonaga** [comment]
Hi Thomas, I've pulled in the latest changes from master. With regard to the failing GHAs:

- Linux additional (hs s390x build only) /  Linux additional (hs ppc64le build only)
  - Fails in "Create sysroot" step with: `Cannot check Release signature; keyring file not available /usr/share/keyrings/debian-archive-keyring.gpg`. It seems like this is some sort of environment setup / infrastructure problem.

- Windows x86 (build debug) / Windows x86 (build release)
  -  Fails in `Download and unpack Visual Studio 2010` step with: `Extracting archive: C:\Users\runneradmin\VS2010Express1.iso Can't open as archive: 1`. It looks like the Visual Studio download source is no longer good. 

- macOS x64 (jdk/tier1) /  Linux x64 (jdk/tier1) / Linux x86 (jdk/tier1) / Windows x64 (jdk/tier1)
  - Fails `security/infra/java/security/cert/CertPathValidator/certification/CAInterop.java#teliasonerarootcav1` with: `Test threw exception: java.lang.RuntimeException: Intermediate Root CA not found in the chain`
  - I'm able to reproduce this locally on a clean master branch, so the failure seems independent of this PR.  It looks like the URL used in the test (https://juolukka.cover.sonera.net:10443) needs to be updated, but I'm not sure what to change it to.

- Windows x64 (hotspot/tier1)
  - Fails`runtime/CompressedOops/CompressedClassPointers.java` with:
`Execution failed: main threw exception: java.lang.RuntimeException: 'Narrow klass base: 0x0000000000000000, Narrow klass shift: 3' missing from stdout/stderr`
  - This doesn't seem related to the changes here since this PR only modifies JFR test code and doesn't affect compressed class pointers.

- Linux x86 (hotspot/tier1) 
  - Fails `gc/concurrentMarkSweep/SystemGCOnForegroundCollector.java` with: `Error. Program /home/runner/jdk-linux-x86/jdk-1.8.0-internal+0_linux-x86_bin/j2sdk-image/bin/java' timed out`
  - This also doesn't seem related to the changes here since this PR does not touch any GC-related code.

**Review by tstuefe — APPROVED** [review]
@roberttoyonaga Okay, thank you for checking!

LGTM

**Pull request closed without merging**
