### PR TITLE
8303462: Bump update version of OpenJDK: 8u382

### PR DESCRIPTION
**Pull request by gnu-andrew**
Rampdown for 8u372 has begun. 8u-dev needs to transition to 8u382.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8303462](https://bugs.openjdk.org/browse/JDK-8303462): Bump update version of OpenJDK: 8u382

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/275/head:pull/275` \
`$ git checkout pull/275`

Update a local copy of the PR: \
`$ git checkout pull/275` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/275/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 275`

View PR using the GUI difftool: \
`$ git pr show -t 275`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/275.diff">https://git.openjdk.org/jdk8u-dev/pull/275.diff</a>

</details>

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
LGTM.

**Comment by gnu-andrew** [comment]
Thanks. Flagged for approval.

**Comment by gnu-andrew** [comment]
I see `jdk8u-fix-yes`.

**Pull request closed without merging**
