### PR TITLE
8320964: sun/tools/native2ascii/Native2AsciiTests.sh fails on Japanese

### PR DESCRIPTION
**Pull request by ktakakuri**
I would like to fix this issue because the test dose not work as intended.
Could someone please review it?

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8320964](https://bugs.openjdk.org/browse/JDK-8320964) needs maintainer approval

### Issue
 * [JDK-8320964](https://bugs.openjdk.org/browse/JDK-8320964): sun/tools/native2ascii/Native2AsciiTests.sh fails on Japanese (**Bug** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/400/head:pull/400` \
`$ git checkout pull/400`

Update a local copy of the PR: \
`$ git checkout pull/400` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/400/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 400`

View PR using the GUI difftool: \
`$ git pr show -t 400`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/400.diff">https://git.openjdk.org/jdk8u-dev/pull/400.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/400#issuecomment-1831672441)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by phohensee** [comment]
linux-x86 failure seems unrelated, but please have a look at the windows-x64 failure.

**Comment by ktakakuri** [comment]
@gnu-andrew 
Could you please check for added fixes?

**Review by gnu-andrew — CHANGES_REQUESTED** [review]
Could you indent the new bug ID as in [VerifyCACerts.java](https://github.com/openjdk/jdk8u/blob/master/jdk/test/sun/security/lib/cacerts/VerifyCACerts.java) (i.e. so the '8' in the new ID lines up with the '4' in the one above)? Sorry for providing you with a bad example at first in `LocaleTest.java`

With that change, this should be good to go.

**Comment by ktakakuri** [comment]
I fixed the indent. Thank you.

**Comment by ktakakuri** [comment]
@gnu-andrew 
Is the fix correct?

**Review by phohensee — APPROVED** [review]

**Review by gnu-andrew — APPROVED** [review]
Yes, looks good.

**Comment by gnu-andrew** [comment]
Sorry for the delay, I've been caught up with the upcoming release.
Please apply for approval and we can get this in.

**Comment by ktakakuri** [comment]
Thank you for checking my fix.
I will submit a fix request.

**Comment by ktakakuri** [comment]
/approval request I would like to fix this issue because it always fails in regression testing, resulting in extra costs for checking the test results.
There is no risk.
Testing:
I tested it on Windows and Linux.

**Pull request closed without merging**
