### PR TITLE
8268457: XML Transformer outputs Unicode supplementary character incorrectly to HTML

### PR DESCRIPTION
**Pull request by ktakakuri**
Hi all,

JDK8 reproduces the reported bug and I would like to backport this patch.
The patch is not clean. 

* Eliminated the use of test libraries and TestNG, and embedded compareWithGold() method and compareStringWithGold() method.
* Removed indentation from SurrogateTest1.html because indentation is not added in ToHTMLStream.java in JDK8. This difference is due to JDK-8175793 introduced in JDK9.

There is a related patch JDK-8274606, and I have proposed a separate backport for it. #518

Testing: All tests under jdk/test/javax/xml/jaxp/

Thank you.

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8268457](https://bugs.openjdk.org/browse/JDK-8268457) needs maintainer approval

### Issue
 * [JDK-8268457](https://bugs.openjdk.org/browse/JDK-8268457): XML Transformer outputs Unicode supplementary character incorrectly to HTML (**Bug** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/517/head:pull/517` \
`$ git checkout pull/517`

Update a local copy of the PR: \
`$ git checkout pull/517` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/517/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 517`

View PR using the GUI difftool: \
`$ git pr show -t 517`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/517.diff">https://git.openjdk.org/jdk8u-dev/pull/517.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/517#issuecomment-2159755380)
</details>

### CODE REVIEW

**Review by phohensee — APPROVED** [review]

**Comment by phohensee** [comment]
GHA test failures appear infrastructure related.

**Comment by ktakakuri** [comment]
/approval request JDK8 reproduces the reported bug and I would like to backport this patch.
There is a low risk because the logic around the changes is the same as JDK18.
The original patch does not apply cleanly to 8u, but I verified that it works.
There is a related patch JDK-8274606, and I have proposed a separate backport for it.
Testing: All tests under jdk/test/javax/xml/jaxp/

**Comment by ktakakuri** [comment]
This pull request is pending approval of the Fix Request.
I comment to not close.

**Comment by ktakakuri** [comment]
This pull request is pending approval of the Fix Request.
I comment to not close.

**Comment by ktakakuri** [comment]
This pull request is pending approval of the Fix Request.
I comment to not close.

**Comment by ktakakuri** [comment]
This pull request is pending approval of the Fix Request.
I comment to not close.

**Review by gnu-andrew — APPROVED** [review]
Change looks good to me.

**Comment by gnu-andrew** [comment]
Moved to 8u452; see https://mail.openjdk.org/pipermail/jdk8u-dev/2024-December/019551.html

**Pull request closed without merging**
