### PR TITLE
8238274: (sctp) JDK-7118373 is not fixed for SctpChannel

### PR DESCRIPTION
**Pull request by ktakakuri**
This is a backport of JDK-8238274: (sctp) JDK-7118373 is not fixed for SctpChannel.

This backport is not clean because the test added in this fix uses an API that is not in JDK8.  
It has been replaced by the API that is available in JDK8, but the logic of the test remains unchanged.

Also, the constant LIMIT_LINES used in the test must be 3 due to differences in the behavior of the ServerSocket constructor.  
When the constructor of ServerSocket is called, the file descriptor is not created in JDK17, but it is created in JDK8, so the number of lines obtained by lsof is different.

Testing:  
jdk/com/sun/nio/sctp  
on Linux x86_64

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] [JDK-8238274](https://bugs.openjdk.org/browse/JDK-8238274) needs maintainer approval
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8238274](https://bugs.openjdk.org/browse/JDK-8238274): (sctp) JDK-7118373 is not fixed for SctpChannel (**Bug** - P4 - Approved)

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [533fc5ee](https://git.openjdk.org/jdk8u-dev/pull/427/files/533fc5ee114486dcaff16d3711c8919b7a9e225b)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/427/head:pull/427` \
`$ git checkout pull/427`

Update a local copy of the PR: \
`$ git checkout pull/427` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/427/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 427`

View PR using the GUI difftool: \
`$ git pr show -t 427`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/427.diff">https://git.openjdk.org/jdk8u-dev/pull/427.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/427#issuecomment-1908016191)

### CODE REVIEW

**Review by phohensee — APPROVED** [review]
Almost the same as the 11u backport. Lgtm.

**Comment by phohensee** [comment]
GHA failures look to be infrastructure issues.

**Comment by ktakakuri** [comment]
/approval request This fix adds the preClose check appropriately. The test added in this patch do not work as is in 8u, so I have made some modifications.
Testing:
jdk/com/sun/nio/sctp on Linux x86_64

**Review by gnu-andrew — CHANGES_REQUESTED** [review]
There is actually a replacement for `List.of` in `jdk/test/lib/testlibrary/jdk/testlibrary/Utils.java`, so you can replace this with `Utils.listOf` to get the same behaviour.

The other changes to the testcase look fine.

**Comment by ktakakuri** [comment]
Thank you.
I replaced List.of with Utils.listOf.

**Pull request closed without merging**
