### PR TITLE
8233551: [TESTBUG] SelectEditTableCell.java fails on MacOS

### PR DESCRIPTION
**Pull request by Rudometov**
Backport for [JDK-8233551](https://bugs.openjdk.org/browse/JDK-8233551) [TESTBUG] SelectEditTableCell.java fails on MacOS (https://github.com/openjdk/jdk/commit/9b3fb5d1d5a6a3f0fc699b10bdff6d43ae8d1898)

Backport for test fix from [JDK-7124218](https://bugs.openjdk.org/browse/JDK-7124218).
No risk, only a test change.
Clean backport except for ProblemList.
Test passes during manual run.

This PR depends on https://github.com/openjdk/jdk8u-dev/pull/160

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8233551](https://bugs.openjdk.org/browse/JDK-8233551): [TESTBUG] SelectEditTableCell.java fails on MacOS

### Reviewers
 * [Paul Hohensee](https://openjdk.org/census#phh) (@phohensee - **Reviewer**) ⚠️ Review applies to [0a870669](https://git.openjdk.org/jdk8u-dev/pull/162/files/0a870669e972d810e47dc530ce6eb1263c762eac)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/162/head:pull/162` \
`$ git checkout pull/162`

Update a local copy of the PR: \
`$ git checkout pull/162` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/162/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 162`

View PR using the GUI difftool: \
`$ git pr show -t 162`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/162.diff">https://git.openjdk.org/jdk8u-dev/pull/162.diff</a>

</details>

### CODE REVIEW

**Review by phohensee — CHANGES_REQUESTED** [review]
This PR contains the entirety of SelectEditTableCell.java. The latter was created by JDK-7124218 (which you're backporting first), so this PR should include only the edits.

**Comment by Rudometov** [comment]
Thank you. I've changed the base of this PR to pr160, so the only changes seen here are the actual pr162 changes.

**Review by phohensee — APPROVED** [review]
Thanks, Victor. Lgtm.

**Pull request closed without merging**
