### PR TITLE
8335912: Add an operation mode to the jar command when extracting to not overwriting existing files

### PR DESCRIPTION
**Pull request by alexeybakhtin**
Not clean backport from JDK11 patch:
- No GNUStyle options in JDK8
- No support for long options
- Tests updated to use JDK8 API
- Removed subtest for long option

JTREG tests passed

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] Change requires CSR request [JDK-8344651](https://bugs.openjdk.org/browse/JDK-8344651) to be approved
- [x] [JDK-8335912](https://bugs.openjdk.org/browse/JDK-8335912) needs maintainer approval

### Issues
 * [JDK-8335912](https://bugs.openjdk.org/browse/JDK-8335912): Add an operation mode to the jar command when extracting to not overwriting existing files (**Enhancement** - P5 - Approved)
 * [JDK-8344651](https://bugs.openjdk.org/browse/JDK-8344651): Add an operation mode to the jar command when extracting to not overwriting existing files (**CSR**)

### Reviewers
 * [Martin Balao](https://openjdk.org/census#mbalao) (@martinuy - **Reviewer**)
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/608/head:pull/608` \
`$ git checkout pull/608`

Update a local copy of the PR: \
`$ git checkout pull/608` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/608/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 608`

View PR using the GUI difftool: \
`$ git pr show -t 608`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/608.diff">https://git.openjdk.org/jdk8u-dev/pull/608.diff</a>

</details>
<details><summary>Using Webrev</summary>

[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/608#issuecomment-2502200619)
</details>

### CODE REVIEW

**Review by martinuy — COMMENTED** [review]
Thanks for this contribution.

One minor comment regarding the text "-k/k" in the warning message.  Passing the argument as a standalone "-k" seems to work only with GNUStyleOptions. We can pass "-k..." (along with other options), but the most typical invocation would be "-xk...". I'm okay with the suggested "-k/k" text but would have been okay with with "k" too.

I have the impression that the addition of "main.help.opt.extract.keep-old-files" is related to GNUStyleOptions. The place where "-k  Do not overwrite existing files" was added is not the exact equivalent, but we should be able to live with that.  Just wonder if we should add "k" to "[vfmn0PMe]". What do you think?

The test "testGnuOptionsKeptOldFile" does not apply, does it? The leading "-" is optional for the non-Gnu interface.

**Comment by martinuy** [comment]
@alexeybakhtin , thanks for considering the suggested changes.

Looks like `jar_pt_BR.properties` was missed, if we really want to update all `jar...properties`. Changes to `jar...properties` make me think that the new option will not be documented for languages other than English. Would be very tricky to do the translation for all languages and perhaps is acceptable not to do it, as it has not been done for JDK main line either. While the spirit in 8u was different, it's not unreasonable for developer tools to be in English only. I'd suggest to update `jar_pt_BR.properties` and leave it there. The reader will probably fall back to English for an explanation of the (undocumented) `k`. If people really want to do the translation, I can contribute Spanish and Portuguese.

What do you think?

**Comment by alexeybakhtin** [comment]
> @alexeybakhtin , thanks for considering the suggested changes.
> 
> Looks like `jar_pt_BR.properties` was missed, if we really want to update all `jar...properties`. Changes to `jar...properties` make me think that the new option will not be documented for languages other than English. Would be very tricky to do the translation for all languages and perhaps is acceptable not to do it, as it has not been done for JDK main line either. While the spirit in 8u was different, it's not unreasonable for developer tools to be in English only. I'd suggest to update `jar_pt_BR.properties` and leave it there. The reader will probably fall back to English for an explanation of the (undocumented) `k`. If people really want to do the translation, I can contribute Spanish and Portuguese.
> 
> What do you think?

Thank you @martinuy 
Added the 'k' option to `jar_pt_BR.properties`. Translation for new and missed options can be done separately.

**Review by martinuy — APPROVED** [review]

**Review by martinuy — APPROVED** [review]

**Review by gnu-andrew — APPROVED** [review]
The change looks good to me. Martin has already covered the same comments I would have had about the initial version. I note that the simple `warn` method is pulled in from [JDK-8164805](https://bugs.openjdk.org/browse/JDK-8164805), which is fine because we hardly want to backport a change to do with modular JARs to 8u.

I appreciate you considering the translated property files, as I think there's a building problem there in update releases. I'll say more on this in reply to Martin's comment.

**Comment by gnu-andrew** [comment]
> @alexeybakhtin , thanks for considering the suggested changes.
> 
> Looks like `jar_pt_BR.properties` was missed, if we really want to update all `jar...properties`. Changes to `jar...properties` make me think that the new option will not be documented for languages other than English. Would be very tricky to do the translation for all languages and perhaps is acceptable not to do it, as it has not been done for JDK main line either. While the spirit in 8u was different, it's not unreasonable for developer tools to be in English only. I'd suggest to update `jar_pt_BR.properties` and leave it there. The reader will probably fall back to English for an explanation of the (undocumented) `k`. If people really want to do the translation, I can contribute Spanish and Portuguese.
> 
> What do you think?

They do tend to get documented, but in separate updates from the i18n team. The last one is [JDK-8337054](https://github.com/openjdk/jdk/commit/e68df528f80cff3a5564a12b7ec71a920800ce28) for JDK 23. I suspect we'll get another mass update for 24 when it is released, which will include these.

There is an issue with backport releases that we don't get these updates when Oracle cede ownership of them. The last one for 8u is [8214357](https://github.com/openjdk/jdk8u/commit/419ea432e817aabdd064665af594c018135a508d). We likely need to do a check for where the base properties file has keys that the translations do not, but content changes to existing keys will be harder to spot.

Contributing translations for this to trunk might be a good way to open conversation on this, if you have the time.

**Comment by sendaoYan** [comment]
The two newly added tests fails.

Tests:
```
tools/jar/ExtractFilesTest.java
tools/jar/MultipleManifestTest.java
```

Test log snippet:
```
/tmp/tone/run/jtreg/jdk-repo/jdk/test/tools/jar/ExtractFilesTest.java:38: error: package org.junit.jupiter.api does not exist
import org.junit.jupiter.api.TestInstance;
                            ^
/tmp/tone/run/jtreg/jdk-repo/jdk/test/tools/jar/ExtractFilesTest.java:39: error: package org.junit.jupiter.api.TestInstance does not exist
import org.junit.jupiter.api.TestInstance.Lifecycle;
                                         ^
/tmp/tone/run/jtreg/jdk-repo/jdk/test/tools/jar/ExtractFilesTest.java:54: error: cannot find symbol
@TestInstance(Lifecycle.PER_CLASS)
 ^
  symbol: class TestInstance
```

**Comment by sendaoYan** [comment]
The minimum jtreg version of jdk11u-dev is 7.3.1+1, the minimum jtreg version of jdk8u-dev seems to be 5.1. So these two tests can't backport from jdk11u-dev to jdk8u-dev directively

**Comment by alexeybakhtin** [comment]
> The minimum jtreg version of jdk11u-dev is 7.3.1+1, the minimum jtreg version of jdk8u-dev seems to be 5.1. So these two tests can't backport from jdk11u-dev to jdk8u-dev directively. The `org.junit.jupiter.api` does not exist in jtreg5.1

Sorry for breaking this compatibility, but is there any document that defines the minimum jtreg version for jdk8u-dev?

**Comment by sendaoYan** [comment]
> is there any document that defines the minimum jtreg version for jdk8u-dev?

jdk8u-dev:

https://github.com/openjdk/jdk8u-dev/blob/master/make/conf/test-dependencies#L29

jdk11u-dev:

https://github.com/openjdk/jdk11u-dev/blob/master/make/conf/github-actions.conf#L29

or:

https://github.com/openjdk/jdk11u-dev/blob/master/test/jdk/TEST.ROOT#L65

**Comment by alexeybakhtin** [comment]
Thank you @sendaoYan,

Could you suggest how we should deal with these tests? Should I submit an issue to remove these tests OR add them to the ProblemList OR update jtreg requirements?

**Comment by sendaoYan** [comment]
> Could you suggest how we should deal with these tests? Should I submit an issue to remove these tests OR add them to the ProblemList OR update jtreg requirements?

Maybe there are some tests in jdk8u-dev depends jtreg5.1, so I think update jtreg version requirements maybe not a good idea.
I think the better way is resolve the dependencies of jtreg7.3.1 for these tests, similar to https://github.com/openjdk/jdk11u-dev/pull/2553

**Comment by alexeybakhtin** [comment]
@sendaoYan ,

Thank you for the finding one more time. Please have a look at the proposed fix at https://github.com/openjdk/jdk8u-dev/pull/612

**Pull request closed without merging**
