### PR TITLE
8067941: [TESTBUG] Fix tests for OS with 64K page size.

### PR DESCRIPTION
**Pull request by dongbohe**
Hi,

I would like to backport this patch to fix tests for OS with 64K page size.
Patch does not apply cleanly: 
JDK-8062854[1] move StackOverflowBug.java and Test8009761.java to corresponding subfolders.
Test8009761.java context is different because JDK-8021775[2] and JDK-8011397[3] doesn't in jdk8u.
Change to TestGCLogMessages.java is excluded because it was added in JDK-8027962[4].
Chnage to WBStackSize.java is excluded because JDK-8032970[5] does not exist in 8.

I changed Xss in StackOverflowBug.java, Test8009761.java, TestRecursiveReplacedException.java, 
StackOverflowGuardPagesOff.java, TestStackBangMonitorOwned.java and TestStackBangRbp.java from
392k to 512k according to JDK-8159335[6], because JDK-8173339[7] changed StackShadowPages to 20, xss needs at least 456k.

Testing: Performed full jtreg test aarch64-linux-gnu platforms with 64k page size.
Checked that StackOverflowBug.java, Test8009761.java, TestRecursiveReplacedException.java,
StackOverflowGuardPagesOff.java, TestStackBangMonitorOwned.java, TestStackBangRbp.java,
TestHumongousAllocInitialMark.java, TestCMSHeapSizeFlags.java, TestG1HeapSizeFlags.java,
TestParallelHeapSizeFlags.java, TestSerialHeapSizeFlags.java fails without the patch
and passes with the patch on Aarch64 with 64K page size.

[1] https://bugs.openjdk.java.net/browse/JDK-8062854
[2] https://bugs.openjdk.java.net/browse/JDK-8021775
[3] https://bugs.openjdk.java.net/browse/JDK-8011397
[4] https://bugs.openjdk.java.net/browse/JDK-8027962
[5] https://bugs.openjdk.java.net/browse/JDK-8032970
[6] https://bugs.openjdk.java.net/browse/JDK-8159335
[7] https://bugs.openjdk.java.net/browse/JDK-8173339

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8067941](https://bugs.openjdk.org/browse/JDK-8067941): [TESTBUG] Fix tests for OS with 64K page size.

### Reviewers
 * [Andrew John Hughes](https://openjdk.org/census#andrew) (@gnu-andrew - **Reviewer**) ⚠️ Review applies to [565302ee](https://git.openjdk.org/jdk8u-dev/pull/71/files/565302ee55dd27c70dfc76cd3680a001b77126e1)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev pull/71/head:pull/71` \
`$ git checkout pull/71`

Update a local copy of the PR: \
`$ git checkout pull/71` \
`$ git pull https://git.openjdk.org/jdk8u-dev pull/71/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 71`

View PR using the GUI difftool: \
`$ git pr show -t 71`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/71.diff">https://git.openjdk.org/jdk8u-dev/pull/71.diff</a>

</details>

### CODE REVIEW

**Comment by gnu-andrew** [comment]
SKARA seems to be confused by the closure of #66 due to timeout, not integration. Please re-open that one so we can correctly integrate it as a dependency for this one.

**Comment by gnu-andrew** [comment]
Filed https://bugs.openjdk.org/browse/SKARA-1568 for the issue with SKARA treating a timed-out PR as an integrated PR

**Review by gnu-andrew — APPROVED** [review]
Changes make sense to me, given the bump to AArch64 stack sizes in JDK-8173339

I assume this doesn't affect other architectures, as we don't have JDK-8159335 which bumped the stack sizes on ppc64?

8u now:
~~~
$ grep -r 'StackShadowPages' hotspot/|grep pd_global
hotspot/src/cpu/aarch64/vm/globals_aarch64.hpp:define_pd_global(intx, StackShadowPages, 20 DEBUG_ONLY(+5));
hotspot/src/cpu/sparc/vm/globals_sparc.hpp:define_pd_global(intx, StackShadowPages, 10 DEBUG_ONLY(+1));
hotspot/src/cpu/sparc/vm/globals_sparc.hpp:define_pd_global(intx, StackShadowPages, 3 DEBUG_ONLY(+1));
hotspot/src/cpu/x86/vm/globals_x86.hpp:define_pd_global(intx, StackShadowPages, NOT_WIN64(20) WIN64_ONLY(6) DEBUG_ONLY(+2));
hotspot/src/cpu/x86/vm/globals_x86.hpp:define_pd_global(intx, StackShadowPages, 4 DEBUG_ONLY(+5));
hotspot/src/cpu/zero/vm/globals_zero.hpp:define_pd_global(intx,  StackShadowPages,     5 LP64_ONLY(+1) DEBUG_ONLY(+3));
hotspot/src/os_cpu/aix_ppc/vm/globals_aix_ppc.hpp:define_pd_global(intx, StackShadowPages,         6 DEBUG_ONLY(+2));
hotspot/src/os_cpu/linux_ppc/vm/globals_linux_ppc.hpp:define_pd_global(intx, StackShadowPages,         6 DEBUG_ONLY(+2));
~~~

11u now:
~~~
$ grep -r 'define DEFAULT_STACK_SHADOW_PAGES' ../jdk11u-dev/src/hotspot
../jdk11u-dev/src/hotspot/cpu/x86/globals_x86.hpp:#define DEFAULT_STACK_SHADOW_PAGES (NOT_WIN64(20) WIN64_ONLY(7) DEBUG_ONLY(+2))
../jdk11u-dev/src/hotspot/cpu/x86/globals_x86.hpp:#define DEFAULT_STACK_SHADOW_PAGES (4 DEBUG_ONLY(+5))
../jdk11u-dev/src/hotspot/cpu/aarch64/globals_aarch64.hpp:#define DEFAULT_STACK_SHADOW_PAGES (20 DEBUG_ONLY(+5))
../jdk11u-dev/src/hotspot/cpu/arm/globals_arm.hpp:#define DEFAULT_STACK_SHADOW_PAGES (5 DEBUG_ONLY(+1))
../jdk11u-dev/src/hotspot/cpu/ppc/globals_ppc.hpp:#define DEFAULT_STACK_SHADOW_PAGES (20 DEBUG_ONLY(+2))
../jdk11u-dev/src/hotspot/cpu/s390/globals_s390.hpp:#define DEFAULT_STACK_SHADOW_PAGES   (20 DEBUG_ONLY(+4))
../jdk11u-dev/src/hotspot/cpu/sparc/globals_sparc.hpp:#define DEFAULT_STACK_SHADOW_PAGES (20 DEBUG_ONLY(+2))
../jdk11u-dev/src/hotspot/cpu/zero/globals_zero.hpp:#define DEFAULT_STACK_SHADOW_PAGES (5 LP64_ONLY(+1) DEBUG_ONLY(+3))
~~~

**Comment by dongbohe** [comment]
Yes, theoretically this does not affect other architectures.

**Comment by dongbohe** [comment]
But we need to explain the impact of [JDK-8173339](https://bugs.openjdk.org/browse/JDK-8173339) in the jdk8u release. The minimum value of xss on Aarch64 is changed from 164k to 228k on 4k page size(328k->456k on 64k page size). If the user-specified xss is smaller than the current minimum value, the value of xss needs to be adjusted to be larger than the minimum required value to prevent JVM startup failure.

**Comment by gnu-andrew** [comment]
8u-dev is currently closed for rampdown.
I'll sponsor this once it reopens.

**Pull request closed without merging**
