### PR TITLE
8186464: ZipFile cannot read some InfoZip ZIP64 zip files

### PR DESCRIPTION
**Pull request by fitzsim**
Hello,

I am submitting this patch, written by `Andrew John Hughes <andrew@openjdk.org>`, which is a backport of:

```
commit 02b9452ed39eccdfe3210e65b17d4759333c0f15
Author: Xueming Shen <sherman@openjdk.org>
Date:   Wed Sep 20 16:41:54 2017 -0700

    8186464: ZipFile cannot read some InfoZip ZIP64 zip files
    
    Reviewed-by: martin
```

This patch was applied to the Red Hat 1.8.0 RPMs in June 2020, so it has been deployed to Red Hat customers for over three years.

I verified that the patch applies cleanly to `jdk8u-dev` `master`.  I confirmed that with the fix portion of the patch reverted, the `ReadZip.java` test portion of the patch produces this exception:

```
java.lang.RuntimeException: zipfile: zip64 end failed
	at ReadZip.main(ReadZip.java:209)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:750)
```

With the fix applied the test passes:

`Passed: java/util/zip/ZipFile/ReadZip.java`

With the patch applied on top of `jdk8u-dev` `master` tip, `3dc011b7ff955f6c1334058f300708412b21a3ad`, `make test` on Fedora 38 x86-64 passes, with:

`Test results: passed: 3,122`

I also retested the test cases in https://bugs.openjdk.org/browse/JDK-8186464 and confirmed that without this backport, they fail, and with the backport they succeed.

Thank you,
Thomas

---------
### Progress
- [ ] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [ ] [JDK-8186464](https://bugs.openjdk.org/browse/JDK-8186464) needs maintainer approval

### Error
&nbsp;⚠️ OCA signatory status must be verified

### Issue
 * [JDK-8186464](https://bugs.openjdk.org/browse/JDK-8186464): ZipFile cannot read some InfoZip ZIP64 zip files (**Bug** - P3)

### Contributors
 * Andrew John Hughes `<andrew@openjdk.org>`

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/445/head:pull/445` \
`$ git checkout pull/445`

Update a local copy of the PR: \
`$ git checkout pull/445` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/445/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 445`

View PR using the GUI difftool: \
`$ git pr show -t 445`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/445.diff">https://git.openjdk.org/jdk8u-dev/pull/445.diff</a>

</details>

### CODE REVIEW

**Comment by fitzsim** [comment]
I am contributing this work on behalf of my employer, Red Hat. /covered

**Comment by gnu-andrew** [comment]
Windows x86 looks like the same issue as https://bugs.openjdk.org/browse/JDK-8324184
The definition of `end64buf` needs to be moved to the start of the block with the others.

**Comment by gnu-andrew** [comment]
@fitzsim can we close this on in favour of #452 ?

**Comment by fitzsim** [comment]
Closing in favour of #452.

**Pull request closed without merging**
