### PR TITLE
8305400: ISO 4217 Amendment 175 Update

### PR DESCRIPTION
**Pull request by Karm**
backport 8c243a3 JDK11

---------
### Progress
- [x] Change must be properly reviewed (1 review required, with at least 1 [Reviewer](https://openjdk.org/bylaws#reviewer))
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue
- [x] [JDK-8305400](https://bugs.openjdk.org/browse/JDK-8305400) needs maintainer approval

### Issue
 * [JDK-8305400](https://bugs.openjdk.org/browse/JDK-8305400): ISO 4217 Amendment 175 Update (**Bug** - P3 - Approved)

### Reviewers
 * [Severin Gehwolf](https://openjdk.org/census#sgehwolf) (@jerboaa - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk8u-dev.git pull/559/head:pull/559` \
`$ git checkout pull/559`

Update a local copy of the PR: \
`$ git checkout pull/559` \
`$ git pull https://git.openjdk.org/jdk8u-dev.git pull/559/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 559`

View PR using the GUI difftool: \
`$ git pr show -t 559`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk8u-dev/pull/559.diff">https://git.openjdk.org/jdk8u-dev/pull/559.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jdk8u-dev/pull/559#issuecomment-2286725157)

### CODE REVIEW

**Review by jerboaa — APPROVED** [review]
LGTM. Seems clean to the JDK 11 version modulo `FILEVERSION` differences.

**Comment by jerboaa** [comment]
Please apply for approval using the `/approval` command.

**Comment by Karm** [comment]
> ⚠️ @Karm the full name on your profile does not match the author name in this pull requests' [HEAD](https://git.openjdk.org/jdk8u-dev/pull/559/commits/cf4ea7164eb4ead50902ca72d733b8bd4f1cc229) commit. If this pull request gets integrated then the author name from this pull requests' [HEAD](https://git.openjdk.org/jdk8u-dev/pull/559/commits/cf4ea7164eb4ead50902ca72d733b8bd4f1cc229) commit will be used for the resulting commit. If you wish to push a new commit with a different author name, then please run the following commands in a local repository of your personal fork:
> 
> ```
> $ git checkout JDK-8305400-amendment-175
> $ git commit --author='Preferred Full Name <you@example.com>' --allow-empty -m 'Update full name'
> $ git push
> ```

@jerboaa 

Any idea what the machine is worrying about, please?

The commit is

```
Author: Michal Karm Babacek <karm@redhat.com>
```
and it is signed...

**Comment by jerboaa** [comment]
> @Karm 8305400: The approval [request](https://bugs.openjdk.org/browse/JDK-8305400?focusedCommentId=14698720) has been created successfully.

The request comment is:
```
[jdk8u-fix-request] Approval Request from Karm Michal Babacek
```

@Karm This is not a suitable approval request comment. It should mention the anticipated risk, what testing you have done and why it should get approved in the first place. Please update the comment by using `/approval request <comment>`. See also point 6 in: https://wiki.openjdk.org/display/JDKUpdates/How+to+contribute+or+backport+a+fix

**Comment by jerboaa** [comment]
> > ⚠️ @Karm the full name on your profile does not match the author name in this pull requests' [HEAD](https://git.openjdk.org/jdk8u-dev/pull/559/commits/cf4ea7164eb4ead50902ca72d733b8bd4f1cc229) commit. If this pull request gets integrated then the author name from this pull requests' [HEAD](https://git.openjdk.org/jdk8u-dev/pull/559/commits/cf4ea7164eb4ead50902ca72d733b8bd4f1cc229) commit will be used for the resulting commit. If you wish to push a new commit with a different author name, then please run the following commands in a local repository of your personal fork:
> > ```
> > $ git checkout JDK-8305400-amendment-175
> > $ git commit --author='Preferred Full Name <you@example.com>' --allow-empty -m 'Update full name'
> > $ git push
> > ```
> 
> @jerboaa
> 
> Any idea what the machine is worrying about, please?
> 
> The commit is
> 
> ```
> Author: Michal Karm Babacek <karm@redhat.com>
> ```
> 
> and it is signed...

It says the full name in your github profile (`Karm Michal Babacek`) doesn't match the name in the commit (`Michal Karm Babacek`). I'd suggest to fix it so they match and the warning should be gone.

**Comment by Karm** [comment]
/approval request Low risk metadata update backported from JDK 11. It bumps datafile version, does not touch actual currencies. No regression test/java/util/Currency/. Motivation: Gradually bring currencies updates on par with JDK 11.

**Comment by jerboaa** [comment]
GHA failures are unrelated.

/sponsor

**Pull request closed without merging**
